// SPDX-FileCopyrightText: 2026 彭旭
// SPDX-License-Identifier: AGPL-3.0-only
package migration

func DesktopPetActionDefinitionsMigration() Migration {
	return Migration{
		Version:           "202607240002",
		Name:              "add_desktop_pet_action_definitions_table",
		AcceptedChecksums: []string{"147f91eaafa7413b3b7a8b94294d0208578ee3009133f6e13aba2e1bdd57d0db"},
		Up: func(s *Step) error {
			s.CreateTable(`CREATE TABLE IF NOT EXISTS desktop_pet_action_definitions (
id INTEGER PRIMARY KEY AUTOINCREMENT,
action_key TEXT NOT NULL UNIQUE,
name TEXT NOT NULL DEFAULT '',
description TEXT DEFAULT '',
category_key TEXT NOT NULL DEFAULT '',
category_name TEXT NOT NULL DEFAULT '',
supports_default_idle INTEGER NOT NULL DEFAULT 0,
recommended INTEGER NOT NULL DEFAULT 0,
enabled INTEGER NOT NULL DEFAULT 1,
sort_order INTEGER NOT NULL DEFAULT 0,
definition_version INTEGER NOT NULL DEFAULT 1,
default_frame_count INTEGER NOT NULL DEFAULT 8,
estimated_generation_count INTEGER NOT NULL DEFAULT 1,
created_at TEXT DEFAULT '',
updated_at TEXT DEFAULT ''
)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('idle_normal','普通待机','角色保持站立并进行自然轻微活动','idle','待机动作',1,1,1,10,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('idle_breathing','呼吸待机','角色保持站立并进行缓慢呼吸','idle','待机动作',1,1,1,11,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('idle_blink','眨眼','角色自然眨眼','idle','待机动作',1,0,1,12,1,4,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('idle_look_around','四处观察','角色左右环顾四周','idle','待机动作',1,0,1,13,1,12,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('idle_sway','轻微摇摆','角色身体轻微左右摇摆','idle','待机动作',1,0,1,14,1,10,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('walk_left','向左行走','角色向左侧行走','movement','移动动作',0,1,1,20,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('walk_right','向右行走','角色向右侧行走','movement','移动动作',0,1,1,21,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('run_left','向左奔跑','角色向左侧快速奔跑','movement','移动动作',0,0,1,22,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('run_right','向右奔跑','角色向右侧快速奔跑','movement','移动动作',0,0,1,23,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('jump','跳跃','角色向上跳起','movement','移动动作',0,0,1,24,1,10,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('land','落地','角色从空中落地','movement','移动动作',0,0,1,25,1,6,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('turn_around','转身','角色转身面向另一侧','movement','移动动作',0,0,1,26,1,6,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('wave','挥手','角色挥手致意','interaction','基础互动',0,1,1,30,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('nod','点头','角色点头表示肯定','interaction','基础互动',0,0,1,31,1,4,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('shake_head','摇头','角色摇头表示否定','interaction','基础互动',0,0,1,32,1,4,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('clap','鼓掌','角色拍手鼓掌','interaction','基础互动',0,0,1,33,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('point','指向','角色用手指向某处','interaction','基础互动',0,0,1,34,1,6,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('stretch','伸懒腰','角色伸展身体','interaction','基础互动',0,0,1,35,1,10,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('bow','鞠躬','角色弯腰鞠躬','interaction','基础互动',0,0,1,36,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('happy','开心','角色表现出开心的样子','emotion','情绪动作',0,1,1,40,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('excited','兴奋','角色表现出兴奋的样子','emotion','情绪动作',0,0,1,41,1,10,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('shy','害羞','角色表现出害羞的样子','emotion','情绪动作',0,0,1,42,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('sad','难过','角色表现出难过的样子','emotion','情绪动作',0,1,1,43,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('cry','哭泣','角色流泪哭泣','emotion','情绪动作',0,0,1,44,1,10,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('angry','生气','角色表现出愤怒','emotion','情绪动作',0,0,1,45,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('surprised','惊讶','角色表现出惊讶','emotion','情绪动作',0,0,1,46,1,6,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('confused','疑惑','角色表现出疑惑','emotion','情绪动作',0,0,1,47,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('embarrassed','尴尬','角色表现出尴尬','emotion','情绪动作',0,0,1,48,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('scared','害怕','角色表现出害怕','emotion','情绪动作',0,0,1,49,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('proud','得意','角色表现出得意','emotion','情绪动作',0,0,1,50,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('tired','疲惫','角色表现出疲惫','emotion','情绪动作',0,0,1,51,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('sit','坐下','角色坐下','life','生活动作',0,0,1,50,1,6,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('sleep','睡觉','角色躺下睡觉','life','生活动作',0,1,1,51,1,12,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('wake_up','醒来','角色从睡眠中醒来','life','生活动作',0,0,1,52,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('eat','吃东西','角色进食','life','生活动作',0,0,1,53,1,10,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('drink','喝东西','角色喝水','life','生活动作',0,0,1,54,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('read','看书','角色阅读书籍','life','生活动作',0,0,1,55,1,10,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('write','写字','角色书写','life','生活动作',0,0,1,56,1,10,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('use_phone','使用手机','角色使用手机','life','生活动作',0,0,1,57,1,10,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('work','工作','角色伏案工作','life','生活动作',0,0,1,58,1,10,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('study','学习','角色学习','life','生活动作',0,0,1,59,1,10,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('clicked','被点击','角色被鼠标点击','desktop','桌面交互',0,1,1,60,1,4,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('double_clicked','被双击','角色被鼠标双击','desktop','桌面交互',0,0,1,61,1,4,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('hovered','鼠标悬停','角色被鼠标悬停','desktop','桌面交互',0,0,1,62,1,4,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('dragged','被拖动','角色被鼠标拖动','desktop','桌面交互',0,1,1,63,1,6,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('picked_up','被提起','角色被提起','desktop','桌面交互',0,0,1,64,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('dropped','被放下','角色被放下','desktop','桌面交互',0,0,1,65,1,6,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('fall','下落','角色向下掉落','desktop','桌面交互',0,0,1,66,1,10,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('edge_sit','坐在窗口边缘','角色坐在窗口边缘','desktop','桌面交互',0,0,1,67,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('edge_climb','攀爬窗口边缘','角色攀爬窗口边缘','desktop','桌面交互',0,0,1,68,1,10,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('sleep_on_desktop','趴在桌面睡觉','角色趴在桌面上睡觉','desktop','桌面交互',0,0,1,69,1,12,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('listening','倾听','角色倾听对方说话','dialogue','对话反馈',0,0,1,70,1,6,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('thinking','思考','角色思考','dialogue','对话反馈',0,1,1,71,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('speaking','说话','角色说话','dialogue','对话反馈',0,1,1,72,1,10,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('agreeing','赞同','角色表示赞同','dialogue','对话反馈',0,0,1,73,1,6,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('disagreeing','不赞同','角色表示不赞同','dialogue','对话反馈',0,0,1,74,1,6,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('waiting','等待','角色安静等待','dialogue','对话反馈',0,0,1,75,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('greeting','问候','角色问候致意','dialogue','对话反馈',0,0,1,76,1,8,1)`)
			s.Execute(`INSERT OR IGNORE INTO desktop_pet_action_definitions (action_key,name,description,category_key,category_name,supports_default_idle,recommended,enabled,sort_order,definition_version,default_frame_count,estimated_generation_count) VALUES ('goodbye','告别','角色告别','dialogue','对话反馈',0,0,1,77,1,8,1)`)
			return nil
		},
	}
}
