package migration

func DefaultMigrations() []Migration {
	return []Migration{
		BackupMigration(),
		{
			Version: "001",
			Name:    "add_psyche_states_table",
			Up: func(s *Step) error {
				s.CreateTable("CREATE TABLE IF NOT EXISTS psyche_states (character_id TEXT PRIMARY KEY, version TEXT DEFAULT '', state_version INTEGER DEFAULT 0, emotion TEXT DEFAULT '{}', mood TEXT DEFAULT '{}', stress REAL DEFAULT 0, energy REAL DEFAULT 0.7, created_at TEXT DEFAULT '', updated_at TEXT DEFAULT '')")
				return nil
			},
		},
		{
			Version: "002",
			Name:    "add_psyche_events_table",
			Up: func(s *Step) error {
				s.CreateTable("CREATE TABLE IF NOT EXISTS psyche_events (id TEXT PRIMARY KEY, character_id TEXT NOT NULL DEFAULT '', event_type TEXT NOT NULL DEFAULT '', event_data TEXT DEFAULT '{}', created_at TEXT DEFAULT '')")
				return nil
			},
		},
		{
			Version: "003",
			Name:    "add_psyche_snapshots_table",
			Up: func(s *Step) error {
				s.CreateTable("CREATE TABLE IF NOT EXISTS psyche_snapshots (id TEXT PRIMARY KEY, character_id TEXT NOT NULL DEFAULT '', snapshot_data TEXT DEFAULT '{}', created_at TEXT DEFAULT '')")
				return nil
			},
		},
		{
			Version: "004",
			Name:    "add_relationship_states_table",
			Up: func(s *Step) error {
				s.CreateTable("CREATE TABLE IF NOT EXISTS relationship_states (id TEXT PRIMARY KEY, character_id TEXT NOT NULL DEFAULT '', relation_type TEXT NOT NULL DEFAULT '', relation_data TEXT DEFAULT '{}', created_at TEXT DEFAULT '', updated_at TEXT DEFAULT '')")
				return nil
			},
		},
		{
			Version: "005",
			Name:    "add_relationship_events_table",
			Up: func(s *Step) error {
				s.CreateTable("CREATE TABLE IF NOT EXISTS relationship_events (id TEXT PRIMARY KEY, character_id TEXT NOT NULL DEFAULT '', event_type TEXT NOT NULL DEFAULT '', event_data TEXT DEFAULT '{}', created_at TEXT DEFAULT '')")
				return nil
			},
		},
		MemoryScopeTypeMigration(),
		MemorySensitivityMigration(),
		ChatScopeIndexesMigration(),
		MessageSequenceCheckpointMigration(),
		TombstoneRebuildMigration(),
		InteractionRecordsCreateMigration(),
		InteractionRecordsV2Migration(),
		ProactiveDeliveryTrackingMigration(),
		RuntimeQueueMigration(),
		LegacyDataMigration(),
		TriggerHistoryMigration(),
		RelationshipScopeMigration(),
		NeedStatesMigration(),
		ExtensionsMigration(),
		PluginRuntimeMigration(),
		ExtensionWorkshopMigration(),
		ExtensionWorkshopPermissionScopesMigration(),
		ExtensionWorkshopPlannerMigration(),
		ExtensionWorkshopGenerationSummaryMigration(),
		ExtensionAgentSkillsMigration(),
		ExtensionAgentSkillTraceMigration(),
		ExtensionPackagesMigration(),
		ExtensionScopeBindingsMigration(),
		ExtensionOwnedResourcesMigration(),
		ExtensionPackageRecoveryMigration(),
		ExtensionArtifactRecoveryMigration(),
		ExtensionScheduleSourceMigration(),
		ExtensionScheduleOwnershipRepairMigration(),
		EmotesMigration(),
		MessagePlanMigration(),
		TemporalCoreMigration(),
		TemporalRelationshipTimeMigration(),
		CanonicalSingleUserMigration(),
		CharacterBaseColumnMigration(),
		MCPClientMigration(),
		UserProfileCharacterScopeMigration(),
		EpisodicMessageTimeMigration(),
		PipelineCheckpointLocalTimeMigration(),
		ImageGenConfigMigration(),
		DesktopPetActionDefinitionsMigration(),
		ImageGenConfigEnabledMigration(),
		DesktopPetGenerationTasksMigration(),
		DesktopPetTaskExecutionFieldsMigration(),
		DesktopPetActionExecutionFieldsMigration(),
		DesktopPetGenerationFramesMigration(),
		DesktopPetGenerationCallLogsMigration(),
		DesktopPetProcessingTasksMigration(),
		DesktopPetProcessingActionsMigration(),
		DesktopPetProcessedFramesMigration(),
		DesktopPetPackagesMigration(),
		DesktopPetInstallationsMigration(),
		DesktopPetRuntimeSettingsMigration(),
		ConsolidationAutoMigrateMigration(),
		QdrantMigration(),
		SurrealMigration(),
		MCPDuplicateRegistrationsMigration(),
		ProviderApiTypeMigration(),
		TtsAsrBaseUrlMigration(),
		DesktopPetDataConsistencyMigration(),
		DesktopPetStateMachineMigration(),
		DesktopPetRuntimeClientsMigration(),
		DesktopPetRuntimeCommandsMigration(),
		DesktopPetRuntimeActualStatesMigration(),
		DesktopPetActionSpecContractMigration(),
		DesktopPetRuntimeSettingsV2Migration(),
		DesktopPetGenerationChainMigration(),
		DesktopPetCatalogPopulateMigration(),
		DesktopPetQualitySystemMigration(),
		DesktopPetProcessingRevisionsMigration(),
		DesktopPetEditingMigration(),
		DesktopPetPackageReleaseMigration(),
		DesktopPetBehaviorMigration(),
		DesktopPetPhase8GatesMigration(),
		DesktopPetGenerationActiveArtifactMigration(),
		DesktopPetProcessingCommitRecoveryMigration(),
		DesktopPetRevisionBridgeMigration(),
		DesktopPetActionRevisionBridgeV2Migration(),
		DesktopPetActionRevisionDataMigrateMigration(),
		DesktopPetReleaseDomainMigration(),
		DesktopPetQualityBridgeMigration(),
		DesktopPetInstallationCoordinatorMigration(),
		DesktopPetEditingV2Migration(),
		DesktopPetRuntimeProtocolV2Migration(),
		DesktopPetRuntimeV2TablesMigration(),
		DesktopPetGenerationPlanTablesMigration(),
		DesktopPetProcessingAtomicCommitMigration(),
		DesktopPetQualityV2Migration(),
		DesktopPetReleaseDomainV2Migration(),
		DesktopPetReleaseDomainV3Migration(),
		DesktopPetInstallationV2Migration(),
		DesktopPetBehaviorV2ColumnsMigration(),
		DesktopPetLocalSessionMigration(),
		RuntimeBootstrapTicketMigration(),
		RuntimeBootstrapTicketRuntimeIDForwardFix(),
		RotationJournalMigration(),
		DesktopPetRuntimeV2CommandForwardFixMigration(),
		DesktopPetImportStagingsMigration(),
		DesktopPetMigrationControlMigration(),
		DesktopPetDevicesMigration(),
		DesktopPetLocalSessionFixMigration(),
		DesktopPetImportSagaFieldsMigration(),
		WorkspaceMountsMigration(),
		ModelConfigProtocolMigration(),
	}
}
