package tts

func GetAvailableVoices() []VoicePreset {
	return []VoicePreset{
		{Name: "zh_female_vv_uranus_bigtts", Label: "Vivi 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "saturn_zh_female_cancan_tob", Label: "知性灿灿 (角色扮演)", Gender: "female", SupportsEmotion: false},
		{Name: "saturn_zh_female_keainvsheng_tob", Label: "可爱女生 (角色扮演)", Gender: "female", SupportsEmotion: false},
		{Name: "saturn_zh_female_tiaopigongzhu_tob", Label: "调皮公主 (角色扮演)", Gender: "female", SupportsEmotion: false},
		{Name: "saturn_zh_male_shuanglangshaonian_tob", Label: "爽朗少年 (角色扮演)", Gender: "male", SupportsEmotion: false},
		{Name: "saturn_zh_male_tiancaitongzhuo_tob", Label: "天才同桌 (角色扮演)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_female_xiaohe_uranus_bigtts", Label: "小何 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_male_m191_uranus_bigtts", Label: "云舟 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_male_taocheng_uranus_bigtts", Label: "小天 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "en_male_tim_uranus_bigtts", Label: "Tim (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "en_female_dacey_uranus_bigtts", Label: "Dacey (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "en_female_stokie_uranus_bigtts", Label: "Stokie (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_male_liufei_uranus_bigtts", Label: "刘飞 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_female_qingxinnvsheng_uranus_bigtts", Label: "清新女声 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_cancan_uranus_bigtts", Label: "知性灿灿 2.0 (角色扮演)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_sajiaoxuemei_uranus_bigtts", Label: "撒娇学妹 2.0 (角色扮演)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_tianmeixiaoyuan_uranus_bigtts", Label: "甜美小源 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_tianmeitaozi_uranus_bigtts", Label: "甜美桃子 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_shuangkuaisisi_uranus_bigtts", Label: "爽快思思 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_peiqi_uranus_bigtts", Label: "佩奇猪 2.0 (视频配音)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_linjianvhai_uranus_bigtts", Label: "邻家女孩 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_male_shaonianzixin_uranus_bigtts", Label: "少年梓辛/Brayan 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_male_sunwukong_uranus_bigtts", Label: "猴哥 2.0 (视频配音)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_female_yingyujiaoxue_uranus_bigtts", Label: "Tina老师 2.0 (教育)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_kefunvsheng_uranus_bigtts", Label: "暖阳女声 2.0 (客服)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_xiaoxue_uranus_bigtts", Label: "儿童绘本 2.0 (有声阅读)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_male_dayi_uranus_bigtts", Label: "大壹 2.0 (视频配音)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_female_mizai_uranus_bigtts", Label: "黑猫侦探社咪仔 2.0 (视频配音)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_jitangnv_uranus_bigtts", Label: "鸡汤女 2.0 (视频配音)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_meilinvyou_uranus_bigtts", Label: "魅力女友 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_liuchangnv_uranus_bigtts", Label: "流畅女声 2.0 (视频配音)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_male_ruyayichen_uranus_bigtts", Label: "儒雅逸辰 2.0 (视频配音)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_female_wenroumama_uranus_bigtts", Label: "温柔妈妈 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_male_jieshuoxiaoming_uranus_bigtts", Label: "解说小明 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_female_tvbnv_uranus_bigtts", Label: "TVB女声 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_male_yizhipiannan_uranus_bigtts", Label: "译制片男 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_female_qiaopinv_uranus_bigtts", Label: "俏皮女声 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_zhishuaiyingzi_uranus_bigtts", Label: "直率英子 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_male_linjiananhai_uranus_bigtts", Label: "邻家男孩 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_male_silang_uranus_bigtts", Label: "四郎 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_male_ruyaqingnian_uranus_bigtts", Label: "儒雅青年 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_male_qingcang_uranus_bigtts", Label: "擎苍 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_male_xionger_uranus_bigtts", Label: "熊二 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_female_yingtaowanzi_uranus_bigtts", Label: "樱桃丸子 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_male_wennuanahu_uranus_bigtts", Label: "温暖阿虎/Alvin 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_male_naiqimengwa_uranus_bigtts", Label: "奶气萌娃 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_female_popo_uranus_bigtts", Label: "婆婆 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_gaolengyujie_uranus_bigtts", Label: "高冷御姐 2.0 (角色扮演)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_male_aojiaobazong_uranus_bigtts", Label: "傲娇霸总 2.0 (角色扮演)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_male_lanyinmianbao_uranus_bigtts", Label: "懒音绵宝 2.0 (有声阅读)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_male_fanjuanqingnian_uranus_bigtts", Label: "反卷青年 2.0 (角色扮演)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_female_wenroushunv_uranus_bigtts", Label: "温柔淑女 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_gufengshaoyu_uranus_bigtts", Label: "古风少御 2.0 (角色扮演)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_male_huolixiaoge_uranus_bigtts", Label: "活力小哥 2.0 (角色扮演)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_male_baqiqingshu_uranus_bigtts", Label: "霸气青叔 2.0 (角色扮演)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_male_xuanyijieshuo_uranus_bigtts", Label: "悬疑解说 2.0 (有声阅读)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_female_mengyatou_uranus_bigtts", Label: "萌丫头/Cutey 2.0 (角色扮演)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_tiexinnvsheng_uranus_bigtts", Label: "贴心女声/Candy 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_jitangmei_uranus_bigtts", Label: "鸡汤妹妹/Hope 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_male_cixingjieshuonan_uranus_bigtts", Label: "磁性解说男声/Morgan 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_male_liangsangmengzai_uranus_bigtts", Label: "亮嗓萌仔 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_female_kailangjiejie_uranus_bigtts", Label: "开朗姐姐 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_male_gaolengchenwen_uranus_bigtts", Label: "高冷沉稳 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_male_shenyeboke_uranus_bigtts", Label: "深夜播客 2.0 (多情感)", Gender: "male", SupportsEmotion: true},
		{Name: "zh_male_lubanqihao_uranus_bigtts", Label: "鲁班七号 2.0 (角色扮演)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_female_jiaochuannv_uranus_bigtts", Label: "娇喘女声 2.0 (视频配音)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_linxiao_uranus_bigtts", Label: "林潇 2.0 (角色扮演)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_lingling_uranus_bigtts", Label: "玲玲姐姐 2.0 (角色扮演)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_chunribu_uranus_bigtts", Label: "春日部姐姐 2.0 (角色扮演)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_male_tangseng_uranus_bigtts", Label: "唐僧 2.0 (角色扮演)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_male_zhuangzhou_uranus_bigtts", Label: "庄周 2.0 (角色扮演)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_male_kailangdidi_uranus_bigtts", Label: "开朗弟弟 2.0 (角色扮演)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_male_zhubajie_uranus_bigtts", Label: "猪八戒 2.0 (角色扮演)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_female_ganmaodianyin_uranus_bigtts", Label: "感冒电音姐姐 2.0 (角色扮演)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_chanmeinv_uranus_bigtts", Label: "谄媚女声 2.0 (角色扮演)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_nvleishen_uranus_bigtts", Label: "女雷神 2.0 (角色扮演)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_qinqienv_uranus_bigtts", Label: "亲切女声 2.0 (有声阅读)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_male_kuailexiaodong_uranus_bigtts", Label: "快乐小东 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_male_kailangxuezhang_uranus_bigtts", Label: "开朗学长 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_male_youyoujunzi_uranus_bigtts", Label: "悠悠君子 2.0 (有声阅读)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_female_wenjingmaomao_uranus_bigtts", Label: "文静毛毛 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_zhixingnv_uranus_bigtts", Label: "知性女声 2.0 (有声阅读)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_male_qingshuangnanda_uranus_bigtts", Label: "清爽男大 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_male_yuanboxiaoshu_uranus_bigtts", Label: "渊博小叔 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_male_yangguangqingnian_uranus_bigtts", Label: "阳光青年 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_female_qingchezizi_uranus_bigtts", Label: "清澈梓梓 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_tianmeiyueyue_uranus_bigtts", Label: "甜美悦悦 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_xinlingjitang_uranus_bigtts", Label: "心灵鸡汤 2.0 (有声阅读)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_male_wenrouxiaoge_uranus_bigtts", Label: "温柔小哥 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_female_roumeinvyou_uranus_bigtts", Label: "柔美女友 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_male_dongfanghaoran_uranus_bigtts", Label: "东方浩然 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_female_wenrouxiaoya_uranus_bigtts", Label: "温柔小雅 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_male_tiancaitongsheng_uranus_bigtts", Label: "天才童声 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_female_wuzetian_uranus_bigtts", Label: "武则天 2.0 (角色扮演)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_gujie_uranus_bigtts", Label: "顾姐 2.0 (角色扮演)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_male_guanggaojieshuo_uranus_bigtts", Label: "广告解说 2.0 (通用)", Gender: "male", SupportsEmotion: false},
		{Name: "zh_female_shaoergushi_uranus_bigtts", Label: "少儿故事 2.0 (有声阅读)", Gender: "female", SupportsEmotion: false},
		{Name: "zh_female_sophie_uranus_bigtts", Label: "魅力苏菲 2.0 (通用)", Gender: "female", SupportsEmotion: false},
		{Name: "saturn_zh_male_qingxinmumu_cs_tob", Label: "清新沐沐 2.0 (客服)", Gender: "male", SupportsEmotion: false},
	}
}

func GetEmotions() []string {
	return []string{"", "happy", "sad", "angry", "fearful", "surprised", "neutral"}
}
