package event

import (
	"context"
	"fmt"
)

func (s *Service) ensureSchema(ctx context.Context) error {
	if s == nil || s.db == nil {
		return fmt.Errorf("event: db required")
	}
	statements := []string{
		`CREATE TABLE IF NOT EXISTS extension_event_types (
			event_type_id TEXT NOT NULL,
			version INTEGER NOT NULL,
			description TEXT,
			payload_schema_json TEXT,
			metadata_schema_json TEXT,
			producer_policy_json TEXT NOT NULL,
			subscriber_policy_json TEXT NOT NULL,
			delivery_policy_json TEXT NOT NULL,
			ordering_policy TEXT NOT NULL,
			retention_policy_json TEXT NOT NULL,
			sensitive_fields_json TEXT,
			projection_rules_json TEXT,
			max_payload_bytes INTEGER NOT NULL,
			max_metadata_bytes INTEGER NOT NULL,
			risk_level TEXT NOT NULL DEFAULT 'low',
			definition_hash TEXT NOT NULL,
			created_at DATETIME NOT NULL,
			updated_at DATETIME NOT NULL,
			PRIMARY KEY (event_type_id, version)
		)`,
		`CREATE TABLE IF NOT EXISTS extension_event_outbox (
			outbox_id TEXT PRIMARY KEY,
			event_id TEXT NOT NULL UNIQUE,
			event_type_id TEXT NOT NULL,
			event_version INTEGER NOT NULL,
			producer_id TEXT NOT NULL,
			producer_type TEXT NOT NULL,
			producer_generation INTEGER NOT NULL DEFAULT 0,
			event_domain TEXT NOT NULL DEFAULT '',
			causation_id TEXT NOT NULL DEFAULT '',
			aggregate_type TEXT,
			aggregate_id TEXT,
			aggregate_version INTEGER,
			partition_key TEXT,
			ordering_key TEXT,
			idempotency_key TEXT NOT NULL UNIQUE,
			scope_snapshot_id TEXT,
			permission_snapshot_id TEXT,
			trace_id TEXT,
			operation_id TEXT,
			parent_event_id TEXT,
			depth INTEGER NOT NULL DEFAULT 0,
			occurred_at DATETIME NOT NULL,
			published_at DATETIME,
			payload_json TEXT NOT NULL,
			metadata_json TEXT,
			payload_hash TEXT NOT NULL,
			definition_hash TEXT,
			status TEXT NOT NULL DEFAULT 'pending',
			available_at DATETIME NOT NULL,
			created_at DATETIME NOT NULL,
			updated_at DATETIME NOT NULL,
			error_code TEXT,
			error_message TEXT,
			lease_owner TEXT,
			lease_expires_at DATETIME,
			dispatched_at DATETIME
		)`,
		`CREATE TABLE IF NOT EXISTS extension_event_subscriptions (
			contribution_id TEXT PRIMARY KEY,
			extension_id TEXT NOT NULL,
			module_id TEXT NOT NULL,
			event_type_id TEXT NOT NULL,
			event_version_range TEXT,
			entry TEXT NOT NULL,
			filter_json TEXT,
			projection_json TEXT,
			delivery_policy_json TEXT,
			retry_policy_json TEXT,
			ordering_requirement TEXT NOT NULL DEFAULT 'none',
			timeout_ms INTEGER NOT NULL DEFAULT 5000,
			max_in_flight INTEGER NOT NULL DEFAULT 4,
			permission_requirements_json TEXT,
			scope_rule_json TEXT,
			dependency_requirements_json TEXT,
			runtime_binding_json TEXT,
			definition_hash TEXT NOT NULL,
			generation INTEGER NOT NULL DEFAULT 1,
			enabled INTEGER NOT NULL DEFAULT 1,
			created_at DATETIME NOT NULL,
			updated_at DATETIME NOT NULL,
			UNIQUE(extension_id, contribution_id)
		)`,
		`CREATE TABLE IF NOT EXISTS extension_event_deliveries (
			delivery_id TEXT PRIMARY KEY,
			event_id TEXT NOT NULL,
			subscription_id TEXT NOT NULL,
			extension_id TEXT NOT NULL,
			module_id TEXT NOT NULL,
			status TEXT NOT NULL DEFAULT 'pending',
			partition_key TEXT,
			ordering_key TEXT,
			sequence INTEGER NOT NULL DEFAULT 0,
			attempt INTEGER NOT NULL DEFAULT 0,
			max_attempts INTEGER NOT NULL DEFAULT 5,
			available_at DATETIME NOT NULL,
			lease_owner TEXT,
			lease_expires_at DATETIME,
			runtime_instance_id TEXT,
			scope_snapshot_id TEXT,
			permission_snapshot_id TEXT,
			projected_payload_hash TEXT,
			subscription_generation INTEGER NOT NULL DEFAULT 0,
			target_generation INTEGER NOT NULL DEFAULT 0,
			producer_generation INTEGER NOT NULL DEFAULT 0,
			started_at DATETIME,
			finished_at DATETIME,
			error_code TEXT,
			error_message TEXT,
			created_at DATETIME NOT NULL,
			updated_at DATETIME NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS extension_event_dead_letters (
			dead_letter_id TEXT PRIMARY KEY,
			event_id TEXT NOT NULL,
			delivery_id TEXT NOT NULL,
			subscription_id TEXT NOT NULL,
			extension_id TEXT NOT NULL,
			module_id TEXT NOT NULL,
			event_type_id TEXT NOT NULL,
			event_version INTEGER NOT NULL,
			reason TEXT NOT NULL,
			error_code TEXT,
			error_message TEXT,
			attempts INTEGER NOT NULL DEFAULT 0,
			partition_key TEXT,
			ordering_key TEXT,
			payload_hash TEXT,
			projected_payload_hash TEXT,
			definition_hash TEXT,
			scope_snapshot_id TEXT,
			permission_snapshot_id TEXT,
			runtime_instance_id TEXT,
			trace_id TEXT,
			operation_id TEXT,
			origin_event_json TEXT,
			subscription_snapshot_json TEXT,
			created_at DATETIME NOT NULL,
			replay_count INTEGER NOT NULL DEFAULT 0,
			last_replay_at DATETIME,
			status TEXT NOT NULL DEFAULT 'pending',
			updated_at DATETIME NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS extension_event_audit (
			audit_id INTEGER PRIMARY KEY AUTOINCREMENT,
			operation_id TEXT,
			invocation_id TEXT,
			event_id TEXT,
			delivery_id TEXT,
			action TEXT NOT NULL,
			actor TEXT,
			extension_id TEXT,
			timestamp DATETIME NOT NULL,
			payload_hash TEXT,
			error_code TEXT,
			success INTEGER NOT NULL DEFAULT 0,
			detail_json TEXT
		)`,
		`CREATE TABLE IF NOT EXISTS extension_event_invocations (
			invocation_id TEXT PRIMARY KEY,
			operation_id TEXT,
			event_id TEXT NOT NULL,
			delivery_id TEXT,
			subscription_id TEXT,
			attempt INTEGER NOT NULL DEFAULT 0,
			runtime_instance_id TEXT,
			scope_snapshot_id TEXT,
			permission_snapshot_id TEXT,
			trace_id TEXT,
			filter_result TEXT,
			projection_result TEXT,
			ordering_result TEXT,
			permission_result TEXT,
			scope_result TEXT,
			status TEXT NOT NULL,
			started_at DATETIME NOT NULL,
			finished_at DATETIME,
			error_code TEXT,
			error_message TEXT
		)`,
		`CREATE TABLE IF NOT EXISTS extension_event_side_effects (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			invocation_id TEXT NOT NULL,
			kind TEXT NOT NULL,
			target TEXT NOT NULL,
			hash TEXT,
			occurred_at DATETIME NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS extension_conversation_event_sequences (
			conversation_id TEXT PRIMARY KEY,
			last_sequence INTEGER NOT NULL DEFAULT 0,
			updated_at DATETIME NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS extension_event_host_provenance (
			outbox_id TEXT PRIMARY KEY,
			provenance_json TEXT NOT NULL,
			FOREIGN KEY(outbox_id) REFERENCES extension_event_outbox(outbox_id) ON DELETE CASCADE
		)`,
	}
	for _, statement := range statements {
		if _, err := s.db.ExecContext(ctx, statement); err != nil {
			return err
		}
	}
	return nil
}
