package hook

import (
	"context"
	"encoding/json"
	"time"
)

func RegisterDefaultHookPoints(ctx context.Context, registry HookPointRegistry) error {
	points := DefaultHookPoints()
	for _, p := range points {
		if err := registry.RegisterPoint(ctx, p); err != nil {
			return err
		}
	}
	return nil
}

func DefaultHookPoints() []HookPointDefinition {
	messageSchema := json.RawMessage(`{"type":"object","properties":{"messageId":{"type":"string"},"characterId":{"type":"string"},"conversationId":{"type":"string"},"text":{"type":"string"},"sender":{"type":"string"},"direction":{"type":"string"},"attachments":{"type":"array"},"metadata":{"type":"object"}}}`)
	messageResultSchema := json.RawMessage(`{"type":"object","properties":{"decision":{"type":"string","enum":["continue","reject","replace"]},"patch":{"type":"array"}}}`)
	modelRequestSchema := json.RawMessage(`{"type":"object","properties":{"request":{"type":"object","properties":{"temperature":{"type":"number"},"maxTokens":{"type":"integer"},"stop":{"type":"array"},"messages":{"type":"array"},"metadata":{"type":"object"}}}}}`)
	modelResponseSchema := json.RawMessage(`{"type":"object","properties":{"response":{"type":"object","properties":{"content":{"type":"string"},"finishReason":{"type":"string"},"usage":{"type":"object"},"annotations":{"type":"object"}}}}}`)
	toolSchema := json.RawMessage(`{"type":"object","properties":{"toolId":{"type":"string"},"args":{"type":"object"},"invocationId":{"type":"string"},"idempotencyKey":{"type":"string"}}}`)
	toolResultSchema := json.RawMessage(`{"type":"object","properties":{"decision":{"type":"string","enum":["continue","deny","replace"]},"patch":{"type":"array"}}}`)

	return []HookPointDefinition{
		{
			HookPointID:     "message.before_send/1",
			ContractVersion: 1,
			Description:     "Executed before a message is sent. Allows text normalization, metadata enrichment, and rejection.",
			SupportedPhases: []HookPhase{PhaseBefore, PhaseFilter, PhaseTransform, PhaseObserve},
			InputSchema:     messageSchema,
			ResultSchema:    messageResultSchema,
			AllowedMutations: []MutationRule{
				{Path: "/text", Operations: []string{MutationReplace, MutationAdd, MutationRemove}, ConflictMode: ConflictLastWriterWins},
				{Path: "/attachments", Operations: []string{MutationAdd, MutationRemove}, ConflictMode: ConflictLastWriterWins},
				{Path: "/metadata/extensions/*", Operations: []string{MutationAdd, MutationReplace, MutationRemove}, ConflictMode: ConflictLastWriterWins},
			},
			FailurePolicy:     DefaultFailurePolicy(),
			ExecutionPolicy:   DefaultExecutionPolicy(),
			MaxHandlers:       16,
			DefaultTimeout:    500 * time.Millisecond,
			MaxTimeout:        2 * time.Second,
			MaxPayloadBytes:   256 * 1024,
			MaxResultBytes:    128 * 1024,
			RiskLevel:         RiskMedium,
			SensitiveFields:   []string{"/messageId", "/characterId", "/conversationId", "/sender", "/direction", "/createdAt", "/permission", "/scope", "/channelAccount", "/deliveryId", "/idempotencyKey"},
			RequiredContext:   []string{"conversationId", "characterId"},
			ThirdPartyAllowed: true,
		},
		{
			HookPointID:     "message.before_persist/1",
			ContractVersion: 1,
			Description:     "Executed before a message is persisted to the database.",
			SupportedPhases: []HookPhase{PhaseBefore, PhaseObserve},
			InputSchema:     messageSchema,
			ResultSchema:    messageResultSchema,
			AllowedMutations: []MutationRule{
				{Path: "/metadata/extensions/*", Operations: []string{MutationAdd, MutationReplace}, ConflictMode: ConflictLastWriterWins},
			},
			FailurePolicy:     DefaultFailurePolicy(),
			ExecutionPolicy:   DefaultExecutionPolicy(),
			MaxHandlers:       8,
			DefaultTimeout:    300 * time.Millisecond,
			MaxTimeout:        1 * time.Second,
			MaxPayloadBytes:   256 * 1024,
			MaxResultBytes:    64 * 1024,
			RiskLevel:         RiskLow,
			SensitiveFields:   []string{"/messageId", "/characterId", "/conversationId", "/sender", "/direction", "/createdAt"},
			RequiredContext:   []string{"conversationId"},
			ThirdPartyAllowed: true,
		},
		{
			HookPointID:       "message.after_persist/1",
			ContractVersion:   1,
			Description:       "Executed after a message has been persisted. Default observe-only.",
			SupportedPhases:   []HookPhase{PhaseAfter, PhaseObserve},
			InputSchema:       messageSchema,
			ResultSchema:      json.RawMessage(`{"type":"object","properties":{"decision":{"type":"string","enum":["continue"]}}}`),
			AllowedMutations:  nil,
			FailurePolicy:     DefaultFailurePolicy(),
			ExecutionPolicy:   DefaultExecutionPolicy(),
			MaxHandlers:       8,
			DefaultTimeout:    300 * time.Millisecond,
			MaxTimeout:        1 * time.Second,
			MaxPayloadBytes:   256 * 1024,
			MaxResultBytes:    64 * 1024,
			RiskLevel:         RiskLow,
			SensitiveFields:   []string{"/messageId", "/characterId", "/conversationId"},
			RequiredContext:   []string{"messageId"},
			ThirdPartyAllowed: true,
		},
		{
			HookPointID:     "model.before_request/1",
			ContractVersion: 1,
			Description:     "Executed before a model API request is sent. Allows parameter adjustment.",
			SupportedPhases: []HookPhase{PhaseBefore, PhaseFilter, PhaseTransform, PhaseObserve},
			InputSchema:     modelRequestSchema,
			ResultSchema:    json.RawMessage(`{"type":"object","properties":{"decision":{"type":"string","enum":["continue","reject","replace"]},"patch":{"type":"array"}}}`),
			AllowedMutations: []MutationRule{
				{Path: "/request/temperature", Operations: []string{MutationReplace}, ConflictMode: ConflictLastWriterWins},
				{Path: "/request/maxTokens", Operations: []string{MutationReplace}, ConflictMode: ConflictLastWriterWins},
				{Path: "/request/stop", Operations: []string{MutationAdd, MutationRemove, MutationReplace}, ConflictMode: ConflictLastWriterWins},
				{Path: "/request/metadata/extensions/*", Operations: []string{MutationAdd, MutationReplace, MutationRemove}, ConflictMode: ConflictLastWriterWins},
			},
			FailurePolicy:     DefaultFailurePolicy(),
			ExecutionPolicy:   DefaultExecutionPolicy(),
			MaxHandlers:       16,
			DefaultTimeout:    1000 * time.Millisecond,
			MaxTimeout:        5 * time.Second,
			MaxPayloadBytes:   512 * 1024,
			MaxResultBytes:    128 * 1024,
			RiskLevel:         RiskHigh,
			SensitiveFields:   []string{"/systemPrompt", "/securityPrompt", "/modelCredentials", "/providerSecret", "/rawConversationHistory", "/request/model", "/request/apiKey"},
			RequiredContext:   []string{"conversationId", "characterId"},
			ThirdPartyAllowed: true,
		},
		{
			HookPointID:     "model.after_response/1",
			ContractVersion: 1,
			Description:     "Executed after a model response is received. Default observe-only.",
			SupportedPhases: []HookPhase{PhaseAfter, PhaseObserve},
			InputSchema:     modelResponseSchema,
			ResultSchema:    json.RawMessage(`{"type":"object","properties":{"decision":{"type":"string","enum":["continue","replace"]},"patch":{"type":"array"}}}`),
			AllowedMutations: []MutationRule{
				{Path: "/response/annotations/extensions/*", Operations: []string{MutationAdd, MutationReplace}, ConflictMode: ConflictLastWriterWins},
				{Path: "/response/displayMetadata/extensions/*", Operations: []string{MutationAdd, MutationReplace}, ConflictMode: ConflictLastWriterWins},
			},
			FailurePolicy:     DefaultFailurePolicy(),
			ExecutionPolicy:   DefaultExecutionPolicy(),
			MaxHandlers:       16,
			DefaultTimeout:    1000 * time.Millisecond,
			MaxTimeout:        5 * time.Second,
			MaxPayloadBytes:   512 * 1024,
			MaxResultBytes:    128 * 1024,
			RiskLevel:         RiskMedium,
			SensitiveFields:   []string{"/response/content", "/response/rawContent", "/providerSecret", "/modelCredentials"},
			RequiredContext:   []string{"conversationId"},
			ThirdPartyAllowed: true,
		},
		{
			HookPointID:     "prompt.before_assemble/1",
			ContractVersion: 1,
			Description:     "Executed before prompt assembly. Allows extension context contribution only.",
			SupportedPhases: []HookPhase{PhaseBefore, PhaseObserve},
			InputSchema:     json.RawMessage(`{"type":"object","properties":{"sections":{"type":"object"},"context":{"type":"object"}}}`),
			ResultSchema:    json.RawMessage(`{"type":"object","properties":{"decision":{"type":"string","enum":["continue","replace"]},"patch":{"type":"array"}}}`),
			AllowedMutations: []MutationRule{
				{Path: "/sections/extension_context/*", Operations: []string{MutationAdd, MutationReplace}, ConflictMode: ConflictLastWriterWins},
			},
			FailurePolicy:     DefaultFailurePolicy(),
			ExecutionPolicy:   DefaultExecutionPolicy(),
			MaxHandlers:       8,
			DefaultTimeout:    500 * time.Millisecond,
			MaxTimeout:        2 * time.Second,
			MaxPayloadBytes:   512 * 1024,
			MaxResultBytes:    128 * 1024,
			RiskLevel:         RiskHigh,
			SensitiveFields:   []string{"/sections/system_security", "/sections/system_core", "/sections/character", "/sections/agent_skill", "/sections/user"},
			RequiredContext:   []string{"characterId"},
			ThirdPartyAllowed: true,
		},
		{
			HookPointID:       "prompt.after_assemble/1",
			ContractVersion:   1,
			Description:       "Executed after prompt assembly. Observe-only.",
			SupportedPhases:   []HookPhase{PhaseAfter, PhaseObserve},
			InputSchema:       json.RawMessage(`{"type":"object","properties":{"messages":{"type":"array"},"trace":{"type":"object"}}}`),
			ResultSchema:      json.RawMessage(`{"type":"object","properties":{"decision":{"type":"string","enum":["continue"]}}}`),
			AllowedMutations:  nil,
			FailurePolicy:     DefaultFailurePolicy(),
			ExecutionPolicy:   DefaultExecutionPolicy(),
			MaxHandlers:       8,
			DefaultTimeout:    300 * time.Millisecond,
			MaxTimeout:        1 * time.Second,
			MaxPayloadBytes:   512 * 1024,
			MaxResultBytes:    64 * 1024,
			RiskLevel:         RiskMedium,
			SensitiveFields:   []string{"/messages/system_security", "/messages/system_core"},
			RequiredContext:   []string{"characterId"},
			ThirdPartyAllowed: true,
		},
		{
			HookPointID:     "tool.before_execute/1",
			ContractVersion: 1,
			Description:     "Executed before a tool is invoked. Allows deny and metadata enrichment.",
			SupportedPhases: []HookPhase{PhaseBefore, PhaseFilter, PhaseObserve},
			InputSchema:     toolSchema,
			ResultSchema:    toolResultSchema,
			AllowedMutations: []MutationRule{
				{Path: "/args/extensions/*", Operations: []string{MutationAdd, MutationReplace}, ConflictMode: ConflictLastWriterWins},
			},
			FailurePolicy:     DefaultFailurePolicy(),
			ExecutionPolicy:   DefaultExecutionPolicy(),
			MaxHandlers:       16,
			DefaultTimeout:    500 * time.Millisecond,
			MaxTimeout:        2 * time.Second,
			MaxPayloadBytes:   256 * 1024,
			MaxResultBytes:    64 * 1024,
			RiskLevel:         RiskHigh,
			SensitiveFields:   []string{"/toolId", "/runtime", "/permission", "/scope", "/idempotencyKey", "/approvalMode"},
			RequiredContext:   []string{"invocationId"},
			ThirdPartyAllowed: true,
		},
		{
			HookPointID:     "tool.after_execute/1",
			ContractVersion: 1,
			Description:     "Executed after a tool has been invoked. Default observe-only.",
			SupportedPhases: []HookPhase{PhaseAfter, PhaseObserve},
			InputSchema:     json.RawMessage(`{"type":"object","properties":{"toolId":{"type":"string"},"result":{"type":"object"},"sideEffects":{"type":"array"}}}`),
			ResultSchema:    json.RawMessage(`{"type":"object","properties":{"decision":{"type":"string","enum":["continue","replace"]},"patch":{"type":"array"}}}`),
			AllowedMutations: []MutationRule{
				{Path: "/result/displayMetadata/extensions/*", Operations: []string{MutationAdd, MutationReplace}, ConflictMode: ConflictLastWriterWins},
			},
			FailurePolicy:     DefaultFailurePolicy(),
			ExecutionPolicy:   DefaultExecutionPolicy(),
			MaxHandlers:       16,
			DefaultTimeout:    500 * time.Millisecond,
			MaxTimeout:        2 * time.Second,
			MaxPayloadBytes:   256 * 1024,
			MaxResultBytes:    64 * 1024,
			RiskLevel:         RiskMedium,
			SensitiveFields:   []string{"/result/sideEffects", "/result/rawOutput", "/toolId"},
			RequiredContext:   []string{"invocationId"},
			ThirdPartyAllowed: true,
		},
		{
			HookPointID:     "workflow.before_start/1",
			ContractVersion: 1,
			Description:     "Executed before a workflow starts.",
			SupportedPhases: []HookPhase{PhaseBefore, PhaseFilter, PhaseObserve},
			InputSchema:     json.RawMessage(`{"type":"object","properties":{"workflowId":{"type":"string"},"input":{"type":"object"},"mode":{"type":"string"}}}`),
			ResultSchema:    json.RawMessage(`{"type":"object","properties":{"decision":{"type":"string","enum":["continue","deny","replace"]},"patch":{"type":"array"}}}`),
			AllowedMutations: []MutationRule{
				{Path: "/input/extensions/*", Operations: []string{MutationAdd, MutationReplace}, ConflictMode: ConflictLastWriterWins},
			},
			FailurePolicy:     DefaultFailurePolicy(),
			ExecutionPolicy:   DefaultExecutionPolicy(),
			MaxHandlers:       8,
			DefaultTimeout:    500 * time.Millisecond,
			MaxTimeout:        2 * time.Second,
			MaxPayloadBytes:   256 * 1024,
			MaxResultBytes:    64 * 1024,
			RiskLevel:         RiskMedium,
			SensitiveFields:   []string{"/workflowId", "/secrets", "/credentials"},
			RequiredContext:   []string{},
			ThirdPartyAllowed: true,
		},
		{
			HookPointID:       "workflow.after_finish/1",
			ContractVersion:   1,
			Description:       "Executed after a workflow finishes. Observe-only.",
			SupportedPhases:   []HookPhase{PhaseAfter, PhaseObserve},
			InputSchema:       json.RawMessage(`{"type":"object","properties":{"workflowId":{"type":"string"},"result":{"type":"object"},"status":{"type":"string"}}}`),
			ResultSchema:      json.RawMessage(`{"type":"object","properties":{"decision":{"type":"string","enum":["continue"]}}}`),
			AllowedMutations:  nil,
			FailurePolicy:     DefaultFailurePolicy(),
			ExecutionPolicy:   DefaultExecutionPolicy(),
			MaxHandlers:       8,
			DefaultTimeout:    300 * time.Millisecond,
			MaxTimeout:        1 * time.Second,
			MaxPayloadBytes:   256 * 1024,
			MaxResultBytes:    64 * 1024,
			RiskLevel:         RiskLow,
			SensitiveFields:   []string{"/secrets", "/credentials"},
			RequiredContext:   []string{},
			ThirdPartyAllowed: true,
		},
		{
			HookPointID:       "extension.before_enable/1",
			ContractVersion:   1,
			Description:       "Executed before an extension is enabled.",
			SupportedPhases:   []HookPhase{PhaseBefore, PhaseObserve},
			InputSchema:       json.RawMessage(`{"type":"object","properties":{"extensionId":{"type":"string"},"version":{"type":"string"}}}`),
			ResultSchema:      json.RawMessage(`{"type":"object","properties":{"decision":{"type":"string","enum":["continue","reject"]}}}`),
			AllowedMutations:  nil,
			FailurePolicy:     DefaultFailurePolicy(),
			ExecutionPolicy:   DefaultExecutionPolicy(),
			MaxHandlers:       4,
			DefaultTimeout:    300 * time.Millisecond,
			MaxTimeout:        1 * time.Second,
			MaxPayloadBytes:   64 * 1024,
			MaxResultBytes:    32 * 1024,
			RiskLevel:         RiskLow,
			SensitiveFields:   []string{"/extensionId", "/version"},
			RequiredContext:   []string{},
			ThirdPartyAllowed: true,
		},
		{
			HookPointID:       "extension.after_disable/1",
			ContractVersion:   1,
			Description:       "Executed after an extension is disabled.",
			SupportedPhases:   []HookPhase{PhaseAfter, PhaseObserve},
			InputSchema:       json.RawMessage(`{"type":"object","properties":{"extensionId":{"type":"string"},"version":{"type":"string"}}}`),
			ResultSchema:      json.RawMessage(`{"type":"object","properties":{"decision":{"type":"string","enum":["continue"]}}}`),
			AllowedMutations:  nil,
			FailurePolicy:     DefaultFailurePolicy(),
			ExecutionPolicy:   DefaultExecutionPolicy(),
			MaxHandlers:       4,
			DefaultTimeout:    300 * time.Millisecond,
			MaxTimeout:        1 * time.Second,
			MaxPayloadBytes:   64 * 1024,
			MaxResultBytes:    32 * 1024,
			RiskLevel:         RiskLow,
			SensitiveFields:   []string{"/extensionId"},
			RequiredContext:   []string{},
			ThirdPartyAllowed: true,
		},
	}
}

func SystemOnlyHookPoints() []HookPointDefinition {
	return []HookPointDefinition{
		{
			HookPointID:       "permission.before_decision/1",
			ContractVersion:   1,
			Description:       "System-only: executed before a permission decision.",
			SupportedPhases:   []HookPhase{PhaseBefore, PhaseFilter},
			InputSchema:       json.RawMessage(`{"type":"object"}`),
			ResultSchema:      json.RawMessage(`{"type":"object"}`),
			AllowedMutations:  nil,
			FailurePolicy:     StrictFailurePolicy(),
			ExecutionPolicy:   DefaultExecutionPolicy(),
			MaxHandlers:       4,
			DefaultTimeout:    200 * time.Millisecond,
			MaxTimeout:        500 * time.Millisecond,
			MaxPayloadBytes:   64 * 1024,
			MaxResultBytes:    32 * 1024,
			RiskLevel:         RiskCritical,
			SensitiveFields:   []string{"/secret", "/token", "/authorization"},
			RequiredContext:   []string{},
			ThirdPartyAllowed: false,
		},
		{
			HookPointID:       "scope.before_decision/1",
			ContractVersion:   1,
			Description:       "System-only: executed before a scope decision.",
			SupportedPhases:   []HookPhase{PhaseBefore, PhaseFilter},
			InputSchema:       json.RawMessage(`{"type":"object"}`),
			ResultSchema:      json.RawMessage(`{"type":"object"}`),
			AllowedMutations:  nil,
			FailurePolicy:     StrictFailurePolicy(),
			ExecutionPolicy:   DefaultExecutionPolicy(),
			MaxHandlers:       4,
			DefaultTimeout:    200 * time.Millisecond,
			MaxTimeout:        500 * time.Millisecond,
			MaxPayloadBytes:   64 * 1024,
			MaxResultBytes:    32 * 1024,
			RiskLevel:         RiskCritical,
			SensitiveFields:   []string{"/scopeId", "/scopeType"},
			RequiredContext:   []string{},
			ThirdPartyAllowed: false,
		},
		{
			HookPointID:       "security.before_validate/1",
			ContractVersion:   1,
			Description:       "System-only: executed before security validation.",
			SupportedPhases:   []HookPhase{PhaseBefore, PhaseFilter},
			InputSchema:       json.RawMessage(`{"type":"object"}`),
			ResultSchema:      json.RawMessage(`{"type":"object"}`),
			AllowedMutations:  nil,
			FailurePolicy:     StrictFailurePolicy(),
			ExecutionPolicy:   DefaultExecutionPolicy(),
			MaxHandlers:       4,
			DefaultTimeout:    200 * time.Millisecond,
			MaxTimeout:        500 * time.Millisecond,
			MaxPayloadBytes:   64 * 1024,
			MaxResultBytes:    32 * 1024,
			RiskLevel:         RiskCritical,
			SensitiveFields:   []string{"/input", "/rawInput"},
			RequiredContext:   []string{},
			ThirdPartyAllowed: false,
		},
	}
}
