// SPDX-FileCopyrightText: 2026 彭旭
// SPDX-License-Identifier: AGPL-3.0-only
package specs

import "github.com/u-ai/backend/internal/desktoppet/contracts"

func idleSpecs() []contracts.ActionSpec {
	return []contracts.ActionSpec{
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "idle_normal",
				Name:                "普通待机",
				Description:         "角色保持站立并进行自然轻微呼吸活动",
				CategoryKey:         "idle",
				CategoryName:        "待机动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         true,
				SupportsDefaultIdle: true,
				CategorySortOrder:   10,
				ActionSortOrder:     10,
				Tags:                []string{"idle", "ambient", "stationary"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 8,
				FramePhases: makePhases([]string{
					"起始自然站立姿态，双臂自然下垂",
					"胸腔轻微扩张，开始吸气",
					"呼吸达到最高点，肩膀轻微上抬",
					"保持呼吸最高点片刻",
					"开始缓慢呼气，肩膀回落",
					"呼吸回到中位，身体轻微放松",
					"身体轻微自然摆动",
					"回到起始站立姿态",
				}),
				MotionDescription:      "角色保持站立并进行自然轻微呼吸活动",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，双臂自然下垂，身体保持垂直",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色保持站立姿态，进行自然轻微呼吸",
				NegativePromptFragment: "多余人物、变形、肢体扭曲、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       8,
				ReturnPolicy:     contracts.ReturnNone,
				Interruptible:    true,
				InterruptAfterMS: 500,
				MinimumPlayMS:    1000,
				MaximumPlayMS:    0,
				Priority:         10,
				CooldownMS:       0,
				MutexGroup:       "base_idle",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "idle_breathing",
				Name:                "深呼吸待机",
				Description:         "角色保持站立并进行缓慢呼吸，胸腹有明显起伏",
				CategoryKey:         "idle",
				CategoryName:        "待机动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         true,
				SupportsDefaultIdle: true,
				CategorySortOrder:   10,
				ActionSortOrder:     11,
				Tags:                []string{"idle", "ambient", "breathing", "stationary"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 8,
				FramePhases: makePhases([]string{
					"起始站立姿态，双臂自然下垂",
					"缓慢吸气，胸腔轻微扩张",
					"继续吸气，腹部轻微隆起",
					"吸气达到最高点",
					"保持最高点片刻",
					"开始缓慢呼气",
					"继续呼气回到中位",
					"回到起始站立姿态",
				}),
				MotionDescription:      "角色保持站立并进行缓慢呼吸，胸腹有明显起伏",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，双臂自然下垂，胸腹随呼吸起伏",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色保持站立姿态，进行缓慢深呼吸",
				NegativePromptFragment: "多余人物、变形、肢体扭曲、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       8,
				ReturnPolicy:     contracts.ReturnNone,
				Interruptible:    true,
				InterruptAfterMS: 500,
				MinimumPlayMS:    1000,
				MaximumPlayMS:    0,
				Priority:         10,
				CooldownMS:       0,
				MutexGroup:       "base_idle",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "idle_blink",
				Name:                "眨眼",
				Description:         "角色自然眨眼，眼睛开合一个完整周期",
				CategoryKey:         "idle",
				CategoryName:        "待机动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   10,
				ActionSortOrder:     12,
				Tags:                []string{"idle_variant", "micro_expression", "blink"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 4,
				FramePhases: makePhases([]string{
					"眼睛完全睁开，自然站立",
					"上眼睑开始下落",
					"眼睛完全闭合",
					"眼睛重新睁开回到起始状态",
				}),
				MotionDescription:      "角色自然眨眼，眼睛开合一个完整周期",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，仅眼部动作，身体保持静止",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色保持站立，自然眨眼一次",
				NegativePromptFragment: "多余人物、变形、眼球异常、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       12,
				ReturnPolicy:     contracts.ReturnPrevious,
				Interruptible:    false,
				InterruptAfterMS: 0,
				MinimumPlayMS:    333,
				MaximumPlayMS:    1000,
				Priority:         18,
				CooldownMS:       8000,
				MutexGroup:       "micro_expression",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    1000,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "idle_look_around",
				Name:                "环顾四周",
				Description:         "角色左右环顾四周，头部转动观察环境",
				CategoryKey:         "idle",
				CategoryName:        "待机动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   10,
				ActionSortOrder:     13,
				Tags:                []string{"idle_variant", "look_around", "stationary"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 12,
				FramePhases: makePhases([]string{
					"起始站立，正视前方",
					"头部开始向左转",
					"继续向左转",
					"头部转到左侧极限",
					"在左侧停留观察",
					"开始向右回转",
					"经过正面回到中位",
					"继续向右转",
					"头部转到右侧极限",
					"在右侧停留观察",
					"开始向左回转",
					"回到正视前方的起始姿态",
				}),
				MotionDescription:      "角色左右环顾四周，头部转动观察环境",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，身体保持垂直，仅头部转动",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色保持站立，头部左右转动环顾四周",
				NegativePromptFragment: "多余人物、变形、头部扭转过度、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       8,
				ReturnPolicy:     contracts.ReturnPrevious,
				Interruptible:    true,
				InterruptAfterMS: 750,
				MinimumPlayMS:    1500,
				MaximumPlayMS:    3000,
				Priority:         16,
				CooldownMS:       15000,
				MutexGroup:       "idle_variant",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    2000,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "idle_sway",
				Name:                "摇摆待机",
				Description:         "角色身体轻微左右摇摆，重心周期性偏移",
				CategoryKey:         "idle",
				CategoryName:        "待机动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: true,
				CategorySortOrder:   10,
				ActionSortOrder:     14,
				Tags:                []string{"idle", "ambient", "sway", "stationary"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 10,
				FramePhases: makePhases([]string{
					"起始站立，身体居中",
					"身体重心开始向左偏移",
					"继续向左倾斜",
					"到达左侧最大幅度",
					"开始向右回正",
					"经过中心向右偏移",
					"继续向右倾斜",
					"到达右侧最大幅度",
					"开始向左回正",
					"回到居中起始姿态",
				}),
				MotionDescription:      "角色身体轻微左右摇摆，重心周期性偏移",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，双脚不动，上半身左右摇摆",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色保持站立，身体轻微左右摇摆",
				NegativePromptFragment: "多余人物、变形、摇摆幅度过大、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       8,
				ReturnPolicy:     contracts.ReturnNone,
				Interruptible:    true,
				InterruptAfterMS: 625,
				MinimumPlayMS:    1250,
				MaximumPlayMS:    0,
				Priority:         11,
				CooldownMS:       0,
				MutexGroup:       "base_idle",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
	}
}
