// SPDX-FileCopyrightText: 2026 彭旭
// SPDX-License-Identifier: AGPL-3.0-only
package specs

import "github.com/u-ai/backend/internal/desktoppet/contracts"

func interactionSpecs() []contracts.ActionSpec {
	return []contracts.ActionSpec{
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "wave",
				Name:                "挥手",
				Description:         "角色抬起右臂挥手致意，手掌左右摆动",
				CategoryKey:         "interaction",
				CategoryName:        "基础互动",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         true,
				SupportsDefaultIdle: false,
				CategorySortOrder:   30,
				ActionSortOrder:     30,
				Tags:                []string{"interaction", "gesture", "wave"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 8,
				FramePhases: makePhases([]string{
					"起始站立，右臂自然下垂",
					"右臂抬起至肩部高度",
					"前臂展开，手掌朝前",
					"手掌向左挥动",
					"手掌向右挥动",
					"手掌再次向左挥动",
					"手掌回到中间位置",
					"手臂放下回到起始姿态",
				}),
				MotionDescription:      "角色抬起右臂挥手致意，手掌左右摆动",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，右臂抬起至肩部以上，手掌朝前左右摆动，左臂自然下垂",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色抬起右手挥手致意，手掌左右摆动",
				NegativePromptFragment: "多余人物、变形、手臂扭曲、多余手指、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       10,
				ReturnPolicy:     contracts.ReturnPrevious,
				Interruptible:    true,
				InterruptAfterMS: 400,
				MinimumPlayMS:    800,
				MaximumPlayMS:    3000,
				Priority:         55,
				CooldownMS:       2500,
				MutexGroup:       "gesture",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    1000,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "nod",
				Name:                "点头",
				Description:         "角色头部上下点动一次表示肯定",
				CategoryKey:         "interaction",
				CategoryName:        "基础互动",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   30,
				ActionSortOrder:     31,
				Tags:                []string{"interaction", "gesture", "nod"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 4,
				FramePhases: makePhases([]string{
					"起始正视前方",
					"头部开始向下点",
					"头部点到最低点",
					"头部抬起回到正视前方",
				}),
				MotionDescription:      "角色头部上下点动一次表示肯定",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，仅头部上下运动，身体保持静止",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色点头一次表示肯定，头部上下运动",
				NegativePromptFragment: "多余人物、变形、头部扭转、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       12,
				ReturnPolicy:     contracts.ReturnPrevious,
				Interruptible:    true,
				InterruptAfterMS: 400,
				MinimumPlayMS:    333,
				MaximumPlayMS:    1500,
				Priority:         54,
				CooldownMS:       1500,
				MutexGroup:       "gesture",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    500,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "shake_head",
				Name:                "摇头",
				Description:         "角色头部左右摇动一次表示否定",
				CategoryKey:         "interaction",
				CategoryName:        "基础互动",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   30,
				ActionSortOrder:     32,
				Tags:                []string{"interaction", "gesture", "shake_head"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 4,
				FramePhases: makePhases([]string{
					"起始正视前方",
					"头部转向左侧",
					"头部转向右侧",
					"头部回到正视前方",
				}),
				MotionDescription:      "角色头部左右摇动一次表示否定",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，仅头部左右运动，身体保持静止",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色摇头一次表示否定，头部左右运动",
				NegativePromptFragment: "多余人物、变形、头部扭转过度、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       12,
				ReturnPolicy:     contracts.ReturnPrevious,
				Interruptible:    true,
				InterruptAfterMS: 400,
				MinimumPlayMS:    333,
				MaximumPlayMS:    1500,
				Priority:         54,
				CooldownMS:       1500,
				MutexGroup:       "gesture",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    500,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "clap",
				Name:                "鼓掌",
				Description:         "角色双手在胸前合拢拍击鼓掌，连续两次",
				CategoryKey:         "interaction",
				CategoryName:        "基础互动",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   30,
				ActionSortOrder:     33,
				Tags:                []string{"interaction", "gesture", "clap"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 8,
				FramePhases: makePhases([]string{
					"起始站立，双手在胸前分开",
					"双手开始合拢",
					"双手掌心相击",
					"双手分开",
					"双手再次合拢",
					"双手掌心相击",
					"双手分开",
					"双手放下回到起始姿态",
				}),
				MotionDescription:      "角色双手在胸前合拢拍击鼓掌，连续两次",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，双手举至胸前，掌心相对反复合拢分开",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色双手在胸前拍手鼓掌，掌心反复相击",
				NegativePromptFragment: "多余人物、变形、手臂扭曲、多余手指、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       12,
				ReturnPolicy:     contracts.ReturnPrevious,
				Interruptible:    true,
				InterruptAfterMS: 400,
				MinimumPlayMS:    666,
				MaximumPlayMS:    2500,
				Priority:         56,
				CooldownMS:       2000,
				MutexGroup:       "gesture",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    1000,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "point",
				Name:                "指向",
				Description:         "角色抬起右臂用食指指向某处并收回",
				CategoryKey:         "interaction",
				CategoryName:        "基础互动",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   30,
				ActionSortOrder:     34,
				Tags:                []string{"interaction", "gesture", "point"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 6,
				FramePhases: makePhases([]string{
					"起始站立，右臂下垂",
					"右臂抬起，前臂弯曲",
					"食指伸出，开始指向",
					"手臂完全伸展指向目标",
					"保持指向姿态",
					"手臂收回回到起始姿态",
				}),
				MotionDescription:      "角色抬起右臂用食指指向某处并收回",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，右臂抬起伸展，食指指向前方，其余手指收拢",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色抬起右手用食指指向前方目标",
				NegativePromptFragment: "多余人物、变形、手臂扭曲、多余手指、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       10,
				ReturnPolicy:     contracts.ReturnPrevious,
				Interruptible:    true,
				InterruptAfterMS: 400,
				MinimumPlayMS:    600,
				MaximumPlayMS:    2000,
				Priority:         54,
				CooldownMS:       1800,
				MutexGroup:       "gesture",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    800,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "stretch",
				Name:                "伸展",
				Description:         "角色双臂上举伸展身体，含后仰和恢复",
				CategoryKey:         "interaction",
				CategoryName:        "基础互动",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   30,
				ActionSortOrder:     35,
				Tags:                []string{"interaction", "gesture", "stretch"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 10,
				FramePhases: makePhases([]string{
					"起始站立",
					"双臂开始上举",
					"双臂继续上举",
					"双臂举到最高点，身体伸展",
					"保持伸展状态",
					"上半身轻微后仰",
					"保持后仰伸展",
					"身体开始回正",
					"双臂开始下落",
					"回到起始站立姿态",
				}),
				MotionDescription:      "角色双臂上举伸展身体，含后仰和恢复",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，双臂上举至头顶上方，身体后仰伸展",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色双臂上举伸懒腰，身体向后伸展",
				NegativePromptFragment: "多余人物、变形、手臂扭曲、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       8,
				ReturnPolicy:     contracts.ReturnPrevious,
				Interruptible:    true,
				InterruptAfterMS: 400,
				MinimumPlayMS:    1250,
				MaximumPlayMS:    3500,
				Priority:         35,
				CooldownMS:       12000,
				MutexGroup:       "gesture",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    5000,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "bow",
				Name:                "鞠躬",
				Description:         "角色上半身前倾弯腰鞠躬后起身恢复",
				CategoryKey:         "interaction",
				CategoryName:        "基础互动",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   30,
				ActionSortOrder:     36,
				Tags:                []string{"interaction", "gesture", "bow"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 8,
				FramePhases: makePhases([]string{
					"起始站立",
					"上半身开始前倾",
					"继续前倾弯腰",
					"弯腰到最低点",
					"保持鞠躬姿态",
					"开始起身",
					"继续起身",
					"回到站立起始姿态",
				}),
				MotionDescription:      "角色上半身前倾弯腰鞠躬后起身恢复",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，以腰部为轴上半身前倾，双臂自然下垂或贴于身侧",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色弯腰鞠躬，上半身前倾后起身",
				NegativePromptFragment: "多余人物、变形、弯腰过度、肢体扭曲、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       10,
				ReturnPolicy:     contracts.ReturnPrevious,
				Interruptible:    false,
				InterruptAfterMS: 400,
				MinimumPlayMS:    800,
				MaximumPlayMS:    2500,
				Priority:         55,
				CooldownMS:       4000,
				MutexGroup:       "gesture",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    2000,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
	}
}
