// SPDX-FileCopyrightText: 2026 彭旭
// SPDX-License-Identifier: AGPL-3.0-only
package specs

import "github.com/u-ai/backend/internal/desktoppet/contracts"

func movementSpecs() []contracts.ActionSpec {
	return []contracts.ActionSpec{
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "walk_left",
				Name:                "向左行走",
				Description:         "角色向左侧行走，双腿交替迈步移动",
				CategoryKey:         "movement",
				CategoryName:        "移动动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         true,
				SupportsDefaultIdle: false,
				CategorySortOrder:   20,
				ActionSortOrder:     20,
				Tags:                []string{"movement", "locomotion", "walk", "left"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 8,
				FramePhases: makePhases([]string{
					"起始站立，准备向左迈步",
					"右腿抬起向左迈出",
					"右脚落地，重心左移",
					"左腿跟随抬起",
					"左脚向左迈出落地",
					"右腿再次抬起",
					"右脚落地继续行进",
					"回到站立姿态，完成一个步幅",
				}),
				MotionDescription:      "角色向左侧行走，双腿交替迈步移动",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面朝向镜头，双腿交替迈步，身体随步伐轻微起伏",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色向左侧迈步行走，步态自然",
				NegativePromptFragment: "多余人物、变形、滑步、肢体扭曲、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       12,
				ReturnPolicy:     contracts.ReturnCurrentActivity,
				Interruptible:    true,
				InterruptAfterMS: 667,
				MinimumPlayMS:    667,
				MaximumPlayMS:    0,
				Priority:         45,
				CooldownMS:       0,
				MutexGroup:       "locomotion",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "walk_right",
				Name:                "向右行走",
				Description:         "角色向右侧行走，双腿交替迈步移动",
				CategoryKey:         "movement",
				CategoryName:        "移动动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         true,
				SupportsDefaultIdle: false,
				CategorySortOrder:   20,
				ActionSortOrder:     21,
				Tags:                []string{"movement", "locomotion", "walk", "right"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 8,
				FramePhases: makePhases([]string{
					"起始站立，准备向右迈步",
					"左腿抬起向右迈出",
					"左脚落地，重心右移",
					"右腿跟随抬起",
					"右脚向右迈出落地",
					"左腿再次抬起",
					"左脚落地继续行进",
					"回到站立姿态，完成一个步幅",
				}),
				MotionDescription:      "角色向右侧行走，双腿交替迈步移动",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面朝向镜头，双腿交替迈步，身体随步伐轻微起伏",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色向右侧迈步行走，步态自然",
				NegativePromptFragment: "多余人物、变形、滑步、肢体扭曲、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       12,
				ReturnPolicy:     contracts.ReturnCurrentActivity,
				Interruptible:    true,
				InterruptAfterMS: 667,
				MinimumPlayMS:    667,
				MaximumPlayMS:    0,
				Priority:         45,
				CooldownMS:       0,
				MutexGroup:       "locomotion",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "run_left",
				Name:                "向左奔跑",
				Description:         "角色向左侧快速奔跑，步伐大且有腾空阶段",
				CategoryKey:         "movement",
				CategoryName:        "移动动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   20,
				ActionSortOrder:     22,
				Tags:                []string{"movement", "locomotion", "run", "left"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 8,
				FramePhases: makePhases([]string{
					"起始奔跑预备，身体前倾",
					"右腿大力蹬地向左",
					"身体腾空，右腿前摆",
					"左脚落地缓冲",
					"左腿蹬地发力",
					"身体再次腾空，左腿前摆",
					"右脚落地缓冲",
					"回到奔跑预备姿态",
				}),
				MotionDescription:      "角色向左侧快速奔跑，步伐大且有腾空阶段",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面朝向镜头，身体前倾，双臂随奔跑摆动，双腿大幅交替",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色向左侧快速奔跑，动作敏捷有力",
				NegativePromptFragment: "多余人物、变形、滑步、肢体扭曲、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       14,
				ReturnPolicy:     contracts.ReturnCurrentActivity,
				Interruptible:    true,
				InterruptAfterMS: 572,
				MinimumPlayMS:    572,
				MaximumPlayMS:    0,
				Priority:         47,
				CooldownMS:       0,
				MutexGroup:       "locomotion",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "run_right",
				Name:                "向右奔跑",
				Description:         "角色向右侧快速奔跑，步伐大且有腾空阶段",
				CategoryKey:         "movement",
				CategoryName:        "移动动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   20,
				ActionSortOrder:     23,
				Tags:                []string{"movement", "locomotion", "run", "right"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 8,
				FramePhases: makePhases([]string{
					"起始奔跑预备，身体前倾",
					"左腿大力蹬地向右",
					"身体腾空，左腿前摆",
					"右脚落地缓冲",
					"右腿蹬地发力",
					"身体再次腾空，右腿前摆",
					"左脚落地缓冲",
					"回到奔跑预备姿态",
				}),
				MotionDescription:      "角色向右侧快速奔跑，步伐大且有腾空阶段",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面朝向镜头，身体前倾，双臂随奔跑摆动，双腿大幅交替",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色向右侧快速奔跑，动作敏捷有力",
				NegativePromptFragment: "多余人物、变形、滑步、肢体扭曲、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       14,
				ReturnPolicy:     contracts.ReturnCurrentActivity,
				Interruptible:    true,
				InterruptAfterMS: 572,
				MinimumPlayMS:    572,
				MaximumPlayMS:    0,
				Priority:         47,
				CooldownMS:       0,
				MutexGroup:       "locomotion",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "jump",
				Name:                "跳跃",
				Description:         "角色向上跳起，包含蓄力、腾空和落地缓冲完整过程",
				CategoryKey:         "movement",
				CategoryName:        "移动动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   20,
				ActionSortOrder:     24,
				Tags:                []string{"movement", "physics", "airborne", "jump"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 10,
				FramePhases: makePhases([]string{
					"起始站立，准备起跳",
					"双腿弯曲下蹲蓄力",
					"继续下蹲到最低点",
					"双腿蹬地发力开始上升",
					"身体腾空上升中",
					"到达跳跃最高点",
					"开始下落",
					"继续下落接近地面",
					"双脚触地开始缓冲",
					"回到站立姿态",
				}),
				MotionDescription:      "角色向上跳起，包含蓄力、腾空和落地缓冲完整过程",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面朝向镜头，下蹲蓄力后双腿蹬地，双臂上摆辅助起跳",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色原地向上跳跃，先下蹲蓄力再蹬地腾空",
				NegativePromptFragment: "多余人物、变形、悬浮、肢体扭曲、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       12,
				ReturnPolicy:     contracts.ReturnSpecific,
				ReturnActionKey:  "land",
				Interruptible:    false,
				InterruptAfterMS: 0,
				MinimumPlayMS:    833,
				MaximumPlayMS:    1800,
				Priority:         80,
				CooldownMS:       500,
				MutexGroup:       "physics_motion",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "land",
				Name:                "落地",
				Description:         "角色从空中落地，含触地缓冲和起身恢复",
				CategoryKey:         "movement",
				CategoryName:        "移动动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   20,
				ActionSortOrder:     25,
				Tags:                []string{"movement", "physics", "landing"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 6,
				FramePhases: makePhases([]string{
					"身体在空中下落",
					"双脚触地瞬间",
					"双腿弯曲缓冲冲击",
					"继续下蹲到最低点",
					"开始起身",
					"回到稳定站立姿态",
				}),
				MotionDescription:      "角色从空中落地，含触地缓冲和起身恢复",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面朝向镜头，双脚触地后双腿弯曲缓冲，双臂维持平衡",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色从空中下落并稳定落地，双腿弯曲缓冲",
				NegativePromptFragment: "多余人物、变形、穿模、肢体扭曲、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       12,
				ReturnPolicy:     contracts.ReturnCurrentActivity,
				Interruptible:    false,
				InterruptAfterMS: 0,
				MinimumPlayMS:    500,
				MaximumPlayMS:    1200,
				Priority:         82,
				CooldownMS:       100,
				MutexGroup:       "physics_motion",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "turn_around",
				Name:                "转身",
				Description:         "角色转身面向另一侧，身体旋转一百八十度",
				CategoryKey:         "movement",
				CategoryName:        "移动动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   20,
				ActionSortOrder:     26,
				Tags:                []string{"movement", "orientation", "turn"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 6,
				FramePhases: makePhases([]string{
					"起始正面对着镜头",
					"开始转身，肩膀转动",
					"转过四分之一",
					"转到侧面九十度",
					"继续转动接近完成",
					"完成转身面向另一侧",
				}),
				MotionDescription:      "角色转身面向另一侧，身体旋转一百八十度",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "以身体中轴为轴心旋转，双脚原地不动，上半身带动转动",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色原地转身，面向另一侧",
				NegativePromptFragment: "多余人物、变形、位移过大、肢体扭曲、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       10,
				ReturnPolicy:     contracts.ReturnPrevious,
				Interruptible:    true,
				InterruptAfterMS: 400,
				MinimumPlayMS:    600,
				MaximumPlayMS:    1400,
				Priority:         44,
				CooldownMS:       300,
				MutexGroup:       "orientation",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
	}
}
