// SPDX-FileCopyrightText: 2026 彭旭
// SPDX-License-Identifier: AGPL-3.0-only
package specs

import "github.com/u-ai/backend/internal/desktoppet/contracts"

func dialogueSpecs() []contracts.ActionSpec {
	return []contracts.ActionSpec{
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "listening",
				Name:                "倾听",
				Description:         defaultSpecs["listening"].MotionDescription,
				CategoryKey:         "dialogue",
				CategoryName:        "对话反馈",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   70,
				ActionSortOrder:     70,
				Tags:                []string{"dialogue", "state", "listening", "long_running"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: defaultSpecs["listening"].FrameCount,
				FramePhases: makePhases([]string{
					"起始站立",
					"身体微微前倾",
					"头部轻微歪向一侧",
					"眼神专注注视对方",
					"偶尔点头表示在听",
					"保持倾听姿态",
				}),
				MotionDescription:      defaultSpecs["listening"].MotionDescription,
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         defaultSpecs["listening"].PoseConstraint,
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         defaultSpecs["listening"].PromptFragment,
				NegativePromptFragment: defaultSpecs["listening"].NegativePromptFragment,
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       8,
				ReturnPolicy:     contracts.ReturnNone,
				ReturnActionKey:  "",
				Interruptible:    true,
				InterruptAfterMS: 750,
				MinimumPlayMS:    750,
				MaximumPlayMS:    0,
				Priority:         58,
				CooldownMS:       0,
				MutexGroup:       "dialogue_state",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "thinking",
				Name:                "思考",
				Description:         defaultSpecs["thinking"].MotionDescription,
				CategoryKey:         "dialogue",
				CategoryName:        "对话反馈",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         true,
				SupportsDefaultIdle: false,
				CategorySortOrder:   70,
				ActionSortOrder:     71,
				Tags:                []string{"dialogue", "state", "thinking", "long_running"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: defaultSpecs["thinking"].FrameCount,
				FramePhases: makePhases([]string{
					"起始站立",
					"眉头开始微皱",
					"抬手托住下巴",
					"眼神向上看向侧方",
					"保持思考姿态",
					"偶尔点头",
					"继续思考",
					"保持思考姿态",
				}),
				MotionDescription:      defaultSpecs["thinking"].MotionDescription,
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         defaultSpecs["thinking"].PoseConstraint,
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         defaultSpecs["thinking"].PromptFragment,
				NegativePromptFragment: defaultSpecs["thinking"].NegativePromptFragment,
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       8,
				ReturnPolicy:     contracts.ReturnNone,
				ReturnActionKey:  "",
				Interruptible:    true,
				InterruptAfterMS: 1000,
				MinimumPlayMS:    1000,
				MaximumPlayMS:    0,
				Priority:         60,
				CooldownMS:       0,
				MutexGroup:       "dialogue_state",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "speaking",
				Name:                "说话",
				Description:         defaultSpecs["speaking"].MotionDescription,
				CategoryKey:         "dialogue",
				CategoryName:        "对话反馈",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         true,
				SupportsDefaultIdle: false,
				CategorySortOrder:   70,
				ActionSortOrder:     72,
				Tags:                []string{"dialogue", "state", "speaking", "long_running"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: defaultSpecs["speaking"].FrameCount,
				FramePhases: makePhases([]string{
					"起始站立，闭嘴",
					"嘴巴开始张开",
					"嘴型变化发出第一个音节",
					"嘴巴张到最大",
					"嘴型变化发出另一个音节",
					"嘴巴半开",
					"嘴型再次变化",
					"嘴巴接近闭合",
					"嘴型变化收尾",
					"嘴巴闭合回到起始",
				}),
				MotionDescription:      defaultSpecs["speaking"].MotionDescription,
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         defaultSpecs["speaking"].PoseConstraint,
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         defaultSpecs["speaking"].PromptFragment,
				NegativePromptFragment: defaultSpecs["speaking"].NegativePromptFragment,
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       12,
				ReturnPolicy:     contracts.ReturnNone,
				ReturnActionKey:  "",
				Interruptible:    true,
				InterruptAfterMS: 833,
				MinimumPlayMS:    833,
				MaximumPlayMS:    0,
				Priority:         65,
				CooldownMS:       0,
				MutexGroup:       "dialogue_state",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "agreeing",
				Name:                "赞同",
				Description:         defaultSpecs["agreeing"].MotionDescription,
				CategoryKey:         "dialogue",
				CategoryName:        "对话反馈",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   70,
				ActionSortOrder:     73,
				Tags:                []string{"dialogue", "gesture", "agreeing"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: defaultSpecs["agreeing"].FrameCount,
				FramePhases: makePhases([]string{
					"起始站立",
					"开始点头",
					"头部点到最低",
					"头部抬起",
					"再次点头",
					"带着赞同表情",
				}),
				MotionDescription:      defaultSpecs["agreeing"].MotionDescription,
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         defaultSpecs["agreeing"].PoseConstraint,
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         defaultSpecs["agreeing"].PromptFragment,
				NegativePromptFragment: defaultSpecs["agreeing"].NegativePromptFragment,
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       10,
				ReturnPolicy:     contracts.ReturnCurrentActivity,
				ReturnActionKey:  "",
				Interruptible:    true,
				InterruptAfterMS: 400,
				MinimumPlayMS:    600,
				MaximumPlayMS:    2200,
				Priority:         62,
				CooldownMS:       1200,
				MutexGroup:       "dialogue_gesture",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    600,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "disagreeing",
				Name:                "不赞同",
				Description:         defaultSpecs["disagreeing"].MotionDescription,
				CategoryKey:         "dialogue",
				CategoryName:        "对话反馈",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   70,
				ActionSortOrder:     74,
				Tags:                []string{"dialogue", "gesture", "disagreeing"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: defaultSpecs["disagreeing"].FrameCount,
				FramePhases: makePhases([]string{
					"起始站立",
					"开始摇头",
					"头部转到一侧",
					"头部转到另一侧",
					"再次摇头",
					"带着不赞同表情",
				}),
				MotionDescription:      defaultSpecs["disagreeing"].MotionDescription,
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         defaultSpecs["disagreeing"].PoseConstraint,
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         defaultSpecs["disagreeing"].PromptFragment,
				NegativePromptFragment: defaultSpecs["disagreeing"].NegativePromptFragment,
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       10,
				ReturnPolicy:     contracts.ReturnCurrentActivity,
				ReturnActionKey:  "",
				Interruptible:    true,
				InterruptAfterMS: 400,
				MinimumPlayMS:    600,
				MaximumPlayMS:    2200,
				Priority:         62,
				CooldownMS:       1200,
				MutexGroup:       "dialogue_gesture",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    600,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "waiting",
				Name:                "等待",
				Description:         defaultSpecs["waiting"].MotionDescription,
				CategoryKey:         "dialogue",
				CategoryName:        "对话反馈",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   70,
				ActionSortOrder:     75,
				Tags:                []string{"dialogue", "state", "waiting", "long_running"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: defaultSpecs["waiting"].FrameCount,
				FramePhases: makePhases([]string{
					"起始站立",
					"双手交叠身前",
					"身体轻微重心偏移",
					"眼神看向侧方",
					"轻微叹气",
					"换个姿势",
					"继续等待",
					"保持等待姿态",
				}),
				MotionDescription:      defaultSpecs["waiting"].MotionDescription,
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         defaultSpecs["waiting"].PoseConstraint,
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         defaultSpecs["waiting"].PromptFragment,
				NegativePromptFragment: defaultSpecs["waiting"].NegativePromptFragment,
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       6,
				ReturnPolicy:     contracts.ReturnNone,
				ReturnActionKey:  "",
				Interruptible:    true,
				InterruptAfterMS: 1333,
				MinimumPlayMS:    1333,
				MaximumPlayMS:    0,
				Priority:         42,
				CooldownMS:       0,
				MutexGroup:       "dialogue_state",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "greeting",
				Name:                "问候",
				Description:         defaultSpecs["greeting"].MotionDescription,
				CategoryKey:         "dialogue",
				CategoryName:        "对话反馈",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   70,
				ActionSortOrder:     76,
				Tags:                []string{"dialogue", "gesture", "greeting"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: defaultSpecs["greeting"].FrameCount,
				FramePhases: makePhases([]string{
					"起始站立",
					"看到对方露出笑容",
					"右手抬起准备挥手",
					"手掌向前挥手致意",
					"继续挥手",
					"身体轻微前倾",
					"手臂收回",
					"保持友好姿态",
				}),
				MotionDescription:      defaultSpecs["greeting"].MotionDescription,
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         defaultSpecs["greeting"].PoseConstraint,
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         defaultSpecs["greeting"].PromptFragment,
				NegativePromptFragment: defaultSpecs["greeting"].NegativePromptFragment,
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       10,
				ReturnPolicy:     contracts.ReturnCurrentActivity,
				ReturnActionKey:  "",
				Interruptible:    true,
				InterruptAfterMS: 400,
				MinimumPlayMS:    800,
				MaximumPlayMS:    2200,
				Priority:         64,
				CooldownMS:       3000,
				MutexGroup:       "dialogue_gesture",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    1500,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "goodbye",
				Name:                "告别",
				Description:         defaultSpecs["goodbye"].MotionDescription,
				CategoryKey:         "dialogue",
				CategoryName:        "对话反馈",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   70,
				ActionSortOrder:     77,
				Tags:                []string{"dialogue", "gesture", "goodbye"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: defaultSpecs["goodbye"].FrameCount,
				FramePhases: makePhases([]string{
					"起始站立",
					"抬起右手",
					"手掌向前开始挥手",
					"继续挥手告别",
					"手掌左右摆动",
					"继续挥手",
					"手臂开始下落",
					"回到站立姿态",
				}),
				MotionDescription:      defaultSpecs["goodbye"].MotionDescription,
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         defaultSpecs["goodbye"].PoseConstraint,
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         defaultSpecs["goodbye"].PromptFragment,
				NegativePromptFragment: defaultSpecs["goodbye"].NegativePromptFragment,
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       10,
				ReturnPolicy:     contracts.ReturnCurrentActivity,
				ReturnActionKey:  "",
				Interruptible:    true,
				InterruptAfterMS: 400,
				MinimumPlayMS:    800,
				MaximumPlayMS:    2200,
				Priority:         64,
				CooldownMS:       3000,
				MutexGroup:       "dialogue_gesture",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    1500,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
	}
}
