// SPDX-FileCopyrightText: 2026 彭旭
// SPDX-License-Identifier: AGPL-3.0-only
package specs

import "github.com/u-ai/backend/internal/desktoppet/contracts"

func emotionSpecs() []contracts.ActionSpec {
	return []contracts.ActionSpec{
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "happy",
				Name:                "开心",
				Description:         "角色露出开心笑容，身体轻微上跃，双手握拳上举",
				CategoryKey:         "emotion",
				CategoryName:        "情绪动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         true,
				SupportsDefaultIdle: false,
				CategorySortOrder:   40,
				ActionSortOrder:     40,
				Tags:                []string{"emotion", "happy"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 8,
				FramePhases: makePhases([]string{
					"起始自然表情",
					"嘴角开始上扬",
					"笑容展开，眼睛微眯",
					"笑容达到最大，眼睛弯成月牙",
					"保持开心笑容",
					"身体轻微上跃表达喜悦",
					"双手轻微握拳上举",
					"回到带笑的起始姿态",
				}),
				MotionDescription:      "角色露出开心笑容，身体轻微上跃，双手握拳上举",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，嘴角上扬露出笑容，眼睛弯成月牙，身体轻微上跃",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色表现出开心的样子，笑容灿烂，身体欢快",
				NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏、牙齿异常",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       10,
				ReturnPolicy:     contracts.ReturnCurrentActivity,
				Interruptible:    true,
				InterruptAfterMS: 500,
				MinimumPlayMS:    800,
				MaximumPlayMS:    3500,
				Priority:         50,
				CooldownMS:       4000,
				MutexGroup:       "emotion_expression",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    2000,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "excited",
				Name:                "兴奋",
				Description:         "角色高举双手欢呼跳跃，表达强烈兴奋情绪",
				CategoryKey:         "emotion",
				CategoryName:        "情绪动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   40,
				ActionSortOrder:     41,
				Tags:                []string{"emotion", "excited"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 10,
				FramePhases: makePhases([]string{
					"起始站立",
					"双臂开始上举，表情兴奋",
					"双手举高，张大嘴巴欢呼",
					"双手挥动",
					"身体轻微跳跃",
					"继续挥动双手",
					"再次跳跃",
					"双手继续挥动",
					"兴奋表情减弱",
					"回到起始站立姿态",
				}),
				MotionDescription:      "角色高举双手欢呼跳跃，表达强烈兴奋情绪",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，双臂高举挥动，张大嘴巴，身体跳跃",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色表现出兴奋的样子，高举双手欢呼跳跃",
				NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏、肢体扭曲",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       12,
				ReturnPolicy:     contracts.ReturnCurrentActivity,
				Interruptible:    true,
				InterruptAfterMS: 500,
				MinimumPlayMS:    833,
				MaximumPlayMS:    3500,
				Priority:         55,
				CooldownMS:       6000,
				MutexGroup:       "emotion_expression",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    3000,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "shy",
				Name:                "害羞",
				Description:         "角色脸颊泛红，双手捂脸，身体扭动，眼神躲闪",
				CategoryKey:         "emotion",
				CategoryName:        "情绪动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   40,
				ActionSortOrder:     42,
				Tags:                []string{"emotion", "shy"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 8,
				FramePhases: makePhases([]string{
					"起始自然表情",
					"脸颊开始泛红",
					"双手开始抬起",
					"双手捂住脸颊",
					"身体轻微扭动",
					"眼神躲闪向侧方",
					"继续保持害羞姿态",
					"回到带红晕的起始姿态",
				}),
				MotionDescription:      "角色脸颊泛红，双手捂脸，身体扭动，眼神躲闪",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，脸颊泛红，双手捂住脸颊，身体轻微扭动",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色表现出害羞的样子，脸颊泛红双手捂脸",
				NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏、手势异常",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       8,
				ReturnPolicy:     contracts.ReturnCurrentActivity,
				Interruptible:    true,
				InterruptAfterMS: 500,
				MinimumPlayMS:    1000,
				MaximumPlayMS:    3500,
				Priority:         48,
				CooldownMS:       7000,
				MutexGroup:       "emotion_expression",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    3000,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "sad",
				Name:                "难过",
				Description:         "角色嘴角下垂眉头紧锁，头部低垂双肩下沉",
				CategoryKey:         "emotion",
				CategoryName:        "情绪动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         true,
				SupportsDefaultIdle: false,
				CategorySortOrder:   40,
				ActionSortOrder:     43,
				Tags:                []string{"emotion", "sad"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 8,
				FramePhases: makePhases([]string{
					"起始自然表情",
					"嘴角开始下垂",
					"眉头紧锁，眼神低垂",
					"头部低下",
					"双肩下沉",
					"身体微微蜷缩",
					"保持低落姿态",
					"回到难过的起始姿态",
				}),
				MotionDescription:      "角色嘴角下垂眉头紧锁，头部低垂双肩下沉",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，嘴角下垂，眉头紧锁，头部低垂，双肩下沉",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色表现出难过的样子，嘴角下垂眼神低垂",
				NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏、眼泪位置异常",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       8,
				ReturnPolicy:     contracts.ReturnCurrentActivity,
				Interruptible:    true,
				InterruptAfterMS: 500,
				MinimumPlayMS:    1000,
				MaximumPlayMS:    3500,
				Priority:         50,
				CooldownMS:       5000,
				MutexGroup:       "emotion_expression",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    2000,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "cry",
				Name:                "哭泣",
				Description:         "角色眼眶泛红流泪哭泣，用手背擦拭眼泪并抽泣",
				CategoryKey:         "emotion",
				CategoryName:        "情绪动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   40,
				ActionSortOrder:     44,
				Tags:                []string{"emotion", "cry"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 10,
				FramePhases: makePhases([]string{
					"起始自然表情",
					"眼眶开始泛红",
					"眼泪开始在眼眶聚集",
					"第一滴眼泪滑落",
					"嘴角下垂开始抽泣",
					"用手背擦拭眼泪",
					"继续抽泣",
					"眼泪继续流淌",
					"抽泣减弱",
					"回到带泪痕的起始姿态",
				}),
				MotionDescription:      "角色眼眶泛红流泪哭泣，用手背擦拭眼泪并抽泣",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，眼眶泛红，眼泪滑落，用手背擦泪，嘴角下垂抽泣",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色流泪哭泣，眼泪滑落并用双手擦拭",
				NegativePromptFragment: "多余人物、变形、眼泪位置异常、面部崩坏、手势异常",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       10,
				ReturnPolicy:     contracts.ReturnCurrentActivity,
				Interruptible:    true,
				InterruptAfterMS: 500,
				MinimumPlayMS:    1000,
				MaximumPlayMS:    3500,
				Priority:         58,
				CooldownMS:       10000,
				MutexGroup:       "emotion_expression",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    5000,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "angry",
				Name:                "愤怒",
				Description:         "角色眉头紧锁眉毛下压，双拳握紧身体前倾",
				CategoryKey:         "emotion",
				CategoryName:        "情绪动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   40,
				ActionSortOrder:     45,
				Tags:                []string{"emotion", "angry"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 8,
				FramePhases: makePhases([]string{
					"起始自然表情",
					"眉头开始紧锁",
					"眉毛下压，眼神凌厉",
					"嘴唇紧抿",
					"咬牙切齿",
					"双拳握紧",
					"身体前倾表达怒意",
					"回到愤怒的起始姿态",
				}),
				MotionDescription:      "角色眉头紧锁眉毛下压，双拳握紧身体前倾",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，眉头紧锁下压，嘴唇紧抿，双拳握紧，身体前倾",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色表现出愤怒的样子，眉头紧锁双拳握紧",
				NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏、肢体扭曲",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       10,
				ReturnPolicy:     contracts.ReturnCurrentActivity,
				Interruptible:    true,
				InterruptAfterMS: 500,
				MinimumPlayMS:    800,
				MaximumPlayMS:    3500,
				Priority:         60,
				CooldownMS:       8000,
				MutexGroup:       "emotion_expression",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    4000,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "surprised",
				Name:                "惊讶",
				Description:         "角色眼睛睁大嘴巴张开，双手抬起表达震惊",
				CategoryKey:         "emotion",
				CategoryName:        "情绪动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   40,
				ActionSortOrder:     46,
				Tags:                []string{"emotion", "surprised"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 6,
				FramePhases: makePhases([]string{
					"起始自然表情",
					"眼睛开始睁大",
					"眼睛完全睁大，嘴巴微张",
					"嘴巴张到最大",
					"双手轻微抬起表达震惊",
					"保持惊讶表情",
				}),
				MotionDescription:      "角色眼睛睁大嘴巴张开，双手抬起表达震惊",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，眼睛睁大，嘴巴张开，双手轻微抬起",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色表现出惊讶的样子，眼睛睁大嘴巴张开",
				NegativePromptFragment: "多余人物、变形、眼睛过大、嘴巴过大、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       12,
				ReturnPolicy:     contracts.ReturnCurrentActivity,
				Interruptible:    true,
				InterruptAfterMS: 500,
				MinimumPlayMS:    500,
				MaximumPlayMS:    3500,
				Priority:         62,
				CooldownMS:       5000,
				MutexGroup:       "emotion_expression",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    2500,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "confused",
				Name:                "困惑",
				Description:         "角色一侧眉毛上挑头部歪斜，抬手摸下巴表达疑惑",
				CategoryKey:         "emotion",
				CategoryName:        "情绪动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   40,
				ActionSortOrder:     47,
				Tags:                []string{"emotion", "confused"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 8,
				FramePhases: makePhases([]string{
					"起始自然表情",
					"一侧眉毛开始上挑",
					"头部轻微歪斜",
					"嘴角歪斜",
					"眼神迷茫",
					"抬手摸下巴思考",
					"继续保持疑惑姿态",
					"回到疑惑的起始姿态",
				}),
				MotionDescription:      "角色一侧眉毛上挑头部歪斜，抬手摸下巴表达疑惑",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，一侧眉毛上挑，头部轻微歪斜，抬手摸下巴",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色表现出疑惑的样子，歪头抬手摸下巴思考",
				NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏、手势异常",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       8,
				ReturnPolicy:     contracts.ReturnCurrentActivity,
				Interruptible:    true,
				InterruptAfterMS: 500,
				MinimumPlayMS:    1000,
				MaximumPlayMS:    3500,
				Priority:         48,
				CooldownMS:       5000,
				MutexGroup:       "emotion_expression",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    2500,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "embarrassed",
				Name:                "尴尬",
				Description:         "角色脸颊泛红眼神躲闪，手抬到头后抓挠，嘴角苦笑",
				CategoryKey:         "emotion",
				CategoryName:        "情绪动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   40,
				ActionSortOrder:     48,
				Tags:                []string{"emotion", "embarrassed"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 8,
				FramePhases: makePhases([]string{
					"起始自然表情",
					"脸颊开始泛红",
					"眼神开始躲闪",
					"手抬到头后抓挠",
					"嘴角勉强苦笑",
					"身体轻微扭动",
					"继续保持尴尬姿态",
					"回到尴尬的起始姿态",
				}),
				MotionDescription:      "角色脸颊泛红眼神躲闪，手抬到头后抓挠，嘴角苦笑",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，脸颊泛红，眼神躲闪，手抬至头后，身体扭动",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色表现出尴尬的样子，脸颊泛红手抓后脑勺苦笑",
				NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏、手势异常",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       8,
				ReturnPolicy:     contracts.ReturnCurrentActivity,
				Interruptible:    true,
				InterruptAfterMS: 500,
				MinimumPlayMS:    1000,
				MaximumPlayMS:    3500,
				Priority:         50,
				CooldownMS:       7000,
				MutexGroup:       "emotion_expression",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    3000,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "scared",
				Name:                "害怕",
				Description:         "角色瞳孔收缩身体后退，双臂护胸身体蜷缩颤抖",
				CategoryKey:         "emotion",
				CategoryName:        "情绪动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   40,
				ActionSortOrder:     49,
				Tags:                []string{"emotion", "scared"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 8,
				FramePhases: makePhases([]string{
					"起始自然表情",
					"瞳孔开始收缩",
					"身体开始后退",
					"双臂抬起护在胸前",
					"身体蜷缩",
					"头部后仰",
					"全身轻微颤抖",
					"回到恐惧的起始姿态",
				}),
				MotionDescription:      "角色瞳孔收缩身体后退，双臂护胸身体蜷缩颤抖",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，瞳孔收缩，身体后退蜷缩，双臂护在胸前，全身颤抖",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色表现出害怕的样子，身体后退蜷缩双臂护胸",
				NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏、肢体扭曲",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       10,
				ReturnPolicy:     contracts.ReturnCurrentActivity,
				Interruptible:    true,
				InterruptAfterMS: 500,
				MinimumPlayMS:    800,
				MaximumPlayMS:    3500,
				Priority:         63,
				CooldownMS:       8000,
				MutexGroup:       "emotion_expression",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    4000,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "proud",
				Name:                "得意",
				Description:         "角色下巴抬起双手叉腰，挺胸抬头露出得意笑容",
				CategoryKey:         "emotion",
				CategoryName:        "情绪动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   40,
				ActionSortOrder:     50,
				Tags:                []string{"emotion", "proud"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 8,
				FramePhases: makePhases([]string{
					"起始站立",
					"下巴开始抬起",
					"双手叉腰",
					"挺胸抬头",
					"嘴角上扬露出得意笑容",
					"保持得意姿态",
					"眼神自信",
					"回到得意的起始姿态",
				}),
				MotionDescription:      "角色下巴抬起双手叉腰，挺胸抬头露出得意笑容",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，下巴抬起，双手叉腰，挺胸抬头",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色表现出得意的样子，双手叉腰挺胸抬头",
				NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏、手势异常",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       9,
				ReturnPolicy:     contracts.ReturnCurrentActivity,
				Interruptible:    true,
				InterruptAfterMS: 500,
				MinimumPlayMS:    888,
				MaximumPlayMS:    3500,
				Priority:         50,
				CooldownMS:       7000,
				MutexGroup:       "emotion_expression",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    3000,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "tired",
				Name:                "疲惫",
				Description:         "角色双肩下沉头部低垂，打哈欠揉眼，身体佝偻",
				CategoryKey:         "emotion",
				CategoryName:        "情绪动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   40,
				ActionSortOrder:     51,
				Tags:                []string{"emotion", "tired"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 8,
				FramePhases: makePhases([]string{
					"起始站立",
					"双肩开始下沉",
					"头部开始低垂",
					"眼皮开始下垂",
					"张嘴打哈欠",
					"用手揉眼睛",
					"身体微微佝偻",
					"回到疲惫的起始姿态",
				}),
				MotionDescription:      "角色双肩下沉头部低垂，打哈欠揉眼，身体佝偻",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面站立，双肩下沉，头部低垂，眼皮下垂，身体佝偻",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色表现出疲惫的样子，打哈欠揉眼睛双肩下沉",
				NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏、手势异常",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       8,
				ReturnPolicy:     contracts.ReturnCurrentActivity,
				Interruptible:    true,
				InterruptAfterMS: 500,
				MinimumPlayMS:    1000,
				MaximumPlayMS:    3500,
				Priority:         45,
				CooldownMS:       6000,
				MutexGroup:       "emotion_expression",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    3000,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
	}
}
