// SPDX-FileCopyrightText: 2026 彭旭
// SPDX-License-Identifier: AGPL-3.0-only
package specs

import "github.com/u-ai/backend/internal/desktoppet/contracts"

func desktopSpecs() []contracts.ActionSpec {
	return []contracts.ActionSpec{
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "clicked",
				Name:                "被点击",
				Description:         defaultSpecs["clicked"].MotionDescription,
				CategoryKey:         "desktop",
				CategoryName:        "桌面交互",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         true,
				SupportsDefaultIdle: false,
				CategorySortOrder:   60,
				ActionSortOrder:     60,
				Tags:                []string{"desktop", "pointer", "click", "reaction"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: defaultSpecs["clicked"].FrameCount,
				FramePhases: makePhases([]string{
					"起始站立",
					"受到点击惊讶反应",
					"身体轻微后仰",
					"回过神来恢复站立",
				}),
				MotionDescription:      defaultSpecs["clicked"].MotionDescription,
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         defaultSpecs["clicked"].PoseConstraint,
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         defaultSpecs["clicked"].PromptFragment,
				NegativePromptFragment: defaultSpecs["clicked"].NegativePromptFragment,
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       12,
				ReturnPolicy:     contracts.ReturnPrevious,
				ReturnActionKey:  "",
				Interruptible:    false,
				InterruptAfterMS: 0,
				MinimumPlayMS:    333,
				MaximumPlayMS:    900,
				Priority:         72,
				CooldownMS:       250,
				MutexGroup:       "pointer_reaction",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    200,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "double_clicked",
				Name:                "被双击",
				Description:         defaultSpecs["double_clicked"].MotionDescription,
				CategoryKey:         "desktop",
				CategoryName:        "桌面交互",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   60,
				ActionSortOrder:     61,
				Tags:                []string{"desktop", "pointer", "double_click", "reaction"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: defaultSpecs["double_clicked"].FrameCount,
				FramePhases: makePhases([]string{
					"起始站立",
					"第一次点击反应",
					"第二次点击反应更强",
					"恢复站立",
				}),
				MotionDescription:      defaultSpecs["double_clicked"].MotionDescription,
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         defaultSpecs["double_clicked"].PoseConstraint,
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         defaultSpecs["double_clicked"].PromptFragment,
				NegativePromptFragment: defaultSpecs["double_clicked"].NegativePromptFragment,
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       12,
				ReturnPolicy:     contracts.ReturnPrevious,
				ReturnActionKey:  "",
				Interruptible:    false,
				InterruptAfterMS: 0,
				MinimumPlayMS:    333,
				MaximumPlayMS:    900,
				Priority:         74,
				CooldownMS:       400,
				MutexGroup:       "pointer_reaction",
				QueuePolicy:      contracts.QueueCoalesce,
				DedupWindowMS:    300,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "hovered",
				Name:                "被悬停",
				Description:         defaultSpecs["hovered"].MotionDescription,
				CategoryKey:         "desktop",
				CategoryName:        "桌面交互",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   60,
				ActionSortOrder:     62,
				Tags:                []string{"desktop", "pointer", "hover", "hold_pose"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: defaultSpecs["hovered"].FrameCount,
				FramePhases: makePhases([]string{
					"起始站立",
					"注意到鼠标靠近",
					"看向鼠标方向",
					"保持注视",
				}),
				MotionDescription:      defaultSpecs["hovered"].MotionDescription,
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         defaultSpecs["hovered"].PoseConstraint,
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         defaultSpecs["hovered"].PromptFragment,
				NegativePromptFragment: defaultSpecs["hovered"].NegativePromptFragment,
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackHold,
				DefaultFPS:       10,
				ReturnPolicy:     contracts.ReturnPrevious,
				ReturnActionKey:  "",
				Interruptible:    true,
				InterruptAfterMS: 300,
				MinimumPlayMS:    400,
				MaximumPlayMS:    0,
				Priority:         35,
				CooldownMS:       200,
				MutexGroup:       "pointer_reaction",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: true,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "dragged",
				Name:                "被拖动",
				Description:         defaultSpecs["dragged"].MotionDescription,
				CategoryKey:         "desktop",
				CategoryName:        "桌面交互",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         true,
				SupportsDefaultIdle: false,
				CategorySortOrder:   60,
				ActionSortOrder:     63,
				Tags:                []string{"desktop", "pointer", "drag", "hold_pose"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: defaultSpecs["dragged"].FrameCount,
				FramePhases: makePhases([]string{
					"起始站立",
					"被抓起的瞬间",
					"身体悬空跟随移动",
					"四肢下垂晃动",
					"继续被拖动",
					"保持悬空姿态",
				}),
				MotionDescription:      defaultSpecs["dragged"].MotionDescription,
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         defaultSpecs["dragged"].PoseConstraint,
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         defaultSpecs["dragged"].PromptFragment,
				NegativePromptFragment: defaultSpecs["dragged"].NegativePromptFragment,
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackHold,
				DefaultFPS:       10,
				ReturnPolicy:     contracts.ReturnPrevious,
				ReturnActionKey:  "",
				Interruptible:    false,
				InterruptAfterMS: 0,
				MinimumPlayMS:    600,
				MaximumPlayMS:    0,
				Priority:         88,
				CooldownMS:       0,
				MutexGroup:       "drag_state",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: true,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "picked_up",
				Name:                "被提起",
				Description:         defaultSpecs["picked_up"].MotionDescription,
				CategoryKey:         "desktop",
				CategoryName:        "桌面交互",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   60,
				ActionSortOrder:     64,
				Tags:                []string{"desktop", "physics", "picked_up", "hold_pose"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: defaultSpecs["picked_up"].FrameCount,
				FramePhases: makePhases([]string{
					"起始站立",
					"被抓住的瞬间",
					"开始离开地面",
					"身体上升",
					"完全悬空",
					"四肢自然下垂",
					"轻微晃动",
					"保持悬空姿态",
				}),
				MotionDescription:      defaultSpecs["picked_up"].MotionDescription,
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         defaultSpecs["picked_up"].PoseConstraint,
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         defaultSpecs["picked_up"].PromptFragment,
				NegativePromptFragment: defaultSpecs["picked_up"].NegativePromptFragment,
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackHold,
				DefaultFPS:       10,
				ReturnPolicy:     contracts.ReturnPrevious,
				ReturnActionKey:  "",
				Interruptible:    false,
				InterruptAfterMS: 0,
				MinimumPlayMS:    800,
				MaximumPlayMS:    0,
				Priority:         90,
				CooldownMS:       0,
				MutexGroup:       "drag_state",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: true,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "dropped",
				Name:                "被放下",
				Description:         defaultSpecs["dropped"].MotionDescription,
				CategoryKey:         "desktop",
				CategoryName:        "桌面交互",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   60,
				ActionSortOrder:     65,
				Tags:                []string{"desktop", "physics", "drop", "transition"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: defaultSpecs["dropped"].FrameCount,
				FramePhases: makePhases([]string{
					"悬空姿态",
					"开始下落",
					"继续下落",
					"双脚触地",
					"双腿弯曲缓冲",
					"恢复稳定站立",
				}),
				MotionDescription:      defaultSpecs["dropped"].MotionDescription,
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         defaultSpecs["dropped"].PoseConstraint,
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         defaultSpecs["dropped"].PromptFragment,
				NegativePromptFragment: defaultSpecs["dropped"].NegativePromptFragment,
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       12,
				ReturnPolicy:     contracts.ReturnSpecific,
				ReturnActionKey:  "fall",
				Interruptible:    false,
				InterruptAfterMS: 0,
				MinimumPlayMS:    500,
				MaximumPlayMS:    1200,
				Priority:         92,
				CooldownMS:       0,
				MutexGroup:       "physics_motion",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "fall",
				Name:                "掉落",
				Description:         defaultSpecs["fall"].MotionDescription,
				CategoryKey:         "desktop",
				CategoryName:        "桌面交互",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   60,
				ActionSortOrder:     66,
				Tags:                []string{"desktop", "physics", "airborne", "fall"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: defaultSpecs["fall"].FrameCount,
				FramePhases: makePhases([]string{
					"起始悬空或边缘姿态",
					"开始失去平衡",
					"身体开始下落",
					"继续下落，四肢张开",
					"加速下落",
					"继续下落",
					"接近地面",
					"即将触地",
					"双脚触地",
					"趴在地上",
				}),
				MotionDescription:      defaultSpecs["fall"].MotionDescription,
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         defaultSpecs["fall"].PoseConstraint,
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         defaultSpecs["fall"].PromptFragment,
				NegativePromptFragment: defaultSpecs["fall"].NegativePromptFragment,
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       12,
				ReturnPolicy:     contracts.ReturnSpecific,
				ReturnActionKey:  "land",
				Interruptible:    false,
				InterruptAfterMS: 0,
				MinimumPlayMS:    833,
				MaximumPlayMS:    0,
				Priority:         95,
				CooldownMS:       0,
				MutexGroup:       "physics_motion",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorCenter,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "edge_sit",
				Name:                "边缘静坐",
				Description:         defaultSpecs["edge_sit"].MotionDescription,
				CategoryKey:         "desktop",
				CategoryName:        "桌面交互",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   60,
				ActionSortOrder:     67,
				Tags:                []string{"desktop", "edge", "sit", "long_running"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: defaultSpecs["edge_sit"].FrameCount,
				FramePhases: makePhases([]string{
					"起始站立",
					"走向窗口边缘",
					"转身背对边缘",
					"开始坐下",
					"双腿悬在边缘外侧",
					"稳定坐姿",
					"双手撑在边缘",
					"保持坐在边缘的姿态",
				}),
				MotionDescription:      defaultSpecs["edge_sit"].MotionDescription,
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         defaultSpecs["edge_sit"].PoseConstraint,
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         defaultSpecs["edge_sit"].PromptFragment,
				NegativePromptFragment: defaultSpecs["edge_sit"].NegativePromptFragment,
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       8,
				ReturnPolicy:     contracts.ReturnNone,
				ReturnActionKey:  "",
				Interruptible:    true,
				InterruptAfterMS: 1000,
				MinimumPlayMS:    1000,
				MaximumPlayMS:    0,
				Priority:         34,
				CooldownMS:       500,
				MutexGroup:       "edge_activity",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorEdgeContact,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "edge_climb",
				Name:                "边缘攀爬",
				Description:         defaultSpecs["edge_climb"].MotionDescription,
				CategoryKey:         "desktop",
				CategoryName:        "桌面交互",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   60,
				ActionSortOrder:     68,
				Tags:                []string{"desktop", "edge", "climb", "movement"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: defaultSpecs["edge_climb"].FrameCount,
				FramePhases: makePhases([]string{
					"起始在边缘下方",
					"双手抓住边缘",
					"开始向上攀爬",
					"双臂发力引体向上",
					"头部越过边缘",
					"上半身翻过边缘",
					"一条腿跨上边缘",
					"继续翻越",
					"接近完成攀爬",
					"完成攀爬坐在边缘",
				}),
				MotionDescription:      defaultSpecs["edge_climb"].MotionDescription,
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         defaultSpecs["edge_climb"].PoseConstraint,
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         defaultSpecs["edge_climb"].PromptFragment,
				NegativePromptFragment: defaultSpecs["edge_climb"].NegativePromptFragment,
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       12,
				ReturnPolicy:     contracts.ReturnCurrentActivity,
				ReturnActionKey:  "",
				Interruptible:    true,
				InterruptAfterMS: 833,
				MinimumPlayMS:    833,
				MaximumPlayMS:    0,
				Priority:         66,
				CooldownMS:       0,
				MutexGroup:       "edge_motion",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorEdgeContact,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "sleep_on_desktop",
				Name:                "趴桌入睡",
				Description:         defaultSpecs["sleep_on_desktop"].MotionDescription,
				CategoryKey:         "desktop",
				CategoryName:        "桌面交互",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   60,
				ActionSortOrder:     69,
				Tags:                []string{"desktop", "life", "sleep", "long_running"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: defaultSpecs["sleep_on_desktop"].FrameCount,
				FramePhases: makePhases([]string{
					"起始坐姿",
					"开始疲倦打哈欠",
					"双手交叠放在桌面",
					"头部开始低下",
					"头部靠在手上",
					"闭眼入睡",
					"进入浅睡眠",
					"呼吸平稳起伏",
					"进入深睡眠",
					"轻微翻身",
					"继续安稳睡眠",
					"保持趴睡姿态",
				}),
				MotionDescription:      defaultSpecs["sleep_on_desktop"].MotionDescription,
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         defaultSpecs["sleep_on_desktop"].PoseConstraint,
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         defaultSpecs["sleep_on_desktop"].PromptFragment,
				NegativePromptFragment: defaultSpecs["sleep_on_desktop"].NegativePromptFragment,
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       6,
				ReturnPolicy:     contracts.ReturnNone,
				ReturnActionKey:  "",
				Interruptible:    true,
				InterruptAfterMS: 2000,
				MinimumPlayMS:    2000,
				MaximumPlayMS:    0,
				Priority:         31,
				CooldownMS:       1000,
				MutexGroup:       "activity_sleep",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorSurfaceContact,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
	}
}
