// SPDX-FileCopyrightText: 2026 彭旭
// SPDX-License-Identifier: AGPL-3.0-only
package specs

import "github.com/u-ai/backend/internal/desktoppet/contracts"

func lifeSpecs() []contracts.ActionSpec {
	return []contracts.ActionSpec{
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "sit",
				Name:                "坐下",
				Description:         "角色从站立弯曲双腿下蹲至稳定坐姿",
				CategoryKey:         "life",
				CategoryName:        "生活动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   50,
				ActionSortOrder:     50,
				Tags:                []string{"life", "activity", "sit", "hold_pose"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 6,
				FramePhases: makePhases([]string{
					"起始站立",
					"双腿开始弯曲",
					"身体开始下降",
					"接近坐姿",
					"完全坐下",
					"稳定坐姿",
				}),
				MotionDescription:      "角色从站立弯曲双腿下蹲至稳定坐姿",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面朝向，双腿弯曲，臀部贴近地面或座椅，上半身保持垂直",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色从站立变为坐下，双腿弯曲身体下降",
				NegativePromptFragment: "多余人物、变形、穿模、肢体扭曲、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackHold,
				DefaultFPS:       10,
				ReturnPolicy:     contracts.ReturnNone,
				Interruptible:    true,
				InterruptAfterMS: 600,
				MinimumPlayMS:    600,
				MaximumPlayMS:    0,
				Priority:         30,
				CooldownMS:       500,
				MutexGroup:       "activity_pose",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: true,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "sleep",
				Name:                "睡觉",
				Description:         "角色弯腰躺下闭眼进入睡眠，呼吸平稳并轻微翻身",
				CategoryKey:         "life",
				CategoryName:        "生活动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         true,
				SupportsDefaultIdle: false,
				CategorySortOrder:   50,
				ActionSortOrder:     51,
				Tags:                []string{"life", "activity", "sleep", "long_running"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 12,
				FramePhases: makePhases([]string{
					"起始站立",
					"开始弯腰",
					"双手撑地",
					"身体下降准备躺下",
					"身体接近地面",
					"完全躺下",
					"闭眼进入睡眠",
					"呼吸平稳起伏",
					"轻微翻身",
					"继续安稳睡眠",
					"嘴角轻微活动",
					"保持睡眠姿态",
				}),
				MotionDescription:      "角色弯腰躺下闭眼进入睡眠，呼吸平稳并轻微翻身",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "身体水平躺卧，双眼闭合，双手自然放置身侧或交叠",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色躺下睡觉，闭眼呼吸平稳进入睡眠",
				NegativePromptFragment: "多余人物、变形、穿模、肢体扭曲、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       6,
				ReturnPolicy:     contracts.ReturnNone,
				Interruptible:    true,
				InterruptAfterMS: 2000,
				MinimumPlayMS:    2000,
				MaximumPlayMS:    0,
				Priority:         32,
				CooldownMS:       1000,
				MutexGroup:       "activity_sleep",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "wake_up",
				Name:                "醒来",
				Description:         "角色从躺卧睡眠中睁眼，揉眼撑起坐立伸懒腰清醒",
				CategoryKey:         "life",
				CategoryName:        "生活动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   50,
				ActionSortOrder:     52,
				Tags:                []string{"life", "transition", "wake_up"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 8,
				FramePhases: makePhases([]string{
					"躺卧睡眠姿态",
					"眼皮开始颤动",
					"眼睛微微睁开",
					"用手揉眼睛",
					"开始撑起身体",
					"上半身坐起",
					"伸懒腰清醒",
					"完全清醒的坐姿",
				}),
				MotionDescription:      "角色从躺卧睡眠中睁眼，揉眼撑起坐立伸懒腰清醒",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "从躺卧转为坐姿，眼皮颤动后睁眼，用手揉眼，上半身撑起",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色从睡眠中醒来，睁眼揉眼坐起伸懒腰",
				NegativePromptFragment: "多余人物、变形、穿模、肢体扭曲、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackOnce,
				DefaultFPS:       10,
				ReturnPolicy:     contracts.ReturnDefaultIdle,
				Interruptible:    false,
				InterruptAfterMS: 0,
				MinimumPlayMS:    800,
				MaximumPlayMS:    1800,
				Priority:         70,
				CooldownMS:       1000,
				MutexGroup:       "activity_sleep",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     false,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "eat",
				Name:                "进食",
				Description:         "角色拿起食物送至嘴边咬下，咀嚼吞咽后露出满足表情",
				CategoryKey:         "life",
				CategoryName:        "生活动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   50,
				ActionSortOrder:     53,
				Tags:                []string{"life", "activity", "eat", "long_running"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 10,
				FramePhases: makePhases([]string{
					"起始坐姿或站姿",
					"拿起食物",
					"将食物送向嘴边",
					"食物接近嘴巴",
					"张嘴咬下食物",
					"开始咀嚼",
					"继续咀嚼",
					"吞咽",
					"满足表情",
					"回到起始姿态",
				}),
				MotionDescription:      "角色拿起食物送至嘴边咬下，咀嚼吞咽后露出满足表情",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面朝向，一手拿起食物送至嘴边，张嘴咬下后咀嚼",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色进食，拿起食物送入嘴中咀嚼吞咽",
				NegativePromptFragment: "多余人物、变形、食物异常、手势异常、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       10,
				ReturnPolicy:     contracts.ReturnNone,
				Interruptible:    true,
				InterruptAfterMS: 1000,
				MinimumPlayMS:    1000,
				MaximumPlayMS:    0,
				Priority:         30,
				CooldownMS:       500,
				MutexGroup:       "activity_loop",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "drink",
				Name:                "喝水",
				Description:         "角色拿起杯子送至嘴边仰头饮水后放下杯子",
				CategoryKey:         "life",
				CategoryName:        "生活动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   50,
				ActionSortOrder:     54,
				Tags:                []string{"life", "activity", "drink", "long_running"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 8,
				FramePhases: makePhases([]string{
					"起始姿态",
					"拿起杯子",
					"将杯子送向嘴边",
					"杯子接触嘴唇",
					"仰头饮水",
					"继续饮水",
					"放下杯子",
					"回到起始姿态",
				}),
				MotionDescription:      "角色拿起杯子送至嘴边仰头饮水后放下杯子",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面朝向，一手拿起杯子送至嘴边，仰头饮水",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色喝水，拿起杯子送至嘴边仰头饮用",
				NegativePromptFragment: "多余人物、变形、杯子异常、手势异常、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       10,
				ReturnPolicy:     contracts.ReturnNone,
				Interruptible:    true,
				InterruptAfterMS: 800,
				MinimumPlayMS:    800,
				MaximumPlayMS:    0,
				Priority:         30,
				CooldownMS:       500,
				MutexGroup:       "activity_loop",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "read",
				Name:                "阅读",
				Description:         "角色拿起书本翻开阅读，翻页并点头表示理解",
				CategoryKey:         "life",
				CategoryName:        "生活动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   50,
				ActionSortOrder:     55,
				Tags:                []string{"life", "activity", "read", "long_running"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 10,
				FramePhases: makePhases([]string{
					"起始坐姿",
					"拿起书本",
					"翻开书本",
					"将书本举到面前",
					"开始阅读",
					"眼神随文字移动",
					"翻页",
					"继续阅读",
					"点头表示理解",
					"继续保持阅读姿态",
				}),
				MotionDescription:      "角色拿起书本翻开阅读，翻页并点头表示理解",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "坐姿，双手捧书举至面前，眼神随文字移动",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色阅读书籍，双手捧书翻页阅读",
				NegativePromptFragment: "多余人物、变形、书本异常、手势异常、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       8,
				ReturnPolicy:     contracts.ReturnNone,
				Interruptible:    true,
				InterruptAfterMS: 1250,
				MinimumPlayMS:    1250,
				MaximumPlayMS:    0,
				Priority:         30,
				CooldownMS:       500,
				MutexGroup:       "activity_loop",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "write",
				Name:                "书写",
				Description:         "角色拿起笔在纸面书写，抬笔思考后继续并检查",
				CategoryKey:         "life",
				CategoryName:        "生活动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   50,
				ActionSortOrder:     56,
				Tags:                []string{"life", "activity", "write", "long_running"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 10,
				FramePhases: makePhases([]string{
					"起始坐姿",
					"拿起笔",
					"笔尖接触纸面",
					"开始书写",
					"继续书写",
					"抬笔思考",
					"继续书写",
					"书写中",
					"停笔",
					"检查书写内容",
				}),
				MotionDescription:      "角色拿起笔在纸面书写，抬笔思考后继续并检查",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "坐姿，一手执笔在纸面书写，另一手按住纸张",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色书写，拿笔在纸面上写字",
				NegativePromptFragment: "多余人物、变形、笔异常、手势异常、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       9,
				ReturnPolicy:     contracts.ReturnNone,
				Interruptible:    true,
				InterruptAfterMS: 1111,
				MinimumPlayMS:    1111,
				MaximumPlayMS:    0,
				Priority:         30,
				CooldownMS:       500,
				MutexGroup:       "activity_loop",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "use_phone",
				Name:                "玩手机",
				Description:         "角色拿出手机解锁浏览，滑动点击并打字发送消息",
				CategoryKey:         "life",
				CategoryName:        "生活动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   50,
				ActionSortOrder:     57,
				Tags:                []string{"life", "activity", "use_phone", "long_running"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 10,
				FramePhases: makePhases([]string{
					"起始姿态",
					"拿出手机",
					"解锁屏幕",
					"开始浏览",
					"手指滑动屏幕",
					"点击屏幕",
					"继续浏览",
					"打字输入",
					"发送消息",
					"继续使用手机",
				}),
				MotionDescription:      "角色拿出手机解锁浏览，滑动点击并打字发送消息",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "正面朝向，单手或双手持手机，手指在屏幕上滑动点击",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色使用手机，滑动屏幕浏览并打字输入",
				NegativePromptFragment: "多余人物、变形、手机异常、手势异常、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       8,
				ReturnPolicy:     contracts.ReturnNone,
				Interruptible:    true,
				InterruptAfterMS: 1250,
				MinimumPlayMS:    1250,
				MaximumPlayMS:    0,
				Priority:         30,
				CooldownMS:       500,
				MutexGroup:       "activity_loop",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "work",
				Name:                "工作",
				Description:         "角色伏案专注工作，敲击键盘翻阅资料并思考",
				CategoryKey:         "life",
				CategoryName:        "生活动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   50,
				ActionSortOrder:     58,
				Tags:                []string{"life", "activity", "work", "long_running"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 10,
				FramePhases: makePhases([]string{
					"起始坐姿",
					"双手放在桌面",
					"开始操作",
					"专注工作中",
					"敲击键盘",
					"思考片刻",
					"继续工作",
					"翻阅资料",
					"继续专注工作",
					"保持工作姿态",
				}),
				MotionDescription:      "角色伏案专注工作，敲击键盘翻阅资料并思考",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "坐姿，身体前倾向桌面，双手操作键盘或翻阅资料",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色伏案工作，敲击键盘专注操作",
				NegativePromptFragment: "多余人物、变形、键盘异常、手势异常、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       8,
				ReturnPolicy:     contracts.ReturnNone,
				Interruptible:    true,
				InterruptAfterMS: 1250,
				MinimumPlayMS:    1250,
				MaximumPlayMS:    0,
				Priority:         30,
				CooldownMS:       500,
				MutexGroup:       "activity_loop",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
		{
			SchemaVersion: contracts.ActionSpecSchemaVersion,
			Identity: contracts.ActionIdentity{
				Key:                 "study",
				Name:                "学习",
				Description:         "角色翻开书本阅读做笔记，思考翻页并标记重点",
				CategoryKey:         "life",
				CategoryName:        "生活动作",
				Source:              contracts.ActionSourceBuiltin,
				DefinitionVersion:   1,
				Enabled:             true,
				Recommended:         false,
				SupportsDefaultIdle: false,
				CategorySortOrder:   50,
				ActionSortOrder:     59,
				Tags:                []string{"life", "activity", "study", "long_running"},
			},
			Generation: contracts.ActionGenerationSpec{
				Version:    1,
				Strategy:   contracts.GenerationTypeSequential,
				FrameCount: 10,
				FramePhases: makePhases([]string{
					"起始坐姿",
					"翻开书本",
					"开始阅读",
					"认真阅读",
					"做笔记",
					"继续阅读",
					"思考问题",
					"翻页继续",
					"标记重点",
					"保持学习姿态",
				}),
				MotionDescription:      "角色翻开书本阅读做笔记，思考翻页并标记重点",
				CameraConstraint:       cameraConstraint,
				PoseConstraint:         "坐姿，一手翻书阅读，一手执笔做笔记",
				ContinuityConstraint:   continuityConstraint,
				PromptFragment:         "角色学习，翻书阅读并做笔记标记重点",
				NegativePromptFragment: "多余人物、变形、书本异常、手势异常、面部崩坏",
			},
			Playback: contracts.ActionPlaybackSpec{
				Mode:             contracts.PlaybackLoop,
				DefaultFPS:       8,
				ReturnPolicy:     contracts.ReturnNone,
				Interruptible:    true,
				InterruptAfterMS: 1250,
				MinimumPlayMS:    1250,
				MaximumPlayMS:    0,
				Priority:         30,
				CooldownMS:       500,
				MutexGroup:       "activity_loop",
				QueuePolicy:      contracts.QueueReplace,
				DedupWindowMS:    0,
			},
			Processing: contracts.ActionProcessingHints{
				AnchorProfile:     contracts.AnchorFeetCenter,
				CheckLoopSeam:     true,
				PreserveLastFrame: false,
			},
		},
	}
}
