// SPDX-FileCopyrightText: 2026 彭旭
// SPDX-License-Identifier: AGPL-3.0-only
package specs

const cameraConstraint = "固定正面镜头，角色半身居中，保持固定缩放比例"
const continuityConstraint = "保持与参考图同一角色，脸部/发型/服装/配饰/身体比例一致"

var defaultSpecs = map[string]ActionGenerationSpec{
	"idle_normal": {
		ActionKey:  "idle_normal",
		LoopType:   LoopTypeLoop,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始自然站立姿态，双臂自然下垂"},
			{Index: 1, Description: "胸腔轻微扩张，开始吸气"},
			{Index: 2, Description: "呼吸达到最高点，肩膀轻微上抬"},
			{Index: 3, Description: "保持呼吸最高点片刻"},
			{Index: 4, Description: "开始缓慢呼气，肩膀回落"},
			{Index: 5, Description: "呼吸回到中位，身体轻微放松"},
			{Index: 6, Description: "身体轻微自然摆动"},
			{Index: 7, Description: "回到起始站立姿态"},
		},
		MotionDescription:      "角色保持站立并进行自然轻微呼吸活动",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，双臂自然下垂，身体保持垂直",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色保持站立姿态，进行自然轻微呼吸",
		NegativePromptFragment: "多余人物、变形、肢体扭曲、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"idle_breathing": {
		ActionKey:  "idle_breathing",
		LoopType:   LoopTypeLoop,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立姿态，双臂自然下垂"},
			{Index: 1, Description: "缓慢吸气，胸腔轻微扩张"},
			{Index: 2, Description: "继续吸气，腹部轻微隆起"},
			{Index: 3, Description: "吸气达到最高点"},
			{Index: 4, Description: "保持最高点片刻"},
			{Index: 5, Description: "开始缓慢呼气"},
			{Index: 6, Description: "继续呼气回到中位"},
			{Index: 7, Description: "回到起始站立姿态"},
		},
		MotionDescription:      "角色保持站立并进行缓慢呼吸，胸腹有明显起伏",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，双臂自然下垂，胸腹随呼吸起伏",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色保持站立姿态，进行缓慢深呼吸",
		NegativePromptFragment: "多余人物、变形、肢体扭曲、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"idle_blink": {
		ActionKey:  "idle_blink",
		LoopType:   LoopTypeLoop,
		FrameCount: 4,
		FramePhases: []FramePhase{
			{Index: 0, Description: "眼睛完全睁开，自然站立"},
			{Index: 1, Description: "上眼睑开始下落"},
			{Index: 2, Description: "眼睛完全闭合"},
			{Index: 3, Description: "眼睛重新睁开回到起始状态"},
		},
		MotionDescription:      "角色自然眨眼，眼睛开合一个完整周期",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，仅眼部动作，身体保持静止",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色保持站立，自然眨眼一次",
		NegativePromptFragment: "多余人物、变形、眼球异常、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"idle_look_around": {
		ActionKey:  "idle_look_around",
		LoopType:   LoopTypeLoop,
		FrameCount: 12,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立，正视前方"},
			{Index: 1, Description: "头部开始向左转"},
			{Index: 2, Description: "继续向左转"},
			{Index: 3, Description: "头部转到左侧极限"},
			{Index: 4, Description: "在左侧停留观察"},
			{Index: 5, Description: "开始向右回转"},
			{Index: 6, Description: "经过正面回到中位"},
			{Index: 7, Description: "继续向右转"},
			{Index: 8, Description: "头部转到右侧极限"},
			{Index: 9, Description: "在右侧停留观察"},
			{Index: 10, Description: "开始向左回转"},
			{Index: 11, Description: "回到正视前方的起始姿态"},
		},
		MotionDescription:      "角色左右环顾四周，头部转动观察环境",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，身体保持垂直，仅头部转动",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色保持站立，头部左右转动环顾四周",
		NegativePromptFragment: "多余人物、变形、头部扭转过度、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"idle_sway": {
		ActionKey:  "idle_sway",
		LoopType:   LoopTypeLoop,
		FrameCount: 10,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立，身体居中"},
			{Index: 1, Description: "身体重心开始向左偏移"},
			{Index: 2, Description: "继续向左倾斜"},
			{Index: 3, Description: "到达左侧最大幅度"},
			{Index: 4, Description: "开始向右回正"},
			{Index: 5, Description: "经过中心向右偏移"},
			{Index: 6, Description: "继续向右倾斜"},
			{Index: 7, Description: "到达右侧最大幅度"},
			{Index: 8, Description: "开始向左回正"},
			{Index: 9, Description: "回到居中起始姿态"},
		},
		MotionDescription:      "角色身体轻微左右摇摆，重心周期性偏移",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，双脚不动，上半身左右摇摆",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色保持站立，身体轻微左右摇摆",
		NegativePromptFragment: "多余人物、变形、摇摆幅度过大、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"walk_left": {
		ActionKey:  "walk_left",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立，准备向左迈步"},
			{Index: 1, Description: "右腿抬起向左迈出"},
			{Index: 2, Description: "右脚落地，重心左移"},
			{Index: 3, Description: "左腿跟随抬起"},
			{Index: 4, Description: "左脚向左迈出落地"},
			{Index: 5, Description: "右腿再次抬起"},
			{Index: 6, Description: "右脚落地继续行进"},
			{Index: 7, Description: "回到站立姿态，完成一个步幅"},
		},
		MotionDescription:      "角色向左侧行走，双腿交替迈步移动",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面朝向镜头，双腿交替迈步，身体随步伐轻微起伏",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色向左侧迈步行走，步态自然",
		NegativePromptFragment: "多余人物、变形、滑步、肢体扭曲、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"walk_right": {
		ActionKey:  "walk_right",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立，准备向右迈步"},
			{Index: 1, Description: "左腿抬起向右迈出"},
			{Index: 2, Description: "左脚落地，重心右移"},
			{Index: 3, Description: "右腿跟随抬起"},
			{Index: 4, Description: "右脚向右迈出落地"},
			{Index: 5, Description: "左腿再次抬起"},
			{Index: 6, Description: "左脚落地继续行进"},
			{Index: 7, Description: "回到站立姿态，完成一个步幅"},
		},
		MotionDescription:      "角色向右侧行走，双腿交替迈步移动",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面朝向镜头，双腿交替迈步，身体随步伐轻微起伏",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色向右侧迈步行走，步态自然",
		NegativePromptFragment: "多余人物、变形、滑步、肢体扭曲、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"run_left": {
		ActionKey:  "run_left",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始奔跑预备，身体前倾"},
			{Index: 1, Description: "右腿大力蹬地向左"},
			{Index: 2, Description: "身体腾空，右腿前摆"},
			{Index: 3, Description: "左脚落地缓冲"},
			{Index: 4, Description: "左腿蹬地发力"},
			{Index: 5, Description: "身体再次腾空，左腿前摆"},
			{Index: 6, Description: "右脚落地缓冲"},
			{Index: 7, Description: "回到奔跑预备姿态"},
		},
		MotionDescription:      "角色向左侧快速奔跑，步伐大且有腾空阶段",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面朝向镜头，身体前倾，双臂随奔跑摆动，双腿大幅交替",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色向左侧快速奔跑，动作敏捷有力",
		NegativePromptFragment: "多余人物、变形、滑步、肢体扭曲、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"run_right": {
		ActionKey:  "run_right",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始奔跑预备，身体前倾"},
			{Index: 1, Description: "左腿大力蹬地向右"},
			{Index: 2, Description: "身体腾空，左腿前摆"},
			{Index: 3, Description: "右脚落地缓冲"},
			{Index: 4, Description: "右腿蹬地发力"},
			{Index: 5, Description: "身体再次腾空，右腿前摆"},
			{Index: 6, Description: "左脚落地缓冲"},
			{Index: 7, Description: "回到奔跑预备姿态"},
		},
		MotionDescription:      "角色向右侧快速奔跑，步伐大且有腾空阶段",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面朝向镜头，身体前倾，双臂随奔跑摆动，双腿大幅交替",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色向右侧快速奔跑，动作敏捷有力",
		NegativePromptFragment: "多余人物、变形、滑步、肢体扭曲、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"jump": {
		ActionKey:  "jump",
		LoopType:   LoopTypeOnce,
		FrameCount: 10,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立，准备起跳"},
			{Index: 1, Description: "双腿弯曲下蹲蓄力"},
			{Index: 2, Description: "继续下蹲到最低点"},
			{Index: 3, Description: "双腿蹬地发力开始上升"},
			{Index: 4, Description: "身体腾空上升中"},
			{Index: 5, Description: "到达跳跃最高点"},
			{Index: 6, Description: "开始下落"},
			{Index: 7, Description: "继续下落接近地面"},
			{Index: 8, Description: "双脚触地开始缓冲"},
			{Index: 9, Description: "回到站立姿态"},
		},
		MotionDescription:      "角色向上跳起，包含蓄力、腾空和落地缓冲完整过程",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面朝向镜头，下蹲蓄力后双腿蹬地，双臂上摆辅助起跳",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色原地向上跳跃，先下蹲蓄力再蹬地腾空",
		NegativePromptFragment: "多余人物、变形、悬浮、肢体扭曲、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"land": {
		ActionKey:  "land",
		LoopType:   LoopTypeOnce,
		FrameCount: 6,
		FramePhases: []FramePhase{
			{Index: 0, Description: "身体在空中下落"},
			{Index: 1, Description: "双脚触地瞬间"},
			{Index: 2, Description: "双腿弯曲缓冲冲击"},
			{Index: 3, Description: "继续下蹲到最低点"},
			{Index: 4, Description: "开始起身"},
			{Index: 5, Description: "回到稳定站立姿态"},
		},
		MotionDescription:      "角色从空中落地，含触地缓冲和起身恢复",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面朝向镜头，双脚触地后双腿弯曲缓冲，双臂维持平衡",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色从空中下落并稳定落地，双腿弯曲缓冲",
		NegativePromptFragment: "多余人物、变形、穿模、肢体扭曲、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"turn_around": {
		ActionKey:  "turn_around",
		LoopType:   LoopTypeOnce,
		FrameCount: 6,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始正面对着镜头"},
			{Index: 1, Description: "开始转身，肩膀转动"},
			{Index: 2, Description: "转过四分之一"},
			{Index: 3, Description: "转到侧面九十度"},
			{Index: 4, Description: "继续转动接近完成"},
			{Index: 5, Description: "完成转身面向另一侧"},
		},
		MotionDescription:      "角色转身面向另一侧，身体旋转一百八十度",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "以身体中轴为轴心旋转，双脚原地不动，上半身带动转动",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色原地转身，面向另一侧",
		NegativePromptFragment: "多余人物、变形、位移过大、肢体扭曲、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"wave": {
		ActionKey:  "wave",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立，右臂自然下垂"},
			{Index: 1, Description: "右臂抬起至肩部高度"},
			{Index: 2, Description: "前臂展开，手掌朝前"},
			{Index: 3, Description: "手掌向左挥动"},
			{Index: 4, Description: "手掌向右挥动"},
			{Index: 5, Description: "手掌再次向左挥动"},
			{Index: 6, Description: "手掌回到中间位置"},
			{Index: 7, Description: "手臂放下回到起始姿态"},
		},
		MotionDescription:      "角色抬起右臂挥手致意，手掌左右摆动",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，右臂抬起至肩部以上，手掌朝前左右摆动，左臂自然下垂",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色抬起右手挥手致意，手掌左右摆动",
		NegativePromptFragment: "多余人物、变形、手臂扭曲、多余手指、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"nod": {
		ActionKey:  "nod",
		LoopType:   LoopTypeOnce,
		FrameCount: 4,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始正视前方"},
			{Index: 1, Description: "头部开始向下点"},
			{Index: 2, Description: "头部点到最低点"},
			{Index: 3, Description: "头部抬起回到正视前方"},
		},
		MotionDescription:      "角色头部上下点动一次表示肯定",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，仅头部上下运动，身体保持静止",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色点头一次表示肯定，头部上下运动",
		NegativePromptFragment: "多余人物、变形、头部扭转、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"shake_head": {
		ActionKey:  "shake_head",
		LoopType:   LoopTypeOnce,
		FrameCount: 4,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始正视前方"},
			{Index: 1, Description: "头部转向左侧"},
			{Index: 2, Description: "头部转向右侧"},
			{Index: 3, Description: "头部回到正视前方"},
		},
		MotionDescription:      "角色头部左右摇动一次表示否定",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，仅头部左右运动，身体保持静止",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色摇头一次表示否定，头部左右运动",
		NegativePromptFragment: "多余人物、变形、头部扭转过度、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"clap": {
		ActionKey:  "clap",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立，双手在胸前分开"},
			{Index: 1, Description: "双手开始合拢"},
			{Index: 2, Description: "双手掌心相击"},
			{Index: 3, Description: "双手分开"},
			{Index: 4, Description: "双手再次合拢"},
			{Index: 5, Description: "双手掌心相击"},
			{Index: 6, Description: "双手分开"},
			{Index: 7, Description: "双手放下回到起始姿态"},
		},
		MotionDescription:      "角色双手在胸前合拢拍击鼓掌，连续两次",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，双手举至胸前，掌心相对反复合拢分开",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色双手在胸前拍手鼓掌，掌心反复相击",
		NegativePromptFragment: "多余人物、变形、手臂扭曲、多余手指、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"point": {
		ActionKey:  "point",
		LoopType:   LoopTypeOnce,
		FrameCount: 6,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立，右臂下垂"},
			{Index: 1, Description: "右臂抬起，前臂弯曲"},
			{Index: 2, Description: "食指伸出，开始指向"},
			{Index: 3, Description: "手臂完全伸展指向目标"},
			{Index: 4, Description: "保持指向姿态"},
			{Index: 5, Description: "手臂收回回到起始姿态"},
		},
		MotionDescription:      "角色抬起右臂用食指指向某处并收回",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，右臂抬起伸展，食指指向前方，其余手指收拢",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色抬起右手用食指指向前方目标",
		NegativePromptFragment: "多余人物、变形、手臂扭曲、多余手指、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"stretch": {
		ActionKey:  "stretch",
		LoopType:   LoopTypeOnce,
		FrameCount: 10,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立"},
			{Index: 1, Description: "双臂开始上举"},
			{Index: 2, Description: "双臂继续上举"},
			{Index: 3, Description: "双臂举到最高点，身体伸展"},
			{Index: 4, Description: "保持伸展状态"},
			{Index: 5, Description: "上半身轻微后仰"},
			{Index: 6, Description: "保持后仰伸展"},
			{Index: 7, Description: "身体开始回正"},
			{Index: 8, Description: "双臂开始下落"},
			{Index: 9, Description: "回到起始站立姿态"},
		},
		MotionDescription:      "角色双臂上举伸展身体，含后仰和恢复",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，双臂上举至头顶上方，身体后仰伸展",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色双臂上举伸懒腰，身体向后伸展",
		NegativePromptFragment: "多余人物、变形、手臂扭曲、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"bow": {
		ActionKey:  "bow",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立"},
			{Index: 1, Description: "上半身开始前倾"},
			{Index: 2, Description: "继续前倾弯腰"},
			{Index: 3, Description: "弯腰到最低点"},
			{Index: 4, Description: "保持鞠躬姿态"},
			{Index: 5, Description: "开始起身"},
			{Index: 6, Description: "继续起身"},
			{Index: 7, Description: "回到站立起始姿态"},
		},
		MotionDescription:      "角色上半身前倾弯腰鞠躬后起身恢复",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，以腰部为轴上半身前倾，双臂自然下垂或贴于身侧",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色弯腰鞠躬，上半身前倾后起身",
		NegativePromptFragment: "多余人物、变形、弯腰过度、肢体扭曲、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"happy": {
		ActionKey:  "happy",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始自然表情"},
			{Index: 1, Description: "嘴角开始上扬"},
			{Index: 2, Description: "笑容展开，眼睛微眯"},
			{Index: 3, Description: "笑容达到最大，眼睛弯成月牙"},
			{Index: 4, Description: "保持开心笑容"},
			{Index: 5, Description: "身体轻微上跃表达喜悦"},
			{Index: 6, Description: "双手轻微握拳上举"},
			{Index: 7, Description: "回到带笑的起始姿态"},
		},
		MotionDescription:      "角色露出开心笑容，身体轻微上跃，双手握拳上举",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，嘴角上扬露出笑容，眼睛弯成月牙，身体轻微上跃",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色表现出开心的样子，笑容灿烂，身体欢快",
		NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏、牙齿异常",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"excited": {
		ActionKey:  "excited",
		LoopType:   LoopTypeOnce,
		FrameCount: 10,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立"},
			{Index: 1, Description: "双臂开始上举，表情兴奋"},
			{Index: 2, Description: "双手举高，张大嘴巴欢呼"},
			{Index: 3, Description: "双手挥动"},
			{Index: 4, Description: "身体轻微跳跃"},
			{Index: 5, Description: "继续挥动双手"},
			{Index: 6, Description: "再次跳跃"},
			{Index: 7, Description: "双手继续挥动"},
			{Index: 8, Description: "兴奋表情减弱"},
			{Index: 9, Description: "回到起始站立姿态"},
		},
		MotionDescription:      "角色高举双手欢呼跳跃，表达强烈兴奋情绪",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，双臂高举挥动，张大嘴巴，身体跳跃",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色表现出兴奋的样子，高举双手欢呼跳跃",
		NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏、肢体扭曲",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"shy": {
		ActionKey:  "shy",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始自然表情"},
			{Index: 1, Description: "脸颊开始泛红"},
			{Index: 2, Description: "双手开始抬起"},
			{Index: 3, Description: "双手捂住脸颊"},
			{Index: 4, Description: "身体轻微扭动"},
			{Index: 5, Description: "眼神躲闪向侧方"},
			{Index: 6, Description: "继续保持害羞姿态"},
			{Index: 7, Description: "回到带红晕的起始姿态"},
		},
		MotionDescription:      "角色脸颊泛红，双手捂脸，身体扭动，眼神躲闪",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，脸颊泛红，双手捂住脸颊，身体轻微扭动",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色表现出害羞的样子，脸颊泛红双手捂脸",
		NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏、手势异常",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"sad": {
		ActionKey:  "sad",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始自然表情"},
			{Index: 1, Description: "嘴角开始下垂"},
			{Index: 2, Description: "眉头紧锁，眼神低垂"},
			{Index: 3, Description: "头部低下"},
			{Index: 4, Description: "双肩下沉"},
			{Index: 5, Description: "身体微微蜷缩"},
			{Index: 6, Description: "保持低落姿态"},
			{Index: 7, Description: "回到难过的起始姿态"},
		},
		MotionDescription:      "角色嘴角下垂眉头紧锁，头部低垂双肩下沉",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，嘴角下垂，眉头紧锁，头部低垂，双肩下沉",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色表现出难过的样子，嘴角下垂眼神低垂",
		NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏、眼泪位置异常",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"cry": {
		ActionKey:  "cry",
		LoopType:   LoopTypeOnce,
		FrameCount: 10,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始自然表情"},
			{Index: 1, Description: "眼眶开始泛红"},
			{Index: 2, Description: "眼泪开始在眼眶聚集"},
			{Index: 3, Description: "第一滴眼泪滑落"},
			{Index: 4, Description: "嘴角下垂开始抽泣"},
			{Index: 5, Description: "用手背擦拭眼泪"},
			{Index: 6, Description: "继续抽泣"},
			{Index: 7, Description: "眼泪继续流淌"},
			{Index: 8, Description: "抽泣减弱"},
			{Index: 9, Description: "回到带泪痕的起始姿态"},
		},
		MotionDescription:      "角色眼眶泛红流泪哭泣，用手背擦拭眼泪并抽泣",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，眼眶泛红，眼泪滑落，用手背擦泪，嘴角下垂抽泣",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色流泪哭泣，眼泪滑落并用双手擦拭",
		NegativePromptFragment: "多余人物、变形、眼泪位置异常、面部崩坏、手势异常",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"angry": {
		ActionKey:  "angry",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始自然表情"},
			{Index: 1, Description: "眉头开始紧锁"},
			{Index: 2, Description: "眉毛下压，眼神凌厉"},
			{Index: 3, Description: "嘴唇紧抿"},
			{Index: 4, Description: "咬牙切齿"},
			{Index: 5, Description: "双拳握紧"},
			{Index: 6, Description: "身体前倾表达怒意"},
			{Index: 7, Description: "回到愤怒的起始姿态"},
		},
		MotionDescription:      "角色眉头紧锁眉毛下压，双拳握紧身体前倾",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，眉头紧锁下压，嘴唇紧抿，双拳握紧，身体前倾",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色表现出愤怒的样子，眉头紧锁双拳握紧",
		NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏、肢体扭曲",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"surprised": {
		ActionKey:  "surprised",
		LoopType:   LoopTypeOnce,
		FrameCount: 6,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始自然表情"},
			{Index: 1, Description: "眼睛开始睁大"},
			{Index: 2, Description: "眼睛完全睁大，嘴巴微张"},
			{Index: 3, Description: "嘴巴张到最大"},
			{Index: 4, Description: "双手轻微抬起表达震惊"},
			{Index: 5, Description: "保持惊讶表情"},
		},
		MotionDescription:      "角色眼睛睁大嘴巴张开，双手抬起表达震惊",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，眼睛睁大，嘴巴张开，双手轻微抬起",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色表现出惊讶的样子，眼睛睁大嘴巴张开",
		NegativePromptFragment: "多余人物、变形、眼睛过大、嘴巴过大、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"confused": {
		ActionKey:  "confused",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始自然表情"},
			{Index: 1, Description: "一侧眉毛开始上挑"},
			{Index: 2, Description: "头部轻微歪斜"},
			{Index: 3, Description: "嘴角歪斜"},
			{Index: 4, Description: "眼神迷茫"},
			{Index: 5, Description: "抬手摸下巴思考"},
			{Index: 6, Description: "继续保持疑惑姿态"},
			{Index: 7, Description: "回到疑惑的起始姿态"},
		},
		MotionDescription:      "角色一侧眉毛上挑头部歪斜，抬手摸下巴表达疑惑",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，一侧眉毛上挑，头部轻微歪斜，抬手摸下巴",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色表现出疑惑的样子，歪头抬手摸下巴思考",
		NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏、手势异常",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"embarrassed": {
		ActionKey:  "embarrassed",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始自然表情"},
			{Index: 1, Description: "脸颊开始泛红"},
			{Index: 2, Description: "眼神开始躲闪"},
			{Index: 3, Description: "手抬到头后抓挠"},
			{Index: 4, Description: "嘴角勉强苦笑"},
			{Index: 5, Description: "身体轻微扭动"},
			{Index: 6, Description: "继续保持尴尬姿态"},
			{Index: 7, Description: "回到尴尬的起始姿态"},
		},
		MotionDescription:      "角色脸颊泛红眼神躲闪，手抬到头后抓挠，嘴角苦笑",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，脸颊泛红，眼神躲闪，手抬至头后，身体扭动",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色表现出尴尬的样子，脸颊泛红手抓后脑勺苦笑",
		NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏、手势异常",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"scared": {
		ActionKey:  "scared",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始自然表情"},
			{Index: 1, Description: "瞳孔开始收缩"},
			{Index: 2, Description: "身体开始后退"},
			{Index: 3, Description: "双臂抬起护在胸前"},
			{Index: 4, Description: "身体蜷缩"},
			{Index: 5, Description: "头部后仰"},
			{Index: 6, Description: "全身轻微颤抖"},
			{Index: 7, Description: "回到恐惧的起始姿态"},
		},
		MotionDescription:      "角色瞳孔收缩身体后退，双臂护胸身体蜷缩颤抖",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，瞳孔收缩，身体后退蜷缩，双臂护在胸前，全身颤抖",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色表现出害怕的样子，身体后退蜷缩双臂护胸",
		NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏、肢体扭曲",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"proud": {
		ActionKey:  "proud",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立"},
			{Index: 1, Description: "下巴开始抬起"},
			{Index: 2, Description: "双手叉腰"},
			{Index: 3, Description: "挺胸抬头"},
			{Index: 4, Description: "嘴角上扬露出得意笑容"},
			{Index: 5, Description: "保持得意姿态"},
			{Index: 6, Description: "眼神自信"},
			{Index: 7, Description: "回到得意的起始姿态"},
		},
		MotionDescription:      "角色下巴抬起双手叉腰，挺胸抬头露出得意笑容",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，下巴抬起，双手叉腰，挺胸抬头",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色表现出得意的样子，双手叉腰挺胸抬头",
		NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏、手势异常",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"tired": {
		ActionKey:  "tired",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立"},
			{Index: 1, Description: "双肩开始下沉"},
			{Index: 2, Description: "头部开始低垂"},
			{Index: 3, Description: "眼皮开始下垂"},
			{Index: 4, Description: "张嘴打哈欠"},
			{Index: 5, Description: "用手揉眼睛"},
			{Index: 6, Description: "身体微微佝偻"},
			{Index: 7, Description: "回到疲惫的起始姿态"},
		},
		MotionDescription:      "角色双肩下沉头部低垂，打哈欠揉眼，身体佝偻",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，双肩下沉，头部低垂，眼皮下垂，身体佝偻",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色表现出疲惫的样子，打哈欠揉眼睛双肩下沉",
		NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏、手势异常",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"sit": {
		ActionKey:  "sit",
		LoopType:   LoopTypeOnce,
		FrameCount: 6,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立"},
			{Index: 1, Description: "双腿开始弯曲"},
			{Index: 2, Description: "身体开始下降"},
			{Index: 3, Description: "接近坐姿"},
			{Index: 4, Description: "完全坐下"},
			{Index: 5, Description: "稳定坐姿"},
		},
		MotionDescription:      "角色从站立弯曲双腿下蹲至稳定坐姿",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面朝向，双腿弯曲，臀部贴近地面或座椅，上半身保持垂直",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色从站立变为坐下，双腿弯曲身体下降",
		NegativePromptFragment: "多余人物、变形、穿模、肢体扭曲、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"sleep": {
		ActionKey:  "sleep",
		LoopType:   LoopTypeOnce,
		FrameCount: 12,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立"},
			{Index: 1, Description: "开始弯腰"},
			{Index: 2, Description: "双手撑地"},
			{Index: 3, Description: "身体下降准备躺下"},
			{Index: 4, Description: "身体接近地面"},
			{Index: 5, Description: "完全躺下"},
			{Index: 6, Description: "闭眼进入睡眠"},
			{Index: 7, Description: "呼吸平稳起伏"},
			{Index: 8, Description: "轻微翻身"},
			{Index: 9, Description: "继续安稳睡眠"},
			{Index: 10, Description: "嘴角轻微活动"},
			{Index: 11, Description: "保持睡眠姿态"},
		},
		MotionDescription:      "角色弯腰躺下闭眼进入睡眠，呼吸平稳并轻微翻身",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "身体水平躺卧，双眼闭合，双手自然放置身侧或交叠",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色躺下睡觉，闭眼呼吸平稳进入睡眠",
		NegativePromptFragment: "多余人物、变形、穿模、肢体扭曲、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"wake_up": {
		ActionKey:  "wake_up",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "躺卧睡眠姿态"},
			{Index: 1, Description: "眼皮开始颤动"},
			{Index: 2, Description: "眼睛微微睁开"},
			{Index: 3, Description: "用手揉眼睛"},
			{Index: 4, Description: "开始撑起身体"},
			{Index: 5, Description: "上半身坐起"},
			{Index: 6, Description: "伸懒腰清醒"},
			{Index: 7, Description: "完全清醒的坐姿"},
		},
		MotionDescription:      "角色从躺卧睡眠中睁眼，揉眼撑起坐立伸懒腰清醒",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "从躺卧转为坐姿，眼皮颤动后睁眼，用手揉眼，上半身撑起",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色从睡眠中醒来，睁眼揉眼坐起伸懒腰",
		NegativePromptFragment: "多余人物、变形、穿模、肢体扭曲、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"eat": {
		ActionKey:  "eat",
		LoopType:   LoopTypeOnce,
		FrameCount: 10,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始坐姿或站姿"},
			{Index: 1, Description: "拿起食物"},
			{Index: 2, Description: "将食物送向嘴边"},
			{Index: 3, Description: "食物接近嘴巴"},
			{Index: 4, Description: "张嘴咬下食物"},
			{Index: 5, Description: "开始咀嚼"},
			{Index: 6, Description: "继续咀嚼"},
			{Index: 7, Description: "吞咽"},
			{Index: 8, Description: "满足表情"},
			{Index: 9, Description: "回到起始姿态"},
		},
		MotionDescription:      "角色拿起食物送至嘴边咬下，咀嚼吞咽后露出满足表情",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面朝向，一手拿起食物送至嘴边，张嘴咬下后咀嚼",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色进食，拿起食物送入嘴中咀嚼吞咽",
		NegativePromptFragment: "多余人物、变形、食物异常、手势异常、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"drink": {
		ActionKey:  "drink",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始姿态"},
			{Index: 1, Description: "拿起杯子"},
			{Index: 2, Description: "将杯子送向嘴边"},
			{Index: 3, Description: "杯子接触嘴唇"},
			{Index: 4, Description: "仰头饮水"},
			{Index: 5, Description: "继续饮水"},
			{Index: 6, Description: "放下杯子"},
			{Index: 7, Description: "回到起始姿态"},
		},
		MotionDescription:      "角色拿起杯子送至嘴边仰头饮水后放下杯子",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面朝向，一手拿起杯子送至嘴边，仰头饮水",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色喝水，拿起杯子送至嘴边仰头饮用",
		NegativePromptFragment: "多余人物、变形、杯子异常、手势异常、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"read": {
		ActionKey:  "read",
		LoopType:   LoopTypeOnce,
		FrameCount: 10,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始坐姿"},
			{Index: 1, Description: "拿起书本"},
			{Index: 2, Description: "翻开书本"},
			{Index: 3, Description: "将书本举到面前"},
			{Index: 4, Description: "开始阅读"},
			{Index: 5, Description: "眼神随文字移动"},
			{Index: 6, Description: "翻页"},
			{Index: 7, Description: "继续阅读"},
			{Index: 8, Description: "点头表示理解"},
			{Index: 9, Description: "继续保持阅读姿态"},
		},
		MotionDescription:      "角色拿起书本翻开阅读，翻页并点头表示理解",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "坐姿，双手捧书举至面前，眼神随文字移动",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色阅读书籍，双手捧书翻页阅读",
		NegativePromptFragment: "多余人物、变形、书本异常、手势异常、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"write": {
		ActionKey:  "write",
		LoopType:   LoopTypeOnce,
		FrameCount: 10,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始坐姿"},
			{Index: 1, Description: "拿起笔"},
			{Index: 2, Description: "笔尖接触纸面"},
			{Index: 3, Description: "开始书写"},
			{Index: 4, Description: "继续书写"},
			{Index: 5, Description: "抬笔思考"},
			{Index: 6, Description: "继续书写"},
			{Index: 7, Description: "书写中"},
			{Index: 8, Description: "停笔"},
			{Index: 9, Description: "检查书写内容"},
		},
		MotionDescription:      "角色拿起笔在纸面书写，抬笔思考后继续并检查",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "坐姿，一手执笔在纸面书写，另一手按住纸张",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色书写，拿笔在纸面上写字",
		NegativePromptFragment: "多余人物、变形、笔异常、手势异常、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"use_phone": {
		ActionKey:  "use_phone",
		LoopType:   LoopTypeOnce,
		FrameCount: 10,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始姿态"},
			{Index: 1, Description: "拿出手机"},
			{Index: 2, Description: "解锁屏幕"},
			{Index: 3, Description: "开始浏览"},
			{Index: 4, Description: "手指滑动屏幕"},
			{Index: 5, Description: "点击屏幕"},
			{Index: 6, Description: "继续浏览"},
			{Index: 7, Description: "打字输入"},
			{Index: 8, Description: "发送消息"},
			{Index: 9, Description: "继续使用手机"},
		},
		MotionDescription:      "角色拿出手机解锁浏览，滑动点击并打字发送消息",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面朝向，单手或双手持手机，手指在屏幕上滑动点击",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色使用手机，滑动屏幕浏览并打字输入",
		NegativePromptFragment: "多余人物、变形、手机异常、手势异常、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"work": {
		ActionKey:  "work",
		LoopType:   LoopTypeOnce,
		FrameCount: 10,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始坐姿"},
			{Index: 1, Description: "双手放在桌面"},
			{Index: 2, Description: "开始操作"},
			{Index: 3, Description: "专注工作中"},
			{Index: 4, Description: "敲击键盘"},
			{Index: 5, Description: "思考片刻"},
			{Index: 6, Description: "继续工作"},
			{Index: 7, Description: "翻阅资料"},
			{Index: 8, Description: "继续专注工作"},
			{Index: 9, Description: "保持工作姿态"},
		},
		MotionDescription:      "角色伏案专注工作，敲击键盘翻阅资料并思考",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "坐姿，身体前倾向桌面，双手操作键盘或翻阅资料",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色伏案工作，敲击键盘专注操作",
		NegativePromptFragment: "多余人物、变形、键盘异常、手势异常、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"study": {
		ActionKey:  "study",
		LoopType:   LoopTypeOnce,
		FrameCount: 10,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始坐姿"},
			{Index: 1, Description: "翻开书本"},
			{Index: 2, Description: "开始阅读"},
			{Index: 3, Description: "认真阅读"},
			{Index: 4, Description: "做笔记"},
			{Index: 5, Description: "继续阅读"},
			{Index: 6, Description: "思考问题"},
			{Index: 7, Description: "翻页继续"},
			{Index: 8, Description: "标记重点"},
			{Index: 9, Description: "保持学习姿态"},
		},
		MotionDescription:      "角色翻开书本阅读做笔记，思考翻页并标记重点",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "坐姿，一手翻书阅读，一手执笔做笔记",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色学习，翻书阅读并做笔记标记重点",
		NegativePromptFragment: "多余人物、变形、书本异常、手势异常、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"clicked": {
		ActionKey:  "clicked",
		LoopType:   LoopTypeOnce,
		FrameCount: 4,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立"},
			{Index: 1, Description: "受到点击惊讶反应"},
			{Index: 2, Description: "身体轻微后仰"},
			{Index: 3, Description: "回过神来恢复站立"},
		},
		MotionDescription:      "角色被鼠标点击后惊讶反应，身体后仰后恢复",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，被点击后身体轻微后仰，表情短暂惊讶",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色被点击，短暂惊讶后恢复站立",
		NegativePromptFragment: "多余人物、变形、反应过度、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"double_clicked": {
		ActionKey:  "double_clicked",
		LoopType:   LoopTypeOnce,
		FrameCount: 4,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立"},
			{Index: 1, Description: "第一次点击反应"},
			{Index: 2, Description: "第二次点击反应更强"},
			{Index: 3, Description: "恢复站立"},
		},
		MotionDescription:      "角色被鼠标双击后连续两次惊讶反应并恢复",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，连续两次被点击后身体后仰反应更强",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色被双击，连续两次惊讶后恢复",
		NegativePromptFragment: "多余人物、变形、反应过度、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"hovered": {
		ActionKey:  "hovered",
		LoopType:   LoopTypeOnce,
		FrameCount: 4,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立"},
			{Index: 1, Description: "注意到鼠标靠近"},
			{Index: 2, Description: "看向鼠标方向"},
			{Index: 3, Description: "保持注视"},
		},
		MotionDescription:      "角色注意到鼠标悬停，看向鼠标方向并保持注视",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，视线转向鼠标方向，表情略带好奇",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色被鼠标悬停，看向鼠标方向注视",
		NegativePromptFragment: "多余人物、变形、眼神异常、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"dragged": {
		ActionKey:  "dragged",
		LoopType:   LoopTypeOnce,
		FrameCount: 6,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立"},
			{Index: 1, Description: "被抓起的瞬间"},
			{Index: 2, Description: "身体悬空跟随移动"},
			{Index: 3, Description: "四肢下垂晃动"},
			{Index: 4, Description: "继续被拖动"},
			{Index: 5, Description: "保持悬空姿态"},
		},
		MotionDescription:      "角色被鼠标拖动悬空移动，四肢下垂晃动",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "身体悬空，四肢自然下垂晃动，表情略带不适",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色被拖动，悬空移动四肢下垂",
		NegativePromptFragment: "多余人物、变形、肢体扭曲、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"picked_up": {
		ActionKey:  "picked_up",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立"},
			{Index: 1, Description: "被抓住的瞬间"},
			{Index: 2, Description: "开始离开地面"},
			{Index: 3, Description: "身体上升"},
			{Index: 4, Description: "完全悬空"},
			{Index: 5, Description: "四肢自然下垂"},
			{Index: 6, Description: "轻微晃动"},
			{Index: 7, Description: "保持悬空姿态"},
		},
		MotionDescription:      "角色被提起离开地面，四肢自然下垂轻微晃动",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "身体悬空上升，四肢自然下垂，表情略带惊讶",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色被提起，身体上升悬空四肢下垂",
		NegativePromptFragment: "多余人物、变形、肢体扭曲、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"dropped": {
		ActionKey:  "dropped",
		LoopType:   LoopTypeOnce,
		FrameCount: 6,
		FramePhases: []FramePhase{
			{Index: 0, Description: "悬空姿态"},
			{Index: 1, Description: "开始下落"},
			{Index: 2, Description: "继续下落"},
			{Index: 3, Description: "双脚触地"},
			{Index: 4, Description: "双腿弯曲缓冲"},
			{Index: 5, Description: "恢复稳定站立"},
		},
		MotionDescription:      "角色从悬空被放下，下落后双脚触地缓冲恢复站立",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "从悬空下落，双脚触地后双腿弯曲缓冲，恢复站立",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色被放下，从悬空下落并稳定落地",
		NegativePromptFragment: "多余人物、变形、穿模、肢体扭曲、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"fall": {
		ActionKey:  "fall",
		LoopType:   LoopTypeOnce,
		FrameCount: 10,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始悬空或边缘姿态"},
			{Index: 1, Description: "开始失去平衡"},
			{Index: 2, Description: "身体开始下落"},
			{Index: 3, Description: "继续下落，四肢张开"},
			{Index: 4, Description: "加速下落"},
			{Index: 5, Description: "继续下落"},
			{Index: 6, Description: "接近地面"},
			{Index: 7, Description: "即将触地"},
			{Index: 8, Description: "双脚触地"},
			{Index: 9, Description: "趴在地上"},
		},
		MotionDescription:      "角色失去平衡向下掉落，四肢张开加速下坠后趴地",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "身体失去平衡下落，四肢张开，最终趴在地上",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色向下掉落，失去平衡四肢张开坠地",
		NegativePromptFragment: "多余人物、变形、悬浮、穿模、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"edge_sit": {
		ActionKey:  "edge_sit",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立"},
			{Index: 1, Description: "走向窗口边缘"},
			{Index: 2, Description: "转身背对边缘"},
			{Index: 3, Description: "开始坐下"},
			{Index: 4, Description: "双腿悬在边缘外侧"},
			{Index: 5, Description: "稳定坐姿"},
			{Index: 6, Description: "双手撑在边缘"},
			{Index: 7, Description: "保持坐在边缘的姿态"},
		},
		MotionDescription:      "角色走向窗口边缘转身坐下，双腿悬在外侧双手撑边",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "坐在窗口边缘，双腿悬在边缘外侧，双手撑在边缘",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色坐在窗口边缘，双腿悬空双手撑边",
		NegativePromptFragment: "多余人物、变形、穿模、肢体扭曲、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"edge_climb": {
		ActionKey:  "edge_climb",
		LoopType:   LoopTypeOnce,
		FrameCount: 10,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始在边缘下方"},
			{Index: 1, Description: "双手抓住边缘"},
			{Index: 2, Description: "开始向上攀爬"},
			{Index: 3, Description: "双臂发力引体向上"},
			{Index: 4, Description: "头部越过边缘"},
			{Index: 5, Description: "上半身翻过边缘"},
			{Index: 6, Description: "一条腿跨上边缘"},
			{Index: 7, Description: "继续翻越"},
			{Index: 8, Description: "接近完成攀爬"},
			{Index: 9, Description: "完成攀爬坐在边缘"},
		},
		MotionDescription:      "角色抓住窗口边缘引体向上攀爬翻越后坐在边缘",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "双手抓住边缘引体向上，头部和上半身翻越，腿部跨上",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色攀爬窗口边缘，引体向上翻越至边缘",
		NegativePromptFragment: "多余人物、变形、穿模、肢体扭曲、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"sleep_on_desktop": {
		ActionKey:  "sleep_on_desktop",
		LoopType:   LoopTypeOnce,
		FrameCount: 12,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始坐姿"},
			{Index: 1, Description: "开始疲倦打哈欠"},
			{Index: 2, Description: "双手交叠放在桌面"},
			{Index: 3, Description: "头部开始低下"},
			{Index: 4, Description: "头部靠在手上"},
			{Index: 5, Description: "闭眼入睡"},
			{Index: 6, Description: "进入浅睡眠"},
			{Index: 7, Description: "呼吸平稳起伏"},
			{Index: 8, Description: "进入深睡眠"},
			{Index: 9, Description: "轻微翻身"},
			{Index: 10, Description: "继续安稳睡眠"},
			{Index: 11, Description: "保持趴睡姿态"},
		},
		MotionDescription:      "角色疲倦打哈欠后双手交叠趴在桌面闭眼入睡",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "坐姿，双手交叠放在桌面，头部靠在手臂上闭眼",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色趴在桌面睡觉，双手交叠头部靠在手臂上闭眼",
		NegativePromptFragment: "多余人物、变形、穿模、肢体扭曲、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"listening": {
		ActionKey:  "listening",
		LoopType:   LoopTypeOnce,
		FrameCount: 6,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立"},
			{Index: 1, Description: "身体微微前倾"},
			{Index: 2, Description: "头部轻微歪向一侧"},
			{Index: 3, Description: "眼神专注注视对方"},
			{Index: 4, Description: "偶尔点头表示在听"},
			{Index: 5, Description: "保持倾听姿态"},
		},
		MotionDescription:      "角色身体前倾头部歪斜，眼神专注偶尔点头倾听对方",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，身体微微前倾，头部轻微歪斜，眼神专注",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色倾听对方说话，身体前倾眼神专注偶尔点头",
		NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"thinking": {
		ActionKey:  "thinking",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立"},
			{Index: 1, Description: "眉头开始微皱"},
			{Index: 2, Description: "抬手托住下巴"},
			{Index: 3, Description: "眼神向上看向侧方"},
			{Index: 4, Description: "保持思考姿态"},
			{Index: 5, Description: "偶尔点头"},
			{Index: 6, Description: "继续思考"},
			{Index: 7, Description: "保持思考姿态"},
		},
		MotionDescription:      "角色眉头微皱抬手托下巴，眼神上看侧方思考",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，一手托住下巴，眉头微皱，眼神看向侧上方",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色思考，抬手托下巴眉头微皱眼神看向侧方",
		NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏、手势异常",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"speaking": {
		ActionKey:  "speaking",
		LoopType:   LoopTypeOnce,
		FrameCount: 10,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立，闭嘴"},
			{Index: 1, Description: "嘴巴开始张开"},
			{Index: 2, Description: "嘴型变化发出第一个音节"},
			{Index: 3, Description: "嘴巴张到最大"},
			{Index: 4, Description: "嘴型变化发出另一个音节"},
			{Index: 5, Description: "嘴巴半开"},
			{Index: 6, Description: "嘴型再次变化"},
			{Index: 7, Description: "嘴巴接近闭合"},
			{Index: 8, Description: "嘴型变化收尾"},
			{Index: 9, Description: "嘴巴闭合回到起始"},
		},
		MotionDescription:      "角色嘴巴连续开合变化，模拟说话时嘴型运动",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，嘴巴随说话音节连续开合，嘴型变化自然",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色说话，嘴巴连续开合嘴型随音节变化",
		NegativePromptFragment: "多余人物、变形、嘴型异常、牙齿异常、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"agreeing": {
		ActionKey:  "agreeing",
		LoopType:   LoopTypeOnce,
		FrameCount: 6,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立"},
			{Index: 1, Description: "开始点头"},
			{Index: 2, Description: "头部点到最低"},
			{Index: 3, Description: "头部抬起"},
			{Index: 4, Description: "再次点头"},
			{Index: 5, Description: "带着赞同表情"},
		},
		MotionDescription:      "角色连续点头两次表示赞同，带着认可表情",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，头部连续上下点动，表情认可",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色表示赞同，连续点头表情认可",
		NegativePromptFragment: "多余人物、变形、头部扭转、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"disagreeing": {
		ActionKey:  "disagreeing",
		LoopType:   LoopTypeOnce,
		FrameCount: 6,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立"},
			{Index: 1, Description: "开始摇头"},
			{Index: 2, Description: "头部转到一侧"},
			{Index: 3, Description: "头部转到另一侧"},
			{Index: 4, Description: "再次摇头"},
			{Index: 5, Description: "带着不赞同表情"},
		},
		MotionDescription:      "角色连续摇头表示不赞同，带着否定表情",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，头部连续左右摇动，表情否定",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色表示不赞同，连续摇头表情否定",
		NegativePromptFragment: "多余人物、变形、头部扭转过度、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"waiting": {
		ActionKey:  "waiting",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立"},
			{Index: 1, Description: "双手交叠身前"},
			{Index: 2, Description: "身体轻微重心偏移"},
			{Index: 3, Description: "眼神看向侧方"},
			{Index: 4, Description: "轻微叹气"},
			{Index: 5, Description: "换个姿势"},
			{Index: 6, Description: "继续等待"},
			{Index: 7, Description: "保持等待姿态"},
		},
		MotionDescription:      "角色双手交叠身前安静等待，偶尔换姿势和叹气",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，双手交叠放在身前，身体轻微重心偏移",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色安静等待，双手交叠身前偶尔换姿势",
		NegativePromptFragment: "多余人物、变形、表情僵硬、面部崩坏、手势异常",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"greeting": {
		ActionKey:  "greeting",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立"},
			{Index: 1, Description: "看到对方露出笑容"},
			{Index: 2, Description: "右手抬起准备挥手"},
			{Index: 3, Description: "手掌向前挥手致意"},
			{Index: 4, Description: "继续挥手"},
			{Index: 5, Description: "身体轻微前倾"},
			{Index: 6, Description: "手臂收回"},
			{Index: 7, Description: "保持友好姿态"},
		},
		MotionDescription:      "角色看到对方露出笑容，抬手挥手致意后身体前倾",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，右手抬起挥手，露出笑容，身体轻微前倾",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色问候致意，抬手挥手露出笑容身体前倾",
		NegativePromptFragment: "多余人物、变形、手臂扭曲、多余手指、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
	"goodbye": {
		ActionKey:  "goodbye",
		LoopType:   LoopTypeOnce,
		FrameCount: 8,
		FramePhases: []FramePhase{
			{Index: 0, Description: "起始站立"},
			{Index: 1, Description: "抬起右手"},
			{Index: 2, Description: "手掌向前开始挥手"},
			{Index: 3, Description: "继续挥手告别"},
			{Index: 4, Description: "手掌左右摆动"},
			{Index: 5, Description: "继续挥手"},
			{Index: 6, Description: "手臂开始下落"},
			{Index: 7, Description: "回到站立姿态"},
		},
		MotionDescription:      "角色抬起右手挥手告别，手掌左右摆动后放下",
		CameraConstraint:       cameraConstraint,
		PoseConstraint:         "正面站立，右手抬起至肩部以上，手掌朝前左右摆动",
		ContinuityConstraint:   continuityConstraint,
		PromptFragment:         "角色告别，抬手挥手手掌左右摆动",
		NegativePromptFragment: "多余人物、变形、手臂扭曲、多余手指、面部崩坏",
		GenerationStrategy:     StrategySequentialFrames,
		Version:                1,
	},
}
