package contacts

const (
	ErrContactsUnsupported               = "CONTACTS_UNSUPPORTED"
	ErrPermissionNotDetermined           = "CONTACTS_PERMISSION_NOT_DETERMINED"
	ErrPermissionDenied                  = "CONTACTS_PERMISSION_DENIED"
	ErrPermissionRestricted              = "CONTACTS_PERMISSION_RESTRICTED"
	ErrNotFoundOrNotAccessible           = "CONTACTS_NOT_FOUND_OR_NOT_ACCESSIBLE"
	ErrInvalidQuery                      = "CONTACTS_INVALID_QUERY"
	ErrInvalidContactID                  = "CONTACTS_INVALID_CONTACT_ID"
	ErrInvalidSearchField                = "CONTACTS_INVALID_SEARCH_FIELD"
	ErrInvalidName                       = "CONTACTS_INVALID_NAME"
	ErrInvalidPhone                      = "CONTACTS_INVALID_PHONE"
	ErrInvalidEmail                      = "CONTACTS_INVALID_EMAIL"
	ErrInvalidAddress                    = "CONTACTS_INVALID_ADDRESS"
	ErrInvalidDate                       = "CONTACTS_INVALID_DATE"
	ErrContainerNotFound                 = "CONTACTS_CONTAINER_NOT_FOUND"
	ErrContainerReadOnly                 = "CONTACTS_CONTAINER_READ_ONLY"
	ErrReadOnly                          = "CONTACTS_READ_ONLY"
	ErrCreateFailed                      = "CONTACTS_CREATE_FAILED"
	ErrUpdateFailed                      = "CONTACTS_UPDATE_FAILED"
	ErrDeleteFailed                      = "CONTACTS_DELETE_FAILED"
	ErrPhotoInvalid                      = "CONTACTS_PHOTO_INVALID"
	ErrPhotoTooLarge                     = "CONTACTS_PHOTO_TOO_LARGE"
	ErrNotesEntitlementRequired          = "CONTACTS_NOTES_ENTITLEMENT_REQUIRED"
	ErrOperationTimeout                  = "CONTACTS_OPERATION_TIMEOUT"
	ErrCancelled                         = "CONTACTS_CANCELLED"
	ErrOutcomeUnknown                    = "CONTACTS_OUTCOME_UNKNOWN"
	ErrNativeBridgeUnavailable           = "CONTACTS_NATIVE_BRIDGE_UNAVAILABLE"
	ErrInvalidResponse                   = "CONTACTS_INVALID_RESPONSE"
)
