package root

const (
	ROOT_UNSUPPORTED          = "ROOT_UNSUPPORTED"
	ROOT_NOT_AVAILABLE        = "ROOT_NOT_AVAILABLE"
	ROOT_NOT_GRANTED          = "ROOT_NOT_GRANTED"
	ROOT_DENIED               = "ROOT_DENIED"
	ROOT_REQUEST_FAILED       = "ROOT_REQUEST_FAILED"
	ROOT_EXECUTION_FAILED     = "ROOT_EXECUTION_FAILED"
	ROOT_TIMEOUT              = "ROOT_TIMEOUT"
	ROOT_CANCELLED            = "ROOT_CANCELLED"
	ROOT_COMMAND_NOT_ALLOWED  = "ROOT_COMMAND_NOT_ALLOWED"
	ROOT_INVALID_ARGUMENT     = "ROOT_INVALID_ARGUMENT"
	ROOT_INPUT_TOO_LARGE      = "ROOT_INPUT_TOO_LARGE"
	ROOT_OUTPUT_TOO_LARGE     = "ROOT_OUTPUT_TOO_LARGE"
	ROOT_BRIDGE_UNAVAILABLE   = "ROOT_BRIDGE_UNAVAILABLE"
	ROOT_INVALID_RESPONSE     = "ROOT_INVALID_RESPONSE"
)

func MapRootErrorToCanonical(code string) string {
	switch code {
	case ROOT_UNSUPPORTED:
		return "PLATFORM_NOT_SUPPORTED"
	case ROOT_NOT_AVAILABLE:
		return "PROVIDER_UNAVAILABLE"
	case ROOT_NOT_GRANTED:
		return "AUTHORIZATION_DENIED"
	case ROOT_DENIED:
		return "AUTHORIZATION_DENIED"
	case ROOT_REQUEST_FAILED:
		return "USER_ACTION_REQUIRED"
	case ROOT_EXECUTION_FAILED:
		return "PROVIDER_UNAVAILABLE"
	case ROOT_TIMEOUT:
		return "BRIDGE_TIMEOUT"
	case ROOT_CANCELLED:
		return "CANCELLED"
	case ROOT_COMMAND_NOT_ALLOWED:
		return "AUTHORIZATION_DENIED"
	case ROOT_INVALID_ARGUMENT:
		return "AUTHORIZATION_DENIED"
	case ROOT_INPUT_TOO_LARGE, ROOT_OUTPUT_TOO_LARGE:
		return "BRIDGE_INVALID_RESPONSE"
	case ROOT_BRIDGE_UNAVAILABLE:
		return "PROVIDER_UNAVAILABLE"
	case ROOT_INVALID_RESPONSE:
		return "BRIDGE_INVALID_RESPONSE"
	default:
		return "PROVIDER_UNAVAILABLE"
	}
}

func MapRootPolicyError(code string) string {
	switch code {
	case ROOT_COMMAND_NOT_ALLOWED:
		return "AUTHORIZATION_DENIED"
	case ROOT_INVALID_ARGUMENT:
		return "AUTHORIZATION_DENIED"
	case ROOT_INPUT_TOO_LARGE, ROOT_OUTPUT_TOO_LARGE:
		return "BRIDGE_INVALID_RESPONSE"
	default:
		return "AUTHORIZATION_DENIED"
	}
}
