package iosnative

const (
	HEALTHKIT_UNAVAILABLE         = "HEALTHKIT_UNAVAILABLE"
	HEALTH_AUTHORIZATION_REQUIRED = "HEALTH_AUTHORIZATION_REQUIRED"
	HEALTH_TYPE_UNSUPPORTED       = "HEALTH_TYPE_UNSUPPORTED"
	HEALTH_QUERY_INVALID          = "HEALTH_QUERY_INVALID"
	HEALTH_QUERY_FAILED           = "HEALTH_QUERY_FAILED"
	HEALTH_WRITE_NOT_ENABLED      = "HEALTH_WRITE_NOT_ENABLED"
	HEALTH_WRITE_FAILED           = "HEALTH_WRITE_FAILED"
	HEALTH_DATA_NOT_AVAILABLE     = "HEALTH_DATA_NOT_AVAILABLE"
	NATIVE_BRIDGE_UNAVAILABLE     = "NATIVE_BRIDGE_UNAVAILABLE"
)

const (
	PermissionIOSHealthRead  = "platform.ios.health.read"
	PermissionIOSHealthWrite = "platform.ios.health.write"
)
