package reminders

const (
	ErrRemindersUnsupported          = "REMINDERS_UNSUPPORTED"
	ErrPermissionNotDetermined       = "REMINDERS_PERMISSION_NOT_DETERMINED"
	ErrPermissionDenied              = "REMINDERS_PERMISSION_DENIED"
	ErrPermissionRestricted          = "REMINDERS_PERMISSION_RESTRICTED"
	ErrFullAccessRequired            = "REMINDERS_FULL_ACCESS_REQUIRED"
	ErrDefaultListUnavailable        = "REMINDERS_DEFAULT_LIST_UNAVAILABLE"
	ErrListNotFound                  = "REMINDERS_LIST_NOT_FOUND"
	ErrListReadOnly                  = "REMINDERS_LIST_READ_ONLY"
	ErrReminderNotFound              = "REMINDERS_NOT_FOUND"
	ErrReminderTypeMismatch          = "REMINDERS_ITEM_TYPE_MISMATCH"
	ErrReminderNotEditable           = "REMINDERS_NOT_EDITABLE"
	ErrInvalidDateRange              = "REMINDERS_INVALID_DATE_RANGE"
	ErrQueryRangeTooLarge            = "REMINDERS_QUERY_RANGE_TOO_LARGE"
	ErrInvalidTimezone               = "REMINDERS_INVALID_TIMEZONE"
	ErrInvalidPriority               = "REMINDERS_INVALID_PRIORITY"
	ErrInvalidRecurrence             = "REMINDERS_INVALID_RECURRENCE"
	ErrInvalidURL                    = "REMINDERS_INVALID_URL"
	ErrNotesTooLong                  = "REMINDERS_NOTES_TOO_LONG"
	ErrTitleEmpty                    = "REMINDERS_TITLE_EMPTY"
	ErrTitleTooLong                  = "REMINDERS_TITLE_TOO_LONG"
	ErrNativeBridgeUnavailable       = "REMINDERS_NATIVE_BRIDGE_UNAVAILABLE"
	ErrEventKitFailed                = "REMINDERS_EVENTKIT_FAILED"
	ErrTimeout                       = "REMINDERS_TIMEOUT"
	ErrCancelled                     = "REMINDERS_CANCELLED"
	ErrInvalidResponse               = "REMINDERS_INVALID_RESPONSE"
	ErrOutcomeUnknown                = "REMINDERS_OUTCOME_UNKNOWN"
)
