org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=GBK -Dsun.jnu.encoding=GBK -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
android.useAndroidX=true
android.nonTransitiveRClass=true
android.overridePathCheck=true
kotlin.code.style=official
ksp.useKSP2=false
