package desktop

import "errors"

var (
	ErrInvalidContractID         = errors.New("desktop: invalid contract id")
	ErrContractNotFound          = errors.New("desktop: contract not found")
	ErrContractVersionNotFound   = errors.New("desktop: contract version not found")
	ErrContractFrozen            = errors.New("desktop: contract is frozen")
	ErrInvalidDefinition         = errors.New("desktop: invalid contribution definition")
	ErrContributionExists        = errors.New("desktop: contribution already exists")
	ErrContributionNotFound      = errors.New("desktop: contribution not found")
	ErrInvalidMenuTarget         = errors.New("desktop: invalid menu target")
	ErrInvalidTrayTarget         = errors.New("desktop: invalid tray target")
	ErrInvalidShortcut           = errors.New("desktop: invalid shortcut")
	ErrInvalidAccelerator        = errors.New("desktop: invalid accelerator")
	ErrReservedShortcut          = errors.New("desktop: reserved shortcut")
	ErrShortcutConflict          = errors.New("desktop: shortcut conflict")
	ErrShortcutExists            = errors.New("desktop: shortcut already exists")
	ErrMenuConflict              = errors.New("desktop: menu contribution id conflict")
	ErrTrayConflict              = errors.New("desktop: tray contribution id conflict")
	ErrActionConflict            = errors.New("desktop: action id conflict")
	ErrInvalidActionType         = errors.New("desktop: invalid action type")
	ErrForbiddenActionType       = errors.New("desktop: forbidden action type")
	ErrInvalidOrder              = errors.New("desktop: invalid order definition")
	ErrInvalidVisibility         = errors.New("desktop: invalid visibility rule")
	ErrInvalidIconResource       = errors.New("desktop: invalid icon resource")
	ErrSnapshotBuildFailed       = errors.New("desktop: snapshot build failed")
	ErrSnapshotApplyFailed       = errors.New("desktop: snapshot apply failed")
	ErrSnapshotConflict          = errors.New("desktop: snapshot conflict")
	ErrPermissionDenied          = errors.New("desktop: permission denied")
	ErrScopeDenied               = errors.New("desktop: scope denied")
	ErrResourceNotOwned          = errors.New("desktop: resource not owned")
	ErrHostNotReady              = errors.New("desktop: host not ready")
	ErrInvalidPlatform           = errors.New("desktop: invalid platform")
	ErrUnsupportedPlatform       = errors.New("desktop: unsupported platform")
	ErrCircuitOpen               = errors.New("desktop: circuit breaker open")
	ErrQuarantined               = errors.New("desktop: contribution quarantined")
	ErrGeneration                = errors.New("desktop: generation mismatch")
	ErrInvalidScope              = errors.New("desktop: invalid scope")
	ErrInvalidPermissionReq      = errors.New("desktop: invalid permission requirement")
	ErrDependencyNotMet          = errors.New("desktop: dependency not met")
	ErrInvalidConflictResolution = errors.New("desktop: invalid conflict resolution")
	ErrTooManyItems              = errors.New("desktop: too many items")
	ErrSeparatorNotAllowed       = errors.New("desktop: separator not allowed for third-party")
	ErrRadioGroupViolation       = errors.New("desktop: radio must be within own extension group")
)
