export const IPC_CHANNELS = {
  getEnvironment: "amitia:environment:get",
  getDeploymentConfig: "amitia:deployment:get",
  saveDeploymentConfig: "amitia:deployment:save",
  getRuntimeStatus: "amitia:runtime:status",
  openLogsDirectory: "amitia:logs:open",
  minimizeWindow: "amitia:window:minimize",
  toggleMaximizeWindow: "amitia:window:toggle-maximize",
  closeWindow: "amitia:window:close",
  editCommand: "amitia:window:edit-command",
  runtimeStatusChanged: "amitia:runtime:status-changed",
  selectAgentSkillDirectory: "amitia:agent-skill:select-directory",
  selectMCPRoot: "amitia:mcp:select-root",
  selectWorkspaceDirectory: "amitia:workspace:select-directory",
  openPath: "amitia:path:open",
  selectExtensionPackage: "amitia:extension-package:select-file",
  saveExtensionPackage: "amitia:extension-package:save",
  getAutoLaunch: "amitia:auto-launch:get",
  setAutoLaunch: "amitia:auto-launch:set",
  autoLaunchChanged: "amitia:auto-launch:changed",
  clipboardReadText: "amitia:clipboard:read-text",
  clipboardWriteText: "amitia:clipboard:write-text",
  uiNavigate: "amitia:ui:navigate",
  getBackendAuthHeaders: "amitia:backend-auth:get-headers",
  publishLocalVoiceASRFinal: "amitia:workflow:voice-asr-final",
  openRealtimeCallWindow: "amitia:realtime-call:open",
  closeRealtimeCallWindow: "amitia:realtime-call:close",
  realtimeCallWindowClosed: "amitia:realtime-call:closed",
  meshGetStatus: "amitia:mesh:status:get",
  meshProvision: "amitia:mesh:provision",
  meshDeprovision: "amitia:mesh:deprovision",
  meshGetIdentity: "amitia:mesh:identity:get",
  meshPairingStatus: "amitia:mesh:pairing:status",
  meshCreatePairingOffer: "amitia:mesh:pairing:create-offer",
  meshCloudListDevices: "amitia:mesh:cloud:list-devices",
  meshCloudRevokeDevice: "amitia:mesh:cloud:revoke-device",
  meshCloudProbe: "amitia:mesh:cloud:probe",
  quitApp: "amitia:app:quit",
  zoomIn: "amitia:zoom:in",
  zoomOut: "amitia:zoom:out",
  zoomReset: "amitia:zoom:reset",
  getZoomFactor: "amitia:zoom:get-factor",
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
