package background

const (
	OperationStatus             = "background.status"
	OperationTaskRegister       = "background.task.register"
	OperationTaskSubmit         = "background.task.submit"
	OperationTaskCancel         = "background.task.cancel"
	OperationTaskCancelAll      = "background.task.cancel_all"
	OperationTaskGetPending     = "background.task.get_pending"
	OperationTaskProgress       = "background.task.progress"
	OperationTaskExpire         = "background.task.expire"
	OperationTaskComplete       = "background.task.complete"
	OperationTaskReconcile      = "background.task.reconcile"
	OperationRuntimeReadiness   = "background.runtime.readiness"
	OperationRuntimeEnsure      = "background.runtime.ensure"
	OperationCheckpointGet      = "background.checkpoint.get"
	OperationCheckpointSet      = "background.checkpoint.set"
	OperationCheckpointClear    = "background.checkpoint.clear"
	OperationBindingGet         = "background.binding.get"
	OperationFilePickImport     = "file.pick.import"
	OperationFilePickDirectory  = "file.pick.directory"
	OperationFileMountReauthorize = "file.mount.reauthorize"
	OperationFileAccessStat     = "file.access.stat"
	OperationFileAccessList     = "file.access.list"
	OperationFileAccessRead     = "file.access.read"
	OperationFileAccessWrite    = "file.access.write"
	OperationFileAccessMkdir    = "file.access.mkdir"
	OperationFileAccessRename   = "file.access.rename"
	OperationFileAccessMove     = "file.access.move"
	OperationFileAccessCopy     = "file.access.copy"
	OperationFileAccessDelete   = "file.access.delete"
	OperationFileExport         = "file.export"
	OperationFileMountGet       = "file.mount.get"
	OperationFileMountList      = "file.mount.list"
	OperationFileMountRemove    = "file.mount.remove"
	OperationFileGetCapabilities = "file.get_capabilities"
)
