package dataportability

import "errors"

var (
	ErrBackupUnavailable        = errors.New("BACKUP_UNAVAILABLE")
	ErrBackupScopeInvalid       = errors.New("BACKUP_SCOPE_INVALID")
	ErrBackupProfileInvalid     = errors.New("BACKUP_PROFILE_INVALID")
	ErrBackupDiskSpace          = errors.New("BACKUP_DISK_SPACE_INSUFFICIENT")
	ErrBackupSnapshotFailed     = errors.New("BACKUP_SQLITE_SNAPSHOT_FAILED")
	ErrBackupIntegrityFailed    = errors.New("BACKUP_SQLITE_INTEGRITY_FAILED")
	ErrBackupComponentFailed    = errors.New("BACKUP_COMPONENT_FAILED")
	ErrBackupResourceMissing    = errors.New("BACKUP_RESOURCE_MISSING")
	ErrBackupResourceChanged    = errors.New("BACKUP_RESOURCE_CHANGED")
	ErrBackupManifestInvalid    = errors.New("BACKUP_MANIFEST_INVALID")
	ErrBackupChecksumMismatch   = errors.New("BACKUP_CHECKSUM_MISMATCH")
	ErrBackupEncryptionFailed   = errors.New("BACKUP_ENCRYPTION_FAILED")
	ErrBackupPassphraseRequired = errors.New("BACKUP_PASSPHRASE_REQUIRED")
	ErrBackupVerifyFailed       = errors.New("BACKUP_VERIFY_FAILED")
	ErrBackupNotFound           = errors.New("BACKUP_NOT_FOUND")
	ErrBackupCompressionInvalid = errors.New("BACKUP_COMPRESSION_INVALID")

	ErrRestoreInvalid             = errors.New("RESTORE_BACKUP_INVALID")
	ErrRestoreFormatUnsupported   = errors.New("RESTORE_FORMAT_UNSUPPORTED")
	ErrRestoreSchemaUnsupported   = errors.New("RESTORE_SCHEMA_UNSUPPORTED")
	ErrRestoreDowngradeUnsupported = errors.New("RESTORE_DOWNGRADE_UNSUPPORTED")
	ErrRestorePreBackupFailed     = errors.New("RESTORE_PRE_BACKUP_FAILED")
	ErrRestoreQuiesceFailed       = errors.New("RESTORE_QUIESCE_FAILED")
	ErrRestoreStagingFailed       = errors.New("RESTORE_STAGING_FAILED")
	ErrRestoreDecryptFailed       = errors.New("RESTORE_DECRYPT_FAILED")
	ErrRestoreIntegrityFailed     = errors.New("RESTORE_SQLITE_INTEGRITY_FAILED")
	ErrRestoreMigrationFailed     = errors.New("RESTORE_MIGRATION_FAILED")
	ErrRestoreAtomicReplaceFailed = errors.New("RESTORE_ATOMIC_REPLACE_FAILED")
	ErrRestoreReconciliationPending = errors.New("RESTORE_RECONCILIATION_PENDING")
	ErrRestoreReauthorizationRequired = errors.New("RESTORE_REAUTHORIZATION_REQUIRED")
	ErrRestoreRollbackFailed      = errors.New("RESTORE_ROLLBACK_FAILED")
	ErrRestoreDiskSpace           = errors.New("RESTORE_DISK_SPACE_INSUFFICIENT")

	ErrImportPackageInvalid       = errors.New("IMPORT_PACKAGE_INVALID")
	ErrImportFormatUnsupported    = errors.New("IMPORT_FORMAT_UNSUPPORTED")
	ErrImportDatasetUnsupported   = errors.New("IMPORT_DATASET_UNSUPPORTED")
	ErrImportCollisionPolicyInvalid = errors.New("IMPORT_COLLISION_POLICY_INVALID")
	ErrImportCharacterConflict    = errors.New("IMPORT_CHARACTER_CONFLICT")
	ErrImportConversationScope    = errors.New("IMPORT_CONVERSATION_SCOPE_INVALID")
	ErrImportMessageRefInvalid    = errors.New("IMPORT_MESSAGE_REFERENCE_INVALID")
	ErrImportResourceHashMismatch = errors.New("IMPORT_RESOURCE_HASH_MISMATCH")
	ErrImportReauthorizationRequired = errors.New("IMPORT_REAUTHORIZATION_REQUIRED")
	ErrImportTransactionFailed    = errors.New("IMPORT_TRANSACTION_FAILED")
	ErrImportReconciliationPending = errors.New("IMPORT_RECONCILIATION_PENDING")
	ErrImportArchiveInvalid       = errors.New("IMPORT_ARCHIVE_INVALID")
	ErrImportStagingFailed        = errors.New("IMPORT_STAGING_FAILED")
)
