package devicecontrol

import (
	"encoding/json"
	"time"

	"github.com/u-ai/backend/internal/extension/kernel/capability"
)

type toolSpec struct {
	id, modelName, name, description, operation, permission string
	input, output                                           string
	risk                                                    capability.RiskLevel
	sideEffect                                              capability.SideEffectLevel
	approval, background, idempotent, retryable             bool
	timeout                                                 time.Duration
	maxOutput                                               int
}

func BuildTools() []capability.ToolDefinition {
	object := `{"type":"object","additionalProperties":true}`
	specs := []toolSpec{
		{id: "android.device.status", name: "Android Device Capability Status", description: "Inspect Android device automation capabilities and permission state without changing the device.", operation: OperationStatus, permission: "android.device.inspect", input: `{ "type":"object","properties":{},"additionalProperties":false }`, output: object, risk: capability.RiskLow, sideEffect: capability.SideEffectReadOnly, background: true, idempotent: true, retryable: true, timeout: 2 * time.Second, maxOutput: 8192},
		{id: "android.device.info", name: "Android Device Info", description: "Read bounded device, display, battery, memory and storage information for capability-aware automation scheduling.", operation: OperationInfo, permission: "android.device.inspect", input: `{ "type":"object","properties":{},"additionalProperties":false }`, output: object, risk: capability.RiskLow, sideEffect: capability.SideEffectReadOnly, background: true, idempotent: true, retryable: true, timeout: 3 * time.Second, maxOutput: 8192},
		{id: "android.input.global_action", name: "Android Global Action", description: "Perform a typed Accessibility global action such as back, home, recents, notifications or quick settings.", operation: OperationGlobalAction, permission: "android.interaction.global", input: `{ "type":"object","required":["action"],"properties":{"action":{"type":"string","enum":["back","home","recents","notifications","quick_settings","power_dialog","lock_screen","take_screenshot"]}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectSystem, background: false, idempotent: false, timeout: 3 * time.Second, maxOutput: 2048},
		{id: "android.input.press_key", name: "Android Press Key", description: "Perform a typed device key action supported without arbitrary shell execution, including media and volume controls.", operation: OperationPressKey, permission: "android.interaction.global", input: `{ "type":"object","required":["key"],"properties":{"key":{"type":"string","enum":["volume_up","volume_down","mute","media_play_pause","media_next","media_previous"]}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectSystem, background: true, idempotent: false, timeout: 3 * time.Second, maxOutput: 2048},
		{id: "android.location.current", name: "Android Current Location", description: "Read the device's current or bounded fallback location when Android location permission is granted.", operation: OperationLocationCurrent, permission: "android.location.read", input: `{ "type":"object","properties":{"timeoutMs":{"type":"integer","minimum":500,"maximum":15000},"maxAgeMs":{"type":"integer","minimum":0,"maximum":86400000},"fresh":{"type":"boolean"}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectReadOnly, background: true, idempotent: true, retryable: true, timeout: 17 * time.Second, maxOutput: 4096},
		{id: "android.location.geofence.add", name: "Add Geofence", description: "Register a persistent platform geofence that emits workflow enter/exit device events and is restored after reboot.", operation: OperationGeofenceAdd, permission: "android.location.background", input: `{ "type":"object","required":["id","latitude","longitude"],"properties":{"id":{"type":"string","minLength":1,"maxLength":128,"pattern":"^[A-Za-z0-9._:-]+$"},"latitude":{"type":"number","minimum":-90,"maximum":90},"longitude":{"type":"number","minimum":-180,"maximum":180},"radiusMeters":{"type":"number","minimum":1,"maximum":100000},"expirationMs":{"type":"integer","minimum":-1,"maximum":31536000000}},"additionalProperties":false }`, output: object, risk: capability.RiskHigh, sideEffect: capability.SideEffectExternal, approval: true, background: true, idempotent: true, timeout: 8 * time.Second, maxOutput: 4096},
		{id: "android.location.geofence.remove", name: "Remove Geofence", description: "Remove a previously registered Amitia platform geofence.", operation: OperationGeofenceRemove, permission: "android.location.background", input: `{ "type":"object","required":["id"],"properties":{"id":{"type":"string","minLength":1,"maxLength":128}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectExternal, background: true, idempotent: true, timeout: 5 * time.Second, maxOutput: 2048},
		{id: "android.location.geofence.list", name: "List Geofences", description: "List Amitia-owned persistent geofence registrations.", operation: OperationGeofenceList, permission: "android.location.background", input: `{ "type":"object","properties":{},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectReadOnly, background: true, idempotent: true, timeout: 5 * time.Second, maxOutput: 16384},
		{id: "android.settings.get", name: "Android Get System Setting", description: "Read one Android system, secure or global setting by explicit namespace and key.", operation: OperationSettingsGet, permission: "android.settings.read", input: `{ "type":"object","required":["namespace","key"],"properties":{"namespace":{"type":"string","enum":["system","secure","global"]},"key":{"type":"string","minLength":1,"maxLength":128}},"additionalProperties":false }`, output: object, risk: capability.RiskLow, sideEffect: capability.SideEffectReadOnly, background: true, idempotent: true, retryable: true, timeout: 3 * time.Second, maxOutput: 4096},
		{id: "android.settings.set", name: "Android Set System Setting", description: "Modify one Android setting only when the platform has granted the required write privilege; never falls back to arbitrary shell.", operation: OperationSettingsSet, permission: "android.settings.write", input: `{ "type":"object","required":["namespace","key"],"properties":{"namespace":{"type":"string","enum":["system","secure","global"]},"key":{"type":"string","minLength":1,"maxLength":128},"value":{"type":["string","number","boolean","null"]}},"additionalProperties":false }`, output: object, risk: capability.RiskHigh, sideEffect: capability.SideEffectSystem, approval: true, background: false, idempotent: true, timeout: 4 * time.Second, maxOutput: 2048},
		{id: "android.app.list", name: "Android List Apps", description: "List launcher-visible applications with a bounded result set.", operation: OperationAppList, permission: "android.app.inspect", input: `{ "type":"object","properties":{"query":{"type":"string","maxLength":256},"limit":{"type":"integer","minimum":1,"maximum":500}},"additionalProperties":false }`, output: object, risk: capability.RiskLow, sideEffect: capability.SideEffectReadOnly, background: true, idempotent: true, retryable: true, timeout: 5 * time.Second, maxOutput: 65536},
		{id: "android.app.info", name: "Android App Info", description: "Read bounded metadata for one installed application visible to the host.", operation: OperationAppInfo, permission: "android.app.inspect", input: `{ "type":"object","required":["packageName"],"properties":{"packageName":{"type":"string","minLength":3,"maxLength":255}},"additionalProperties":false }`, output: object, risk: capability.RiskLow, sideEffect: capability.SideEffectReadOnly, background: true, idempotent: true, retryable: true, timeout: 4 * time.Second, maxOutput: 8192},
		{id: "android.app.open", name: "Android Open App", description: "Launch one installed application through PackageManager without constructing arbitrary shell commands.", operation: OperationAppOpen, permission: "android.app.launch", input: `{ "type":"object","required":["packageName"],"properties":{"packageName":{"type":"string","minLength":3,"maxLength":255}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectSystem, background: false, idempotent: false, timeout: 5 * time.Second, maxOutput: 2048},
		{id: "android.app.stop", name: "Android Stop App Background Processes", description: "Request Android to kill background processes for one package. This is not represented as force-stop when platform privilege is unavailable.", operation: OperationAppStop, permission: "android.app.manage", input: `{ "type":"object","required":["packageName"],"properties":{"packageName":{"type":"string","minLength":3,"maxLength":255}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectSystem, approval: true, background: true, idempotent: false, timeout: 5 * time.Second, maxOutput: 2048},
		{id: "android.app.install", name: "Android Install APK", description: "Open the Android package installer for an explicit content URI. Returns user-action-required rather than claiming silent installation.", operation: OperationAppInstall, permission: "android.app.manage", input: `{ "type":"object","required":["uri"],"properties":{"uri":{"type":"string","minLength":1,"maxLength":4096}},"additionalProperties":false }`, output: object, risk: capability.RiskHigh, sideEffect: capability.SideEffectSystem, approval: true, background: false, idempotent: false, timeout: 5 * time.Second, maxOutput: 2048},
		{id: "android.app.uninstall", name: "Android Uninstall App", description: "Open the Android package uninstaller for one package and require user confirmation.", operation: OperationAppUninstall, permission: "android.app.manage", input: `{ "type":"object","required":["packageName"],"properties":{"packageName":{"type":"string","minLength":3,"maxLength":255}},"additionalProperties":false }`, output: object, risk: capability.RiskHigh, sideEffect: capability.SideEffectDestructive, approval: true, background: false, idempotent: false, timeout: 5 * time.Second, maxOutput: 2048},
		{id: "android.bluetooth.status", name: "Android Bluetooth Status", description: "Inspect Bluetooth availability, enabled state and permission readiness.", operation: OperationBluetoothStatus, permission: "android.bluetooth.read", input: `{ "type":"object","properties":{},"additionalProperties":false }`, output: object, risk: capability.RiskLow, sideEffect: capability.SideEffectReadOnly, background: true, idempotent: true, retryable: true, timeout: 3 * time.Second, maxOutput: 4096},
		{id: "android.bluetooth.request_permission", modelName: "request_bluetooth_permission", name: "Request Bluetooth Permission", description: "Request the Android runtime permissions required for Bluetooth scanning and connection. Returns the current permission state and whether a system permission prompt was started.", operation: OperationBluetoothRequestPermission, permission: "android.bluetooth.connect", input: `{ "type":"object","properties":{"scan":{"type":"boolean"},"connect":{"type":"boolean"}},"additionalProperties":false }`, output: object, risk: capability.RiskHigh, sideEffect: capability.SideEffectSystem, approval: true, background: false, idempotent: true, retryable: false, timeout: 5 * time.Second, maxOutput: 4096},
		{id: "android.bluetooth.request_enable", name: "Request Bluetooth Enable", description: "Open the Android system confirmation flow to enable Bluetooth when it is disabled; never bypasses user confirmation on restricted Android versions.", operation: OperationBluetoothRequestEnable, permission: "android.bluetooth.connect", input: `{ "type":"object","properties":{},"additionalProperties":false }`, output: object, risk: capability.RiskHigh, sideEffect: capability.SideEffectSystem, approval: true, background: false, idempotent: true, retryable: false, timeout: 5 * time.Second, maxOutput: 4096},
		{id: "android.bluetooth.pair", name: "Pair Bluetooth Device", description: "Request Android Bluetooth bonding for an explicitly addressed nearby device and wait for a bounded bond result.", operation: OperationBluetoothPair, permission: "android.bluetooth.connect", input: `{ "type":"object","required":["address"],"properties":{"address":{"type":"string","minLength":17,"maxLength":17},"timeoutMs":{"type":"integer","minimum":1000,"maximum":30000}},"additionalProperties":false }`, output: object, risk: capability.RiskHigh, sideEffect: capability.SideEffectExternal, approval: true, background: false, idempotent: true, retryable: false, timeout: 32 * time.Second, maxOutput: 4096},
		{id: "android.bluetooth.paired", name: "Android Paired Bluetooth Devices", description: "List bonded Bluetooth devices when connect permission is granted.", operation: OperationBluetoothPaired, permission: "android.bluetooth.read", input: `{ "type":"object","properties":{},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectReadOnly, background: true, idempotent: true, retryable: true, timeout: 4 * time.Second, maxOutput: 16384},
		{id: "android.bluetooth.scan", name: "Android Bluetooth Classic Scan", description: "Perform a bounded Bluetooth Classic discovery and return discovered device metadata.", operation: OperationBluetoothScan, permission: "android.bluetooth.scan", input: `{ "type":"object","properties":{"timeoutMs":{"type":"integer","minimum":1000,"maximum":12000}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectReadOnly, background: true, idempotent: false, retryable: true, timeout: 14 * time.Second, maxOutput: 32768},
		{id: "android.ble.scan", name: "Android BLE Scan", description: "Perform a bounded BLE scan and return discovered devices, service UUIDs and RSSI metadata.", operation: OperationBLEScan, permission: "android.bluetooth.scan", input: `{ "type":"object","properties":{"timeoutMs":{"type":"integer","minimum":1000,"maximum":12000}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectReadOnly, background: true, idempotent: false, retryable: true, timeout: 14 * time.Second, maxOutput: 32768},
		{id: "android.bluetooth.classic.connect", name: "Bluetooth Classic Connect", description: "Open a bounded RFCOMM client connection to an explicitly addressed bonded/known Bluetooth device.", operation: OperationBluetoothClassicConnect, permission: "android.bluetooth.connect", input: `{ "type":"object","required":["address"],"properties":{"address":{"type":"string","minLength":17,"maxLength":17},"uuid":{"type":"string"},"secure":{"type":"boolean"},"timeoutMs":{"type":"integer","minimum":1000,"maximum":30000}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectExternal, background: true, idempotent: false, timeout: 32 * time.Second, maxOutput: 4096},
		{id: "android.bluetooth.classic.disconnect", name: "Bluetooth Classic Disconnect", description: "Close an Amitia-owned Bluetooth Classic session.", operation: OperationBluetoothClassicDisconnect, permission: "android.bluetooth.connect", input: `{ "type":"object","required":["sessionId"],"properties":{"sessionId":{"type":"string","minLength":1,"maxLength":128}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectExternal, background: true, idempotent: true, timeout: 5 * time.Second, maxOutput: 2048},
		{id: "android.bluetooth.classic.read", name: "Bluetooth Classic Read", description: "Read a bounded payload from an Amitia-owned RFCOMM session.", operation: OperationBluetoothClassicRead, permission: "android.bluetooth.connect", input: `{ "type":"object","required":["sessionId"],"properties":{"sessionId":{"type":"string"},"maxBytes":{"type":"integer","minimum":1,"maximum":65536},"timeoutMs":{"type":"integer","minimum":100,"maximum":30000},"decodeUtf8":{"type":"boolean"}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectReadOnly, background: true, idempotent: false, retryable: false, timeout: 32 * time.Second, maxOutput: 131072},
		{id: "android.bluetooth.classic.write", name: "Bluetooth Classic Write", description: "Write a bounded base64 or UTF-8 payload to an Amitia-owned RFCOMM session.", operation: OperationBluetoothClassicWrite, permission: "android.bluetooth.connect", input: `{ "type":"object","required":["sessionId"],"properties":{"sessionId":{"type":"string"},"valueBase64":{"type":"string","maxLength":100000},"valueText":{"type":"string","maxLength":65536}},"anyOf":[{"required":["valueBase64"]},{"required":["valueText"]}],"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectExternal, approval: true, background: true, idempotent: false, timeout: 8 * time.Second, maxOutput: 2048},
		{id: "android.bluetooth.classic.listen", name: "Bluetooth Classic Listen", description: "Open an Amitia-owned RFCOMM server socket for an explicit service UUID.", operation: OperationBluetoothClassicListen, permission: "android.bluetooth.connect", input: `{ "type":"object","properties":{"uuid":{"type":"string"},"serviceName":{"type":"string","maxLength":80},"secure":{"type":"boolean"}},"additionalProperties":false }`, output: object, risk: capability.RiskHigh, sideEffect: capability.SideEffectExternal, approval: true, background: true, idempotent: false, timeout: 5 * time.Second, maxOutput: 4096},
		{id: "android.bluetooth.classic.accept", name: "Bluetooth Classic Accept", description: "Accept one incoming connection on an Amitia-owned RFCOMM server socket with a bounded timeout.", operation: OperationBluetoothClassicAccept, permission: "android.bluetooth.connect", input: `{ "type":"object","required":["serverId"],"properties":{"serverId":{"type":"string"},"timeoutMs":{"type":"integer","minimum":1000,"maximum":30000}},"additionalProperties":false }`, output: object, risk: capability.RiskHigh, sideEffect: capability.SideEffectExternal, approval: true, background: true, idempotent: false, timeout: 32 * time.Second, maxOutput: 4096},
		{id: "android.bluetooth.classic.close_server", name: "Bluetooth Classic Close Server", description: "Close an Amitia-owned RFCOMM server socket.", operation: OperationBluetoothClassicCloseServer, permission: "android.bluetooth.connect", input: `{ "type":"object","required":["serverId"],"properties":{"serverId":{"type":"string"}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectExternal, background: true, idempotent: true, timeout: 5 * time.Second, maxOutput: 2048},
		{id: "android.ble.connect", name: "BLE Connect", description: "Connect to an explicitly addressed BLE peripheral and create an opaque Amitia GATT session.", operation: OperationBLEConnect, permission: "android.bluetooth.connect", input: `{ "type":"object","required":["address"],"properties":{"address":{"type":"string","minLength":17,"maxLength":17},"timeoutMs":{"type":"integer","minimum":1000,"maximum":30000}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectExternal, background: true, idempotent: false, timeout: 32 * time.Second, maxOutput: 4096},
		{id: "android.ble.disconnect", name: "BLE Disconnect", description: "Disconnect and close an Amitia-owned BLE GATT session.", operation: OperationBLEDisconnect, permission: "android.bluetooth.connect", input: `{ "type":"object","required":["sessionId"],"properties":{"sessionId":{"type":"string"}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectExternal, background: true, idempotent: true, timeout: 5 * time.Second, maxOutput: 2048},
		{id: "android.ble.services", name: "BLE Discover Services", description: "Discover GATT services and bounded characteristic metadata for a connected BLE session.", operation: OperationBLEServices, permission: "android.bluetooth.connect", input: `{ "type":"object","required":["sessionId"],"properties":{"sessionId":{"type":"string"},"timeoutMs":{"type":"integer","minimum":1000,"maximum":20000}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectReadOnly, background: true, idempotent: false, retryable: true, timeout: 22 * time.Second, maxOutput: 65536},
		{id: "android.ble.characteristics", name: "BLE Characteristics", description: "List characteristics for one discovered GATT service.", operation: OperationBLECharacteristics, permission: "android.bluetooth.connect", input: `{ "type":"object","required":["sessionId","serviceUuid"],"properties":{"sessionId":{"type":"string"},"serviceUuid":{"type":"string"}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectReadOnly, background: true, idempotent: true, timeout: 5 * time.Second, maxOutput: 32768},
		{id: "android.ble.read", name: "BLE Read Characteristic", description: "Read one explicit GATT characteristic from an Amitia-owned BLE session.", operation: OperationBLERead, permission: "android.bluetooth.connect", input: `{ "type":"object","required":["sessionId","serviceUuid","characteristicUuid"],"properties":{"sessionId":{"type":"string"},"serviceUuid":{"type":"string"},"characteristicUuid":{"type":"string"},"timeoutMs":{"type":"integer","minimum":1000,"maximum":20000}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectReadOnly, background: true, idempotent: false, retryable: true, timeout: 22 * time.Second, maxOutput: 131072},
		{id: "android.ble.write", name: "BLE Write Characteristic", description: "Write a bounded base64 or UTF-8 payload to one explicit GATT characteristic.", operation: OperationBLEWrite, permission: "android.bluetooth.connect", input: `{ "type":"object","required":["sessionId","serviceUuid","characteristicUuid"],"properties":{"sessionId":{"type":"string"},"serviceUuid":{"type":"string"},"characteristicUuid":{"type":"string"},"valueBase64":{"type":"string","maxLength":1024},"valueText":{"type":"string","maxLength":512},"withoutResponse":{"type":"boolean"},"timeoutMs":{"type":"integer","minimum":1000,"maximum":20000}},"anyOf":[{"required":["valueBase64"]},{"required":["valueText"]}],"additionalProperties":false }`, output: object, risk: capability.RiskHigh, sideEffect: capability.SideEffectExternal, approval: true, background: true, idempotent: false, timeout: 22 * time.Second, maxOutput: 4096},
		{id: "android.ble.subscribe", name: "BLE Subscribe Characteristic", description: "Enable GATT notifications/indications; incoming values are emitted as durable Workflow device events.", operation: OperationBLESubscribe, permission: "android.bluetooth.connect", input: `{ "type":"object","required":["sessionId","serviceUuid","characteristicUuid"],"properties":{"sessionId":{"type":"string"},"serviceUuid":{"type":"string"},"characteristicUuid":{"type":"string"},"indications":{"type":"boolean"},"timeoutMs":{"type":"integer","minimum":1000,"maximum":20000}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectExternal, approval: true, background: true, idempotent: false, timeout: 22 * time.Second, maxOutput: 4096},
		{id: "android.ble.read_notifications", modelName: "bluetooth_ble_read_notifications", name: "BLE Read Notifications", description: "Read buffered notifications/indications received by an active Amitia BLE GATT session after subscription. Results can be filtered by service/characteristic and consumed atomically.", operation: OperationBLEReadNotifications, permission: "android.bluetooth.connect", input: `{ "type":"object","required":["sessionId"],"properties":{"sessionId":{"type":"string"},"serviceUuid":{"type":"string"},"characteristicUuid":{"type":"string"},"maxItems":{"type":"integer","minimum":1,"maximum":100},"clearAfterRead":{"type":"boolean"}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectReadOnly, background: true, idempotent: false, retryable: true, timeout: 5 * time.Second, maxOutput: 131072},
		{id: "android.ble.unsubscribe", name: "BLE Unsubscribe Characteristic", description: "Disable notifications/indications for one GATT characteristic.", operation: OperationBLEUnsubscribe, permission: "android.bluetooth.connect", input: `{ "type":"object","required":["sessionId","serviceUuid","characteristicUuid"],"properties":{"sessionId":{"type":"string"},"serviceUuid":{"type":"string"},"characteristicUuid":{"type":"string"},"timeoutMs":{"type":"integer","minimum":1000,"maximum":20000}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectExternal, background: true, idempotent: true, timeout: 22 * time.Second, maxOutput: 4096},
		{id: "android.tasker.trigger_event", modelName: "trigger_tasker_event", name: "Trigger Tasker Event", description: "Send an explicit package-scoped Android broadcast for a Tasker Intent Received profile. When action is omitted Amitia generates a stable com.amitia.tasker.EVENT.<EVENT> action from eventName.", operation: OperationTaskerTriggerEvent, permission: "android.tasker.execute", input: `{ "type":"object","required":["eventName"],"properties":{"eventName":{"type":"string","minLength":1,"maxLength":128},"action":{"type":"string","maxLength":255},"variables":{"type":"object","maxProperties":64,"additionalProperties":{"type":["string","number","boolean","null"]}}},"additionalProperties":false }`, output: object, risk: capability.RiskHigh, sideEffect: capability.SideEffectExternal, approval: true, background: true, idempotent: false, timeout: 5 * time.Second, maxOutput: 4096},
		{id: "android.tasker.run_task", name: "Run Tasker Task", description: "Ask Tasker to run an explicitly named task through its documented external-access broadcast contract.", operation: OperationTaskerRunTask, permission: "android.tasker.execute", input: `{ "type":"object","required":["taskName"],"properties":{"taskName":{"type":"string","minLength":1,"maxLength":128},"parameters":{"type":"array","maxItems":32,"items":{"type":["string","number","boolean","null"]}},"variables":{"type":"object","maxProperties":64,"additionalProperties":{"type":["string","number","boolean","null"]}}},"additionalProperties":false }`, output: object, risk: capability.RiskHigh, sideEffect: capability.SideEffectExternal, approval: true, background: true, idempotent: false, timeout: 5 * time.Second, maxOutput: 4096},
		{id: "android.music.play", modelName: "music_play", name: "Music Play", description: "Play one explicit audio source in Amitia's managed Android media player.", operation: OperationMusicPlay, permission: "android.media.playback", input: `{ "type":"object","required":["source"],"properties":{"source":{"type":"string","minLength":1,"maxLength":8192},"startPositionMs":{"type":"integer","minimum":0,"maximum":86400000}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectSystem, background: true, idempotent: false, timeout: 35 * time.Second, maxOutput: 8192},
		{id: "android.music.play_queue", modelName: "music_play_queue", name: "Music Play Queue", description: "Replace the Amitia Android player queue with explicit audio sources and start playback.", operation: OperationMusicPlayQueue, permission: "android.media.playback", input: `{ "type":"object","required":["sources"],"properties":{"sources":{"type":"array","minItems":1,"maxItems":100,"items":{"type":"string","minLength":1,"maxLength":8192}},"startIndex":{"type":"integer","minimum":0,"maximum":99}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectSystem, background: true, idempotent: false, timeout: 35 * time.Second, maxOutput: 16384},
		{id: "android.music.pause", modelName: "music_pause", name: "Music Pause", description: "Pause Amitia-managed Android music playback.", operation: OperationMusicPause, permission: "android.media.playback", input: `{ "type":"object","properties":{},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectSystem, background: true, idempotent: true, timeout: 3 * time.Second, maxOutput: 4096},
		{id: "android.music.resume", modelName: "music_resume", name: "Music Resume", description: "Resume Amitia-managed Android music playback.", operation: OperationMusicResume, permission: "android.media.playback", input: `{ "type":"object","properties":{},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectSystem, background: true, idempotent: true, timeout: 3 * time.Second, maxOutput: 4096},
		{id: "android.music.stop", modelName: "music_stop", name: "Music Stop", description: "Stop Amitia-managed Android music playback and keep the current queue available for inspection.", operation: OperationMusicStop, permission: "android.media.playback", input: `{ "type":"object","properties":{},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectSystem, background: true, idempotent: true, timeout: 3 * time.Second, maxOutput: 4096},
		{id: "android.music.seek", modelName: "music_seek", name: "Music Seek", description: "Seek Amitia-managed Android music playback to an absolute position in milliseconds.", operation: OperationMusicSeek, permission: "android.media.playback", input: `{ "type":"object","required":["positionMs"],"properties":{"positionMs":{"type":"integer","minimum":0,"maximum":86400000}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectSystem, background: true, idempotent: true, timeout: 3 * time.Second, maxOutput: 4096},
		{id: "android.music.set_volume", modelName: "music_set_volume", name: "Music Set Volume", description: "Set Amitia-managed player volume from 0.0 to 1.0 without changing the global device volume.", operation: OperationMusicSetVolume, permission: "android.media.playback", input: `{ "type":"object","required":["volume"],"properties":{"volume":{"type":"number","minimum":0,"maximum":1}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectSystem, background: true, idempotent: true, timeout: 3 * time.Second, maxOutput: 4096},
		{id: "android.music.status", modelName: "music_status", name: "Music Status", description: "Read Amitia-managed Android music player state, queue, position, duration and volume.", operation: OperationMusicStatus, permission: "android.media.playback", input: `{ "type":"object","properties":{},"additionalProperties":false }`, output: object, risk: capability.RiskLow, sideEffect: capability.SideEffectReadOnly, background: true, idempotent: true, retryable: true, timeout: 3 * time.Second, maxOutput: 16384},
		{id: "android.intent.send_broadcast", modelName: "send_broadcast", name: "Send Android Broadcast", description: "Send one explicit Android broadcast action with bounded primitive extras; does not execute shell commands.", operation: OperationSendBroadcast, permission: "android.intent.send", input: `{ "type":"object","required":["action"],"properties":{"action":{"type":"string","minLength":1,"maxLength":255},"packageName":{"type":"string","maxLength":255},"dataUri":{"type":"string","maxLength":4096},"flags":{"type":"integer","minimum":0,"maximum":2147483647},"extras":{"type":"object","maxProperties":64,"additionalProperties":{"type":["string","number","boolean","null"]}}},"additionalProperties":false }`, output: object, risk: capability.RiskHigh, sideEffect: capability.SideEffectExternal, approval: true, background: true, idempotent: false, timeout: 5 * time.Second, maxOutput: 4096},
		{id: "android.ui.toast", modelName: "toast", name: "Android Toast", description: "Show a bounded Amitia toast message on the Android device.", operation: OperationToast, permission: "android.interaction.global", input: `{ "type":"object","required":["text"],"properties":{"text":{"type":"string","minLength":1,"maxLength":512},"duration":{"type":"string","enum":["short","long"]}},"additionalProperties":false }`, output: object, risk: capability.RiskMedium, sideEffect: capability.SideEffectSystem, background: false, idempotent: false, timeout: 3 * time.Second, maxOutput: 2048},
	}
	defs := make([]capability.ToolDefinition, 0, len(specs))
	for _, spec := range specs {
		defs = append(defs, buildTool(spec))
	}
	return defs
}

func buildTool(spec toolSpec) capability.ToolDefinition {
	modelName := spec.modelName
	if modelName == "" {
		modelName = spec.id
	}
	return capability.ToolDefinition{
		ID: spec.id, ModelName: modelName, Source: capability.ToolSourceBuiltin,
		Name: spec.name, Description: spec.description,
		InputSchema: json.RawMessage(spec.input), OutputSchema: json.RawMessage(spec.output),
		Permissions: []capability.PermissionRequirement{{Capability: spec.permission, Risk: string(spec.risk)}},
		RiskLevel:   spec.risk, SideEffect: spec.sideEffect, HasSideEffects: spec.sideEffect != capability.SideEffectReadOnly && spec.sideEffect != capability.SideEffectNone,
		Idempotent: spec.idempotent, Retryable: spec.retryable, TimeoutMS: spec.timeout.Milliseconds(),
		ToolVersion:     capability.ToolVersion{SchemaVersion: 1, Revision: "android-device-control-v1"},
		ModelExposure:   capability.ModelExposureRule{ExposedByDefault: true, Categories: []string{"android", "automation"}, Priority: 40},
		Metadata:        map[string]any{"androidNativeOperation": spec.operation, "bridgeProtocol": "android_native", "typedCapability": true},
		ExecutionPolicy: capability.ToolExecutionPolicy{Timeout: spec.timeout, MaxConcurrency: 1, Idempotent: spec.idempotent, ApprovalRequired: spec.approval, AllowBackground: spec.background},
		ResultPolicy:    capability.ToolResultPolicy{SanitizeError: true, MaxOutputBytes: spec.maxOutput, Streaming: capability.ToolStreamingPolicy{Enabled: false}},
		Runtime:         capability.RuntimeBinding{RuntimeType: capability.RuntimeTypeAndroid_Native, RuntimeID: RuntimeID, HandlerName: spec.operation},
		Enabled:         true, Compatible: true,
	}
}
