package androidmedia

const (
	SCREENSHOT_UNSUPPORTED              = "SCREENSHOT_UNSUPPORTED"
	SCREENSHOT_ACCESSIBILITY_DISABLED   = "SCREENSHOT_ACCESSIBILITY_DISABLED"
	SCREENSHOT_ACCESSIBILITY_NOT_CONNECTED = "SCREENSHOT_ACCESSIBILITY_NOT_CONNECTED"
	SCREENSHOT_CAPABILITY_NOT_DECLARED  = "SCREENSHOT_CAPABILITY_NOT_DECLARED"
	SCREENSHOT_INVALID_DISPLAY          = "SCREENSHOT_INVALID_DISPLAY"
	SCREENSHOT_INTERVAL_TOO_SHORT       = "SCREENSHOT_INTERVAL_TOO_SHORT"
	SCREENSHOT_SECURE_CONTENT           = "SCREENSHOT_SECURE_CONTENT"
	SCREENSHOT_CAPTURE_FAILED           = "SCREENSHOT_CAPTURE_FAILED"
	SCREENSHOT_ENCODE_FAILED            = "SCREENSHOT_ENCODE_FAILED"
	SCREENSHOT_TOO_LARGE                = "SCREENSHOT_TOO_LARGE"
	SCREENSHOT_ARTIFACT_WRITE_FAILED    = "SCREENSHOT_ARTIFACT_WRITE_FAILED"
	SCREENSHOT_RESOURCE_INVALID         = "SCREENSHOT_RESOURCE_INVALID"
	SCREENSHOT_CANCELLED                = "SCREENSHOT_CANCELLED"
	SCREENSHOT_RESOURCE_EXHAUSTED       = "SCREENSHOT_RESOURCE_EXHAUSTED"
	BLOCKED_ANDROID_NATIVE_HOST_SOURCE  = "BLOCKED_ANDROID_NATIVE_HOST_SOURCE"
	BLOCKED_BY_FROZEN_A_CONTRACT       = "BLOCKED_BY_FROZEN_A_CONTRACT"
)

const (
	PermissionScreenCapture = "android.media.screen_capture"
)

const (
	OperationScreenshotCapture = "media.screenshot.capture"
	OperationScreenshotStatus  = "media.screenshot.status"
)

const (
	ToolIDScreenshot    = "android.screen.screenshot"
	HandlerScreenshot   = OperationScreenshotCapture
)

const (
	DefaultScreenshotFormat     = "png"
	DefaultJPEGQuality          = 90
	DefaultMaxScreenshotPixels  = 16_000_000
	DefaultMaxEncodedBytes      = 50 * 1024 * 1024
)
