<template>
  <div class="advanced-page">
    <div class="head"><div><h2>高级系统</h2><p>账号安全、审计、运行观测、语音会话与渠道 Bridge 的统一管理入口。</p></div><el-button :loading="loading" @click="loadAll">刷新</el-button></div>
    <el-tabs v-model="tab">
      <el-tab-pane label="账号安全" name="auth">
        <el-card shadow="never"><template #header>当前会话</template><Description :data="currentSession" /></el-card>
        <el-card shadow="never"><template #header><div class="card-head"><span>恢复代码</span><el-button type="primary" size="small" @click="generateRecoveryCodes">重新生成</el-button></div></template>
          <Description :data="recoveryStatus" />
          <el-alert v-if="recoveryCodes.length" type="warning" :closable="false" title="恢复代码只在本次生成时显示，请立即保存。" />
          <pre v-if="recoveryCodes.length" class="json">{{ recoveryCodes.join('\n') }}</pre>
        </el-card>
        <el-card shadow="never"><template #header>会话策略</template>
          <el-form label-width="170px"><el-form-item label="访问令牌时长（分钟）"><el-input-number v-model="sessionSettings.sessionTimeoutMinutes" :min="1" :max="10080" /></el-form-item><el-form-item label="最大会话数"><el-input-number v-model="sessionSettings.maxSessionsPerUser" :min="1" :max="100" /></el-form-item><el-form-item label="设备追踪"><el-switch v-model="sessionSettings.enableDeviceTracking" /></el-form-item><el-button type="primary" @click="saveSessionSettings">保存策略</el-button><el-tag v-if="sessionSettings.requiresRestart" class="ml">修改后需重启后端生效</el-tag></el-form>
        </el-card>
        <el-card shadow="never"><template #header>登录历史</template><el-table :data="loginHistory"><el-table-column prop="occurredAt" label="时间" min-width="180"/><el-table-column prop="eventType" label="事件" min-width="190"/><el-table-column prop="outcome" label="结果" width="100"/><el-table-column prop="ipAddress" label="IP" min-width="140"/><el-table-column prop="userAgent" label="User-Agent" min-width="260" show-overflow-tooltip/></el-table></el-card>
      </el-tab-pane>
      <el-tab-pane label="审计" name="audit">
        <el-card shadow="never"><template #header><div class="card-head"><span>系统审计</span><div><el-button size="small" @click="saveAuditSettings">保存设置</el-button><el-button size="small" type="danger" plain @click="clearAudit">清空日志</el-button></div></div></template>
          <el-form inline><el-form-item label="启用"><el-switch v-model="auditSettings.enabled" /></el-form-item><el-form-item label="记录动作"><el-switch v-model="auditSettings.logActions" /></el-form-item><el-form-item label="保留天数"><el-input-number v-model="auditSettings.retentionDays" :min="1" :max="3650" /></el-form-item></el-form>
          <p>日志总数：{{ auditStats.total ?? 0 }} · 可审计动作：{{ auditActions.join('、') || '—' }}</p>
          <el-table :data="auditLogs"><el-table-column prop="time" label="时间" min-width="170"/><el-table-column prop="ruleId" label="规则" min-width="150"/><el-table-column prop="action" label="动作" min-width="180"/></el-table>
        </el-card>
      </el-tab-pane>
      <el-tab-pane label="运行观测" name="observability">
        <el-card shadow="never"><template #header>情绪检测</template><el-switch v-model="mood.enabled" @change="saveMood" /> <span class="muted">阈值 {{ mood.threshold ?? 0.5 }}</span></el-card>
        <el-card shadow="never"><template #header><div class="card-head"><span>Shadow Mode</span><div><el-button size="small" type="primary" @click="shadowStart">启动</el-button><el-button size="small" @click="shadowAdvance">推进阶段</el-button><el-button size="small" type="danger" plain @click="shadowStop">停止</el-button></div></div></template><pre class="json">{{ pretty(shadowStatus) }}</pre><h4>阈值</h4><pre class="json">{{ pretty(shadowThresholds) }}</pre><h4>回滚</h4><pre class="json">{{ pretty(shadowRollbacks) }}</pre><el-button size="small" @click="shadowLoadSim">运行短负载模拟</el-button></el-card>
        <el-card shadow="never"><template #header>Runtime 模块健康</template><pre class="json">{{ pretty(runtimeModules) }}</pre></el-card>
        <el-card shadow="never"><template #header>Runtime 健康历史</template><pre class="json">{{ pretty(healthHistory) }}</pre></el-card>
        <el-card shadow="never"><template #header><div class="card-head"><span>模型错误</span><el-button size="small" type="danger" plain @click="clearModelErrors">清空</el-button></div></template><pre class="json">{{ pretty(modelErrors) }}</pre></el-card>
        <el-card shadow="never"><template #header>日志文件</template><el-table :data="logFiles"><el-table-column prop="name" label="文件" min-width="220"/><el-table-column prop="size" label="大小" width="120"/><el-table-column label="操作" width="100"><template #default="{row}"><el-button link type="primary" @click="openLog(row.name)">查看</el-button></template></el-table-column></el-table><el-dialog v-model="logOpen" :title="logName" width="70%"><pre class="json log-content">{{ logContent }}</pre></el-dialog></el-card>
        <el-card shadow="never"><template #header><div class="card-head"><span>Usage 分析</span><el-button size="small" type="danger" plain @click="clearUsage">清空统计</el-button></div></template><h4>按天</h4><pre class="json">{{ pretty(usageDaily) }}</pre><h4>按模型</h4><pre class="json">{{ pretty(usageModels) }}</pre><h4>按来源</h4><pre class="json">{{ pretty(usageSources) }}</pre></el-card>
      </el-tab-pane>
      <el-tab-pane label="安全与 Bridge" name="bridge">
        <el-card shadow="never"><template #header>访问安全</template><el-form label-width="130px"><el-form-item label="要求认证"><el-switch v-model="accessConfig.requireAuth" /></el-form-item><el-form-item label="允许 Origin"><el-input v-model="accessConfig.allowedOrigins" /></el-form-item><el-form-item label="限流"><el-switch v-model="accessConfig.rateLimit" /></el-form-item><el-button type="primary" @click="saveAccess">保存</el-button></el-form><pre class="json">{{ pretty(accessStatus) }}\n{{ pretty(accountCheck) }}</pre></el-card>
        <el-card shadow="never"><template #header><div class="card-head"><span>微信 Bridge</span><el-button size="small" @click="recoverWechat">恢复</el-button></div></template><pre class="json">{{ pretty(wechatBridge) }}</pre><h4>Reply Timing</h4><pre class="json">{{ pretty(wechatReplyTiming) }}</pre><h4>最近事件</h4><pre class="json">{{ pretty(wechatEvents) }}</pre></el-card>
        <el-card shadow="never"><template #header><div class="card-head"><span>QQ Bridge</span><el-button size="small" @click="recoverQQ">恢复</el-button></div></template><pre class="json">{{ pretty(qqBridge) }}</pre><h4>最近事件</h4><pre class="json">{{ pretty(qqEvents) }}</pre></el-card>
        <el-card shadow="never"><template #header>Voice Sessions</template><el-table :data="voiceSessions"><el-table-column prop="sessionId" label="Session" min-width="220"/><el-table-column prop="conversationId" label="Conversation" min-width="180"/><el-table-column prop="characterId" label="Character" min-width="160"/><el-table-column label="控制" min-width="300"><template #default="{row}"><el-button size="small" @click="voiceAction(row.sessionId,'start')">启动</el-button><el-button size="small" @click="voiceAction(row.sessionId,'interrupt')">打断</el-button><el-button size="small" @click="voiceAction(row.sessionId,'wake/arm')">唤醒</el-button><el-button size="small" @click="voiceAction(row.sessionId,'wake/disarm')">取消唤醒</el-button><el-button size="small" type="danger" plain @click="voiceAction(row.sessionId,'stop')">停止</el-button></template></el-table-column></el-table></el-card>
      </el-tab-pane>
    </el-tabs>
  </div>
</template>
<script setup lang="ts">
import { defineComponent, h, onMounted, reactive, ref } from 'vue'; import { ElMessage,ElMessageBox } from 'element-plus'; import { apiClient } from '@/composables/useApi';

const Description=defineComponent({props:{data:{type:Object,required:true}},setup(p){return()=>h('div',{class:'desc'},Object.entries(p.data||{}).map(([k,v])=>h('div',{class:'desc-row'},[h('span',k),h('code',typeof v==='object'?JSON.stringify(v):String(v??'—'))])))}});
const tab=ref('auth'),loading=ref(false); const currentSession=ref<any>({}),loginHistory=ref<any[]>([]),recoveryStatus=ref<any>({}),recoveryCodes=ref<string[]>([]),sessionSettings=reactive<any>({sessionTimeoutMinutes:60,maxSessionsPerUser:10,enableDeviceTracking:true});
const auditActions=ref<string[]>([]),auditLogs=ref<any[]>([]),auditStats=ref<any>({}),auditSettings=reactive<any>({enabled:true,logActions:true,retentionDays:90}); const mood=reactive<any>({enabled:false,threshold:.5}),runtimeModules=ref<any>({}),healthHistory=ref<any>({}),modelErrors=ref<any>({}),logFiles=ref<any[]>([]),usageDaily=ref<any>({}),usageModels=ref<any>({}),usageSources=ref<any>({});
const shadowStatus=ref<any>({}),shadowThresholds=ref<any>({}),shadowRollbacks=ref<any>({});
const accessConfig=reactive<any>({requireAuth:true,allowedOrigins:'*',rateLimit:true}),accessStatus=ref<any>({}),accountCheck=ref<any>({}),wechatBridge=ref<any>({}),wechatEvents=ref<any>({}),wechatReplyTiming=ref<any>({}),qqBridge=ref<any>({}),qqEvents=ref<any>({}),voiceSessions=ref<any[]>([]); const logOpen=ref(false),logName=ref(''),logContent=ref('');
const pretty=(v:any)=>JSON.stringify(v??{},null,2); const safe=async<T>(fn:()=>Promise<T>,fallback:T)=>{try{return await fn()}catch{return fallback}};
async function loadAll(){loading.value=true;try{const [cs,lh,rs,ss,aa,al,as,ast,md,rm,hh,me,lf,ud,um,us,shs,sht,shr,ac,acs,ach,wb,we,wr,qb,qe,vs]=await Promise.all([
 safe(()=>apiClient.get('/api/auth/current-session').then(r=>r.data),{}),safe(()=>apiClient.get('/api/auth/login-history').then(r=>r.data),[]),safe(()=>apiClient.get('/api/auth/recovery-codes/status').then(r=>r.data),{}),safe(()=>apiClient.get('/api/auth/session-settings').then(r=>r.data),{}),safe(()=>apiClient.get('/api/audit/actions').then(r=>r.data),[]),safe(()=>apiClient.get('/api/audit/logs',{params:{limit:200}}).then(r=>r.data),[]),safe(()=>apiClient.get('/api/audit/settings').then(r=>r.data),{}),safe(()=>apiClient.get('/api/audit/stats').then(r=>r.data),{}),safe(()=>apiClient.get('/api/config/mood-detection').then(r=>r.data),{}),safe(()=>apiClient.get('/api/runtime/modules/health').then(r=>r.data),{}),safe(()=>apiClient.get('/api/runtime/health-history').then(r=>r.data),{}),safe(()=>apiClient.get('/api/logs/model-errors').then(r=>r.data),{}),safe(()=>apiClient.get('/api/logs/files').then(r=>r.data),{}),safe(()=>apiClient.get('/api/usage/daily').then(r=>r.data),{}),safe(()=>apiClient.get('/api/usage/models').then(r=>r.data),{}),safe(()=>apiClient.get('/api/usage/sources').then(r=>r.data),{}),safe(()=>apiClient.get('/api/shadow/status').then(r=>r.data),{}),safe(()=>apiClient.get('/api/shadow/thresholds').then(r=>r.data),{}),safe(()=>apiClient.get('/api/shadow/rollbacks').then(r=>r.data),{}),safe(()=>apiClient.get('/api/security/access-config').then(r=>r.data),{}),safe(()=>apiClient.get('/api/security/access-status').then(r=>r.data),{}),safe(()=>apiClient.get('/api/security/account-check').then(r=>r.data),{}),safe(()=>apiClient.get('/api/wechat/bridge/status-detail').then(r=>r.data),{}),safe(()=>apiClient.get('/api/wechat/bridge/events').then(r=>r.data),{}),safe(()=>apiClient.get('/api/wechat/reply-timing/status').then(r=>r.data),{}),safe(()=>apiClient.get('/api/qq/bridge/status-detail').then(r=>r.data),{}),safe(()=>apiClient.get('/api/qq/bridge/events').then(r=>r.data),{}),safe(()=>apiClient.get('/api/voice/sessions').then(r=>r.data),{})]);
 currentSession.value=cs;loginHistory.value=Array.isArray(lh)?lh:[];recoveryStatus.value=rs;Object.assign(sessionSettings,ss);auditActions.value=Array.isArray(aa)?aa:[];auditLogs.value=Array.isArray(al)?al:[];auditStats.value=ast;Object.assign(auditSettings,as);Object.assign(mood,md);runtimeModules.value=rm;healthHistory.value=hh;modelErrors.value=me;logFiles.value=Array.isArray((lf as any)?.files)?(lf as any).files:Array.isArray(lf)?lf:[];usageDaily.value=ud;usageModels.value=um;usageSources.value=us;shadowStatus.value=shs;shadowThresholds.value=sht;shadowRollbacks.value=shr;Object.assign(accessConfig,ac);accessStatus.value=acs;accountCheck.value=ach;wechatBridge.value=wb;wechatEvents.value=we;wechatReplyTiming.value=wr;qqBridge.value=qb;qqEvents.value=qe;voiceSessions.value=Array.isArray((vs as any)?.sessions)?(vs as any).sessions:[];}finally{loading.value=false;}}
async function generateRecoveryCodes(){const r=await apiClient.post('/api/auth/recovery-codes/generate',{});recoveryCodes.value=Array.isArray(r.data?.codes)?r.data.codes:[];await loadAll();}
async function saveSessionSettings(){await apiClient.put('/api/auth/session-settings',{...sessionSettings});ElMessage.success('会话策略已保存，重启后端后应用');}
async function saveAuditSettings(){await apiClient.put('/api/audit/settings',{...auditSettings});ElMessage.success('审计设置已保存');}
async function clearAudit(){await ElMessageBox.confirm('确定清空系统审计日志？','确认');await apiClient.delete('/api/audit/logs');await loadAll();}
async function saveMood(){await apiClient.put('/api/config/mood-detection',{enabled:mood.enabled,threshold:mood.threshold});ElMessage.success('情绪检测设置已保存');}
async function clearModelErrors(){await ElMessageBox.confirm('确定清空模型错误日志？','确认');await apiClient.delete('/api/logs/model-errors');await loadAll();}
async function clearUsage(){await ElMessageBox.confirm('确定清空 Usage 统计？该操作不可撤销。','确认');await apiClient.delete('/api/usage/clear');await loadAll();}
async function openLog(name:string){const r=await apiClient.get(`/api/logs/files/${encodeURIComponent(name)}`);logName.value=name;logContent.value=typeof r.data==='string'?r.data:pretty(r.data);logOpen.value=true;}
async function saveAccess(){await apiClient.put('/api/security/access-config',{...accessConfig});ElMessage.success('访问安全设置已保存');await loadAll();}
async function recoverWechat(){await apiClient.post('/api/wechat/bridge/recover',{});await apiClient.post('/api/wechat/reply-timing/recover',{});ElMessage.success('微信 Bridge 恢复请求已执行');await loadAll();}
async function recoverQQ(){await apiClient.post('/api/qq/bridge/recover',{});ElMessage.success('QQ Bridge 恢复请求已执行');await loadAll();}
async function voiceAction(id:string,action:string){await apiClient.post(`/api/voice/sessions/${encodeURIComponent(id)}/${action}`,{});await loadAll();}

async function shadowStart(){await apiClient.post('/api/shadow/start',{phase:'interaction'});ElMessage.success('Shadow Mode 已启动');await loadAll();}
async function shadowStop(){await apiClient.post('/api/shadow/stop',{});ElMessage.success('Shadow Mode 已停止');await loadAll();}
async function shadowAdvance(){await apiClient.post('/api/shadow/phase/advance',{});await loadAll();}
async function shadowLoadSim(){await apiClient.post('/api/shadow/load-sim',{profile:'burst',durationSeconds:10,burstRate:50,sustainedRps:20});ElMessage.success('负载模拟完成');await loadAll();}
onMounted(loadAll);
</script>

<style scoped>.advanced-page{display:grid;gap:16px}.head,.card-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.head h2{margin:0 0 4px}.head p{margin:0;color:var(--el-text-color-secondary)}.el-card{margin-bottom:14px}.json{max-height:360px;overflow:auto;background:var(--el-fill-color-light);padding:12px;border-radius:8px;white-space:pre-wrap;word-break:break-word}.log-content{max-height:65vh}.muted{color:var(--el-text-color-secondary);margin-left:10px}.ml{margin-left:12px}:deep(.desc){display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:8px}:deep(.desc-row){display:grid;gap:3px;padding:8px;background:var(--el-fill-color-light);border-radius:6px}:deep(.desc-row span){font-size:12px;color:var(--el-text-color-secondary)}:deep(.desc-row code){word-break:break-all}</style>
