package alarms

const (
	ErrAlarmsUnsupported                     = "ALARMS_UNSUPPORTED"
	ErrAlarmsUnsupportedOSVersion            = "ALARMS_UNSUPPORTED_OS_VERSION"
	ErrAlarmsUnavailable                     = "ALARMS_UNAVAILABLE"
	ErrAlarmsAuthNotDetermined               = "ALARMS_AUTH_NOT_DETERMINED"
	ErrAlarmsAuthDenied                      = "ALARMS_AUTH_DENIED"
	ErrAlarmsNotFound                        = "ALARMS_NOT_FOUND"
	ErrAlarmsAlreadyExists                   = "ALARMS_ALREADY_EXISTS"
	ErrAlarmsScheduleInPast                  = "ALARMS_SCHEDULE_IN_PAST"
	ErrAlarmsScheduleInvalid                 = "ALARMS_SCHEDULE_INVALID"
	ErrAlarmsCountdownInvalid                = "ALARMS_COUNTDOWN_INVALID"
	ErrAlarmsPresentationInvalid             = "ALARMS_PRESENTATION_INVALID"
	ErrAlarmsSoundInvalid                    = "ALARMS_SOUND_INVALID"
	ErrAlarmsSoundNotRegistered              = "ALARMS_SOUND_NOT_REGISTERED"
	ErrAlarmsActionInvalid                   = "ALARMS_ACTION_INVALID"
	ErrAlarmsMetadataInvalid                 = "ALARMS_METADATA_INVALID"
	ErrAlarmsSecondaryActionInvalid          = "ALARMS_SECONDARY_ACTION_INVALID"
	ErrAlarmsIntentInvalid                   = "ALARMS_INTENT_INVALID"
	ErrAlarmsIntentNotAllowed                = "ALARMS_INTENT_NOT_ALLOWED"
	ErrAlarmsMaximumLimitReached             = "ALARMS_MAXIMUM_LIMIT_REACHED"
	ErrAlarmsPlatformFailed                  = "ALARMS_PLATFORM_FAILED"
	ErrAlarmsInvalidState                    = "ALARMS_INVALID_STATE"
	ErrAlarmsStopFailed                      = "ALARMS_STOP_FAILED"
	ErrAlarmsCancelFailed                    = "ALARMS_CANCEL_FAILED"
	ErrAlarmsPauseFailed                     = "ALARMS_PAUSE_FAILED"
	ErrAlarmsResumeFailed                    = "ALARMS_RESUME_FAILED"
	ErrAlarmsCountdownFailed                 = "ALARMS_COUNTDOWN_FAILED"
	ErrAlarmsLiveActivityRequired            = "ALARMS_LIVE_ACTIVITY_REQUIRED"
	ErrAlarmsAuthorizationUpdatesUnavailable = "ALARMS_AUTHORIZATION_UPDATES_UNAVAILABLE"
	ErrAlarmsAlarmUpdatesUnavailable         = "ALARMS_ALARM_UPDATES_UNAVAILABLE"
	ErrRestoreUnsupported                    = "ALARMS_RESTORE_UNSUPPORTED"
	ErrRestoreInvalidState                   = "ALARMS_RESTORE_INVALID_STATE"
	ErrOutcomeUnknown                        = "ALARMS_OUTCOME_UNKNOWN"
	ErrNativeBridgeUnavailable               = "ALARMS_NATIVE_BRIDGE_UNAVAILABLE"
	ErrInvalidResponse                       = "ALARMS_INVALID_RESPONSE"
	ErrTimeout                               = "ALARMS_TIMEOUT"
	ErrCancelled                             = "ALARMS_CANCELLED"
)
