package uitree

const (
	UI_TREE_UNSUPPORTED                  = "UI_TREE_UNSUPPORTED"
	UI_TREE_UNAVAILABLE                  = "UI_TREE_UNAVAILABLE"
	UI_TREE_ACCESSIBILITY_DISABLED       = "UI_TREE_ACCESSIBILITY_DISABLED"
	UI_TREE_ACCESSIBILITY_NOT_CONNECTED  = "UI_TREE_ACCESSIBILITY_NOT_CONNECTED"
	UI_TREE_ROOT_UNAVAILABLE            = "UI_TREE_ROOT_UNAVAILABLE"
	UI_TREE_ADB_UNAVAILABLE             = "UI_TREE_ADB_UNAVAILABLE"
	UI_TREE_SNAPSHOT_FAILED             = "UI_TREE_SNAPSHOT_FAILED"
	UI_TREE_SNAPSHOT_TOO_LARGE          = "UI_TREE_SNAPSHOT_TOO_LARGE"
	UI_TREE_TRUNCATED                   = "UI_TREE_TRUNCATED"
	UI_TREE_INVALID_REQUEST             = "UI_TREE_INVALID_REQUEST"
	UI_TREE_INVALID_SOURCE              = "UI_TREE_INVALID_SOURCE"
	UI_TREE_SNAPSHOT_NOT_FOUND          = "UI_TREE_SNAPSHOT_NOT_FOUND"
	UI_NODE_NOT_FOUND                   = "UI_NODE_NOT_FOUND"
	UI_NODE_STALE                       = "UI_NODE_STALE"
	UI_TREE_TIMEOUT                     = "UI_TREE_TIMEOUT"
	UI_TREE_CANCELLED                   = "UI_TREE_CANCELLED"
	UI_TREE_NATIVE_BRIDGE_UNAVAILABLE   = "UI_TREE_NATIVE_BRIDGE_UNAVAILABLE"
	UI_TREE_INVALID_RESPONSE            = "UI_TREE_INVALID_RESPONSE"
)

func MapUITreeErrorToCanonical(code string) string {
	switch code {
	case UI_TREE_UNSUPPORTED:
		return "PLATFORM_NOT_SUPPORTED"
	case UI_TREE_UNAVAILABLE:
		return "PROVIDER_UNAVAILABLE"
	case UI_TREE_ACCESSIBILITY_DISABLED, UI_TREE_ACCESSIBILITY_NOT_CONNECTED:
		return "PROVIDER_UNAVAILABLE"
	case UI_TREE_ROOT_UNAVAILABLE:
		return "PROVIDER_UNAVAILABLE"
	case UI_TREE_ADB_UNAVAILABLE:
		return "PROVIDER_UNAVAILABLE"
	case UI_TREE_SNAPSHOT_FAILED:
		return "PROVIDER_UNAVAILABLE"
	case UI_TREE_SNAPSHOT_TOO_LARGE:
		return "BRIDGE_INVALID_RESPONSE"
	case UI_TREE_TRUNCATED:
		return "BRIDGE_INVALID_RESPONSE"
	case UI_TREE_INVALID_REQUEST:
		return "AUTHORIZATION_DENIED"
	case UI_TREE_INVALID_SOURCE:
		return "AUTHORIZATION_DENIED"
	case UI_TREE_SNAPSHOT_NOT_FOUND:
		return "PROVIDER_UNAVAILABLE"
	case UI_NODE_NOT_FOUND:
		return "PROVIDER_UNAVAILABLE"
	case UI_NODE_STALE:
		return "BRIDGE_INVALID_RESPONSE"
	case UI_TREE_TIMEOUT:
		return "BRIDGE_TIMEOUT"
	case UI_TREE_CANCELLED:
		return "CANCELLED"
	case UI_TREE_NATIVE_BRIDGE_UNAVAILABLE:
		return "PROVIDER_UNAVAILABLE"
	case UI_TREE_INVALID_RESPONSE:
		return "BRIDGE_INVALID_RESPONSE"
	default:
		return "PROVIDER_UNAVAILABLE"
	}
}

const (
	PermissionUITreeRead    = "android.ui_tree.read"
	PermissionUITreeRootRead = "android.ui_tree.root_read"
)
