import { beforeEach, describe, expect, it, vi } from "vitest";
import { useOwnedMemoryManagement } from "../composables/useOwnedMemoryManagement";
const mocks = vi.hoisted(() => ({ get: vi.fn(), post: vi.fn() }));
vi.mock("../composables/useApi", () => ({ apiClient: mocks }));
describe("Owned 记忆管理归属及保存确认", () => {
  let scope: any;
  const resource = (kind = "memory", id = "same") => ({ kind, id, ownerId: "device", roleId: "role", revision: 1, body: { key: "茶", type: "owned-memory-candidate", state: "pending", content: { value: "喜欢茶" } } });
  const wrap = (data: any) => ({ data: { code: 200, data } });
  const result = (candidate = false, generate = false) => ({ resources: [resource(candidate ? "checkpoint" : "memory", candidate ? "memory-candidate/write/fact" : "same"), ...(candidate ? [] : [resource("fact", "same")])], executionScope: { ...scope, requestId: "write" }, saved: true, acknowledgement: { ownerId: "device", requestId: `write${generate ? "|candidate-result" : ""}`, versions: { "memory/same": 1, "fact/same": 1, "checkpoint/memory-candidate/write/fact": 1, [`checkpoint/${candidate ? "memory-candidate-operation" : "memory-management"}/write`]: generate ? 2 : 1 } } });
  beforeEach(() => { mocks.get.mockReset(); mocks.post.mockReset(); scope = { authorizationRealm: "realm", spaceId: "core", coreId: "core", roleId: "role", roleRevision: 1, roleOwnerId: "device", resourceOwnerId: "device", initiatorDeviceId: "device", targetDeviceId: "device", providerEpoch: 1, modeRevision: 1, permissionRevision: 1, targetPermissionRevision: 1, targetProviderEpoch: 1, coordinated: false, requestId: "read" }; });
  it("提交保留原完整 scope，不重新请求权限", async () => { mocks.post.mockResolvedValue(wrap(result())); await useOwnedMemoryManagement().write(scope, "write", { action: "create", key: "茶", value: "喜欢茶" }); expect(mocks.get).not.toHaveBeenCalled(); expect(mocks.post.mock.calls[0][1].expectedExecutionScope).toEqual(scope); });
  it.each(["realm", "core", "owner", "role", "cas", "checkpoint"])("拒绝 %s 不匹配的写入确认", async (field) => { const data = result(); if (field === "realm") data.executionScope.authorizationRealm = "other"; if (field === "core") data.executionScope.coreId = "other"; if (field === "owner") data.resources[0].ownerId = "other"; if (field === "role") data.resources[0].roleId = "other"; if (field === "cas") data.acknowledgement.versions["memory/same"] = 2; if (field === "checkpoint") delete data.acknowledgement.versions["checkpoint/memory-management/write"]; mocks.post.mockResolvedValue(wrap(data)); await expect(useOwnedMemoryManagement().write(scope, "write", { action: "create" })).rejects.toThrow(); });
  it("候选生成核验公开 UUID 与内部结果提交 ACK", async () => { mocks.post.mockResolvedValue(wrap(result(true, true))); await expect(useOwnedMemoryManagement().write(scope, "write", { action: "generate" }, true)).resolves.toHaveLength(1); const bad = result(true, true); bad.acknowledgement.requestId = "write"; mocks.post.mockResolvedValue(wrap(bad)); await expect(useOwnedMemoryManagement().write(scope, "write", { action: "generate" }, true)).rejects.toThrow("保存确认"); });
  it("同 ID 冲突记录不能来自另一设备", () => { expect(() => useOwnedMemoryManagement().conflicts({ response: { data: { conflicts: [{ ...resource(), ownerId: "other" }] } } }, scope)).toThrow("所属设备"); });
  it("检索拒绝同 ID 新 Core 范围", async () => { mocks.get.mockResolvedValue(wrap({ executionScope: { ...scope, coreId: "next" }, resources: [resource()] })); await expect(useOwnedMemoryManagement().read(scope, { query: "茶" })).rejects.toThrow("归属已变化"); });
  it("只有操作收据而无正式记忆版本时不能提示已保存", async () => { const data = result(); data.resources = []; mocks.post.mockResolvedValue(wrap(data)); await expect(useOwnedMemoryManagement().write(scope, "write", { action: "create" })).rejects.toThrow("原记录"); });
  it("候选确认缺少正式记忆及其派生层时拒绝确认", async () => { const data = result(true); data.resources[0].revision = 2; data.resources[0].body.state = "accepted"; data.acknowledgement.versions["checkpoint/memory-candidate/write/fact"] = 2; mocks.post.mockResolvedValue(wrap(data)); await expect(useOwnedMemoryManagement().write(scope, "write", { action: "accept", id: "memory-candidate/write/fact", expectedRevision: 1 }, true)).rejects.toThrow("正式记忆"); });
});
