package package_security

import "errors"

var (
	ErrInvalidArchive        = errors.New("package_security: invalid archive")
	ErrPathTraversal         = errors.New("package_security: path traversal detected")
	ErrAbsolutePath          = errors.New("package_security: absolute path not allowed")
	ErrPathTooLong           = errors.New("package_security: path too long")
	ErrPathDepthExceeded     = errors.New("package_security: directory depth exceeded")
	ErrWindowsReservedName   = errors.New("package_security: windows reserved name")
	ErrSizeLimitExceeded     = errors.New("package_security: size limit exceeded")
	ErrEntryCountExceeded    = errors.New("package_security: entry count exceeded")
	ErrCompressionRatioExceeded = errors.New("package_security: compression ratio exceeded")
	ErrSymlinkNotAllowed     = errors.New("package_security: symlink not allowed")
	ErrHardlinkNotAllowed    = errors.New("package_security: hardlink not allowed")
	ErrSpecialFileNotAllowed = errors.New("package_security: special file not allowed")
	ErrNestedArchiveNotAllowed = errors.New("package_security: nested archive not allowed")
	ErrForbiddenFileType     = errors.New("package_security: forbidden file type")
	ErrExecutableNotAllowed  = errors.New("package_security: executable not allowed")
	ErrDuplicatePath         = errors.New("package_security: duplicate path detected")
	ErrUnicodeCollision      = errors.New("package_security: unicode collision detected")
	ErrSignatureInvalid      = errors.New("package_security: signature invalid")
	ErrSignatureExpired      = errors.New("package_security: signature expired")
	ErrUnknownPublisher      = errors.New("package_security: unknown publisher")
	ErrPublisherBlocked      = errors.New("package_security: publisher blocked")
	ErrInvalidTrustLevel     = errors.New("package_security: invalid trust level")
	ErrStagingNotFound       = errors.New("package_security: staging not found")
	ErrStagingNotReady       = errors.New("package_security: staging not ready")
	ErrStagingNotSealed      = errors.New("package_security: staging not sealed")
	ErrStagingTampered       = errors.New("package_security: staging tampered")
	ErrCommitFailed          = errors.New("package_security: commit failed")
	ErrSnapshotNotFound      = errors.New("package_security: snapshot not found")
	ErrRollbackFailed        = errors.New("package_security: rollback failed")
	ErrRecoveryNeeded        = errors.New("package_security: recovery needed")
	ErrCleanupFailed         = errors.New("package_security: cleanup failed")
	ErrResourceNotFound      = errors.New("package_security: resource not found")
)
