package kernel

import (
	"context"
	"encoding/json"
	"time"

	"github.com/u-ai/backend/internal/browser"
	"github.com/u-ai/backend/internal/extension/kernel/capability"
)

func registerBrowserTools(registry *capability.ToolRegistry, provider browser.BrowserProvider) error {
	if registry == nil || provider == nil {
		return nil
	}
	caps := provider.BrowserCapabilities()
	tools := buildBrowserToolDefinitions(caps)
	for _, def := range tools {
		if err := registry.Replace(context.Background(), def); err != nil {
			return err
		}
	}
	return nil
}

func buildBrowserToolDefinitions(caps browser.BrowserCapabilities) []capability.ToolDefinition {
	runtime := capability.RuntimeBinding{
		RuntimeType: capability.RuntimeTypeBrowser,
		RuntimeID:   "default",
	}
	basePolicy := capability.ToolExecutionPolicy{
		Timeout:     60 * time.Second,
		Idempotent:  false,
		AllowBackground: false,
		RetryPolicy: capability.RetryPolicy{MaxRetries: 0},
	}
	resultPolicy := capability.ToolResultPolicy{
		SanitizeError:  true,
		MaxOutputBytes: 262144,
		Streaming:      capability.ToolStreamingPolicy{Enabled: false},
	}
	perms := []capability.PermissionRequirement{
		{Capability: "browser.runtime", Description: "Controls a browser instance"},
	}

	defs := make([]capability.ToolDefinition, 0, 24)

	if caps.SupportsNavigation {
		defs = append(defs,
			capability.ToolDefinition{
				ID:             "internal/browser/session.create",
				ModelName:      "browser_session_create",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Session Create",
				Description:    "Create a new browser session",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"sessionId":{"type":"string"},"state":{"type":"string"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskMedium,
				SideEffect:     capability.SideEffectSystem,
				HasSideEffects: true,
				Idempotent:     false,
				Retryable:      true,
				TimeoutMS:      30000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.session.create"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
			capability.ToolDefinition{
				ID:             "internal/browser/session.close",
				ModelName:      "browser_session_close",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Session Close",
				Description:    "Close a browser session",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId"],"properties":{"sessionId":{"type":"string"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"ok":{"type":"boolean"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskMedium,
				SideEffect:     capability.SideEffectSystem,
				HasSideEffects: true,
				Idempotent:     true,
				Retryable:      true,
				TimeoutMS:      15000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.session.close"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
			capability.ToolDefinition{
				ID:             "internal/browser/session.get",
				ModelName:      "browser_session_get",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Session Get",
				Description:    "Get browser session info",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId"],"properties":{"sessionId":{"type":"string"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"sessionId":{"type":"string"},"state":{"type":"string"},"url":{"type":"string"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskLow,
				SideEffect:     capability.SideEffectReadOnly,
				HasSideEffects: false,
				Idempotent:     true,
				Retryable:      true,
				TimeoutMS:      5000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.session.get"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
			capability.ToolDefinition{
				ID:             "internal/browser/session.list",
				ModelName:      "browser_session_list",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Session List",
				Description:    "List browser sessions",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"sessions":{"type":"array","items":{"type":"object"}}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskLow,
				SideEffect:     capability.SideEffectReadOnly,
				HasSideEffects: false,
				Idempotent:     true,
				Retryable:      true,
				TimeoutMS:      5000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.session.list"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
			capability.ToolDefinition{
				ID:             "internal/browser/tab.create",
				ModelName:      "browser_tab_create",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Tab Create",
				Description:    "Create a new browser tab",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId"],"properties":{"sessionId":{"type":"string"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"tabId":{"type":"string"},"sessionId":{"type":"string"},"url":{"type":"string"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskMedium,
				SideEffect:     capability.SideEffectSystem,
				HasSideEffects: true,
				Idempotent:     false,
				Retryable:      true,
				TimeoutMS:      15000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.tab.create"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
			capability.ToolDefinition{
				ID:             "internal/browser/tab.close",
				ModelName:      "browser_tab_close",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Tab Close",
				Description:    "Close a browser tab",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId","tabId"],"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"ok":{"type":"boolean"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskMedium,
				SideEffect:     capability.SideEffectSystem,
				HasSideEffects: true,
				Idempotent:     true,
				Retryable:      true,
				TimeoutMS:      15000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.tab.close"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
			capability.ToolDefinition{
				ID:             "internal/browser/tab.get",
				ModelName:      "browser_tab_get",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Tab Get",
				Description:    "Get browser tab info",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId","tabId"],"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"tabId":{"type":"string"},"sessionId":{"type":"string"},"url":{"type":"string"},"title":{"type":"string"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskLow,
				SideEffect:     capability.SideEffectReadOnly,
				HasSideEffects: false,
				Idempotent:     true,
				Retryable:      true,
				TimeoutMS:      5000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.tab.get"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
			capability.ToolDefinition{
				ID:             "internal/browser/tab.list",
				ModelName:      "browser_tab_list",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Tab List",
				Description:    "List browser tabs",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId"],"properties":{"sessionId":{"type":"string"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"tabs":{"type":"array","items":{"type":"object"}}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskLow,
				SideEffect:     capability.SideEffectReadOnly,
				HasSideEffects: false,
				Idempotent:     true,
				Retryable:      true,
				TimeoutMS:      5000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.tab.list"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
			capability.ToolDefinition{
				ID:             "internal/browser/tab.activate",
				ModelName:      "browser_tab_activate",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Tab Activate",
				Description:    "Activate a browser tab",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId","tabId"],"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"ok":{"type":"boolean"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskLow,
				SideEffect:     capability.SideEffectWrite,
				HasSideEffects: true,
				Idempotent:     true,
				Retryable:      true,
				TimeoutMS:      5000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.tab.activate"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
			capability.ToolDefinition{
				ID:             "internal/browser/navigate",
				ModelName:      "browser_navigate",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Navigate",
				Description:    "Navigate to a URL",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId","tabId","url"],"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"},"url":{"type":"string"},"waitUntil":{"type":"string"},"timeoutMs":{"type":"integer"},"referer":{"type":"string"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"},"requestedUrl":{"type":"string"},"finalUrl":{"type":"string"},"title":{"type":"string"},"loaded":{"type":"boolean"},"timedOut":{"type":"boolean"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskHigh,
				SideEffect:     capability.SideEffectExternal,
				HasSideEffects: true,
				Idempotent:     false,
				Retryable:      true,
				TimeoutMS:      60000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.navigate"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
			capability.ToolDefinition{
				ID:             "internal/browser/navigate.reload",
				ModelName:      "browser_navigate_reload",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Reload",
				Description:    "Reload current page",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId","tabId"],"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"},"waitUntil":{"type":"string"},"timeoutMs":{"type":"integer"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"},"finalUrl":{"type":"string"},"loaded":{"type":"boolean"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskMedium,
				SideEffect:     capability.SideEffectExternal,
				HasSideEffects: true,
				Idempotent:     false,
				Retryable:      true,
				TimeoutMS:      60000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.navigate.reload"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
			capability.ToolDefinition{
				ID:             "internal/browser/navigate.back",
				ModelName:      "browser_navigate_back",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Back",
				Description:    "Go back in browser history",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId","tabId"],"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"},"finalUrl":{"type":"string"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskMedium,
				SideEffect:     capability.SideEffectExternal,
				HasSideEffects: true,
				Idempotent:     false,
				Retryable:      true,
				TimeoutMS:      30000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.navigate.back"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
			capability.ToolDefinition{
				ID:             "internal/browser/navigate.forward",
				ModelName:      "browser_navigate_forward",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Forward",
				Description:    "Go forward in browser history",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId","tabId"],"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"},"finalUrl":{"type":"string"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskMedium,
				SideEffect:     capability.SideEffectExternal,
				HasSideEffects: true,
				Idempotent:     false,
				Retryable:      true,
				TimeoutMS:      30000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.navigate.forward"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
			capability.ToolDefinition{
				ID:             "internal/browser/navigate.stop",
				ModelName:      "browser_navigate_stop",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Stop",
				Description:    "Stop loading current page",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId","tabId"],"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"ok":{"type":"boolean"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskMedium,
				SideEffect:     capability.SideEffectWrite,
				HasSideEffects: true,
				Idempotent:     true,
				Retryable:      true,
				TimeoutMS:      15000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.navigate.stop"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
		)
	}

	if caps.SupportsDOM {
		defs = append(defs,
			capability.ToolDefinition{
				ID:             "internal/browser/dom.snapshot",
				ModelName:      "browser_dom_snapshot",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser DOM Snapshot",
				Description:    "Get DOM snapshot of the page",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId","tabId"],"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"},"maxDepth":{"type":"integer"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"},"url":{"type":"string"},"content":{"type":"string"},"truncated":{"type":"boolean"},"nodeCount":{"type":"integer"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskLow,
				SideEffect:     capability.SideEffectReadOnly,
				HasSideEffects: false,
				Idempotent:     true,
				Retryable:      true,
				TimeoutMS:      30000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.dom.snapshot"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
			capability.ToolDefinition{
				ID:             "internal/browser/dom.find",
				ModelName:      "browser_dom_find",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Find Element",
				Description:    "Find an element on the page",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId","tabId","selector"],"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"},"selector":{"type":"string"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"},"stableId":{"type":"string"},"selector":{"type":"string"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskLow,
				SideEffect:     capability.SideEffectReadOnly,
				HasSideEffects: false,
				Idempotent:     true,
				Retryable:      true,
				TimeoutMS:      15000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.dom.find"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
			capability.ToolDefinition{
				ID:             "internal/browser/dom.scrollToElement",
				ModelName:      "browser_dom_scroll_to_element",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Scroll To Element",
				Description:    "Scroll to an element on the page",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId","tabId","element"],"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"},"element":{"type":"object"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"ok":{"type":"boolean"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskLow,
				SideEffect:     capability.SideEffectWrite,
				HasSideEffects: true,
				Idempotent:     true,
				Retryable:      true,
				TimeoutMS:      15000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.dom.scrollToElement"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
		)
	}

	if caps.SupportsInteraction {
		defs = append(defs,
			capability.ToolDefinition{
				ID:             "internal/browser/interact.click",
				ModelName:      "browser_interact_click",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Click",
				Description:    "Click an element",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId","tabId","element"],"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"},"element":{"type":"object"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"success":{"type":"boolean"},"action":{"type":"string"},"verified":{"type":"boolean"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskHigh,
				SideEffect:     capability.SideEffectWrite,
				HasSideEffects: true,
				Idempotent:     false,
				Retryable:      true,
				TimeoutMS:      30000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.interact.click"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
			capability.ToolDefinition{
				ID:             "internal/browser/interact.input",
				ModelName:      "browser_interact_input",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Input",
				Description:    "Input text into an element",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId","tabId","element","inputText"],"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"},"element":{"type":"object"},"inputText":{"type":"string"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"success":{"type":"boolean"},"action":{"type":"string"},"verified":{"type":"boolean"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskHigh,
				SideEffect:     capability.SideEffectWrite,
				HasSideEffects: true,
				Idempotent:     false,
				Retryable:      true,
				TimeoutMS:      30000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.interact.input"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
			capability.ToolDefinition{
				ID:             "internal/browser/interact.select",
				ModelName:      "browser_interact_select",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Select",
				Description:    "Select a value on an element",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId","tabId","element","value"],"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"},"element":{"type":"object"},"value":{"type":"string"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"success":{"type":"boolean"},"action":{"type":"string"},"verified":{"type":"boolean"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskHigh,
				SideEffect:     capability.SideEffectWrite,
				HasSideEffects: true,
				Idempotent:     false,
				Retryable:      true,
				TimeoutMS:      30000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.interact.select"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
			capability.ToolDefinition{
				ID:             "internal/browser/interact.hover",
				ModelName:      "browser_interact_hover",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Hover",
				Description:    "Hover over an element",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId","tabId","element"],"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"},"element":{"type":"object"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"success":{"type":"boolean"},"action":{"type":"string"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskMedium,
				SideEffect:     capability.SideEffectWrite,
				HasSideEffects: true,
				Idempotent:     false,
				Retryable:      true,
				TimeoutMS:      15000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.interact.hover"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
			capability.ToolDefinition{
				ID:             "internal/browser/interact.scroll",
				ModelName:      "browser_interact_scroll",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Scroll",
				Description:    "Scroll the page",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId","tabId","direction"],"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"},"direction":{"type":"string"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"success":{"type":"boolean"},"action":{"type":"string"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskLow,
				SideEffect:     capability.SideEffectWrite,
				HasSideEffects: true,
				Idempotent:     false,
				Retryable:      true,
				TimeoutMS:      15000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.interact.scroll"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
		)
	}

	if caps.SupportsDownload {
		defs = append(defs,
			capability.ToolDefinition{
				ID:             "internal/browser/resource.download",
				ModelName:      "browser_resource_download",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Download",
				Description:    "Download a resource",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId","tabId","resourceURI"],"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"},"resourceURI":{"type":"string"},"filename":{"type":"string"},"waitTimeoutMs":{"type":"integer"},"overwrite":{"type":"boolean"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"resourceURI":{"type":"string"},"filename":{"type":"string"},"sizeBytes":{"type":"integer"},"contentType":{"type":"string"},"contentHash":{"type":"string"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskHigh,
				SideEffect:     capability.SideEffectExternal,
				HasSideEffects: true,
				Idempotent:     false,
				Retryable:      true,
				TimeoutMS:      120000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.resource.download"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
		)
	}

	if caps.SupportsUpload {
		defs = append(defs,
			capability.ToolDefinition{
				ID:             "internal/browser/resource.upload",
				ModelName:      "browser_resource_upload",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Upload",
				Description:    "Upload a resource",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId","tabId","resourceURI"],"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"},"resourceURI":{"type":"string"},"targetInput":{"type":"string"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"resourceURI":{"type":"string"},"success":{"type":"boolean"},"fileSet":{"type":"boolean"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskHigh,
				SideEffect:     capability.SideEffectExternal,
				HasSideEffects: true,
				Idempotent:     false,
				Retryable:      true,
				TimeoutMS:      120000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.resource.upload"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
		)
	}

	if caps.SupportsScreenshot {
		defs = append(defs,
			capability.ToolDefinition{
				ID:             "internal/browser/resource.screenshot",
				ModelName:      "browser_resource_screenshot",
				Source:         capability.ToolSourceInternal,
				Name:           "Browser Screenshot",
				Description:    "Take a screenshot of the page",
				InputSchema:    json.RawMessage(`{"type":"object","additionalProperties":false,"required":["sessionId","tabId"],"properties":{"sessionId":{"type":"string"},"tabId":{"type":"string"},"format":{"type":"string"},"quality":{"type":"integer"},"fullPage":{"type":"boolean"}}}`),
				OutputSchema:   json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"resourceURI":{"type":"string"},"width":{"type":"integer"},"height":{"type":"integer"},"format":{"type":"string"},"sizeBytes":{"type":"integer"}}}`),
				Permissions:    perms,
				RiskLevel:      capability.RiskMedium,
				SideEffect:     capability.SideEffectReadOnly,
				HasSideEffects: false,
				Idempotent:     true,
				Retryable:      true,
				TimeoutMS:      30000,
				Enabled:        true,
				Runtime:        capability.RuntimeBinding{RuntimeType: runtime.RuntimeType, RuntimeID: runtime.RuntimeID, HandlerName: "browser.resource.screenshot"},
				ExecutionPolicy: basePolicy,
				ResultPolicy:    resultPolicy,
			},
		)
	}

	return defs
}

func mapBrowserDomainError(err error) *capability.ToolError {
	if err == nil {
		return nil
	}
	browserErr, ok := err.(*browser.BrowserError)
	if !ok {
		return &capability.ToolError{
			Code:        capability.ErrorCodeExecutionFailed,
			Message:     err.Error(),
			UserVisible: false,
		}
	}
	code := capability.ErrorCodeExecutionFailed
	retryable := false
	switch browserErr.Code {
	case browser.ErrCodeInvalidInput:
		code = capability.ErrorCodeInvalidInput
	case browser.ErrCodePermissionDenied:
		code = capability.ErrorCodePermissionDenied
	case browser.ErrCodeSessionNotFound,
		browser.ErrCodeTabNotFound,
		browser.ErrCodeBrowserExecNotFound:
		code = capability.ErrorCodeNotAvailable
	case browser.ErrCodeBrowserDisabled,
		browser.ErrCodeBrowserRuntimeNotReady,
		browser.ErrCodeProviderUnavailable:
		code = capability.ErrorCodeRuntimeUnavailable
	case browser.ErrCodeSessionLimitReached,
		browser.ErrCodeTabQuotaReached:
		code = capability.ErrorCodeRateLimited
	case browser.ErrCodeUnsupportedAction:
		code = capability.ErrorCodeNotAvailable
	case browser.ErrCodeNavigationTimeout,
		browser.ErrCodeDownloadTimeout:
		code = capability.ErrorCodeTimeout
		retryable = true
	case browser.ErrCodeStaleElement,
		browser.ErrCodeSessionStale,
		browser.ErrCodeTabStale:
		retryable = true
	}
	return &capability.ToolError{
		Code:        code,
		Message:     browserErr.Message,
		DomainCode:  string(browserErr.Code),
		Retryable:   retryable,
		UserVisible: true,
		Cause:       browserErr.Unwrap(),
	}
}
