package kernel

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/u-ai/backend/internal/extension/kernel/builtin"
	"github.com/u-ai/backend/internal/extension/kernel/persistence/sqlite"
	"github.com/u-ai/backend/internal/extension/kernel/schema_ui"
	"github.com/u-ai/backend/internal/extension/kernel/ui_contribution"
	uischema "github.com/u-ai/backend/internal/uiagent/schema"
)

type uiAgentPublisher struct {
	root     string
	registry *schema_ui.SchemaRegistry
	repo     *sqlite.SQLiteUIContributionRepository
	host     *ui_contribution.UIHost
}

func newUIAgentPublisher(root string, registry *schema_ui.SchemaRegistry, repo *sqlite.SQLiteUIContributionRepository, host *ui_contribution.UIHost) builtin.UIAgentPublisher {
	return &uiAgentPublisher{root: root, registry: registry, repo: repo, host: host}
}

func (p *uiAgentPublisher) Publish(ctx context.Context, workspaceID string, doc *uischema.SchemaUIDocument) (builtin.UIAgentPublishResult, error) {
	if p == nil || p.registry == nil || p.repo == nil || p.host == nil || strings.TrimSpace(p.root) == "" {
		return builtin.UIAgentPublishResult{}, fmt.Errorf("uiagent publisher: canonical publish services unavailable")
	}
	if doc == nil {
		return builtin.UIAgentPublishResult{}, fmt.Errorf("uiagent publisher: schema document is nil")
	}
	raw, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return builtin.UIAgentPublishResult{}, fmt.Errorf("uiagent publisher: marshal schema: %w", err)
	}
	docHash := sha256.Sum256(raw)
	identityHash := sha256.Sum256(append([]byte(workspaceID+"\x00"), raw...))
	shortID := hex.EncodeToString(identityHash[:8])
	pageID := "uiagent-" + shortID
	contributionID := "uiagent.generated." + shortID
	extensionID := string(builtin.UIAgentExtensionID)
	moduleID := string(builtin.UIAgentModuleID)

	baseDir := filepath.Join(p.root, "uiagent-generated")
	schemaRel := filepath.Join("generated", pageID+".schema.json")
	schemaPath := filepath.Join(baseDir, schemaRel)
	if err := os.MkdirAll(filepath.Dir(schemaPath), 0o755); err != nil {
		return builtin.UIAgentPublishResult{}, fmt.Errorf("uiagent publisher: create schema directory: %w", err)
	}
	tmp := schemaPath + ".tmp"
	if err := os.WriteFile(tmp, raw, 0o644); err != nil {
		return builtin.UIAgentPublishResult{}, fmt.Errorf("uiagent publisher: write schema: %w", err)
	}
	if err := os.Rename(tmp, schemaPath); err != nil {
		_ = os.Remove(tmp)
		return builtin.UIAgentPublishResult{}, fmt.Errorf("uiagent publisher: publish schema file: %w", err)
	}

	if err := p.registry.RegisterSchema(extensionID, pageID, doc); err != nil {
		_ = os.Remove(schemaPath)
		return builtin.UIAgentPublishResult{}, fmt.Errorf("uiagent publisher: register canonical schema: %w", err)
	}

	title := strings.TrimSpace(doc.Title)
	if title == "" {
		title = "Generated UI"
	}
	hashText := "sha256:" + hex.EncodeToString(docHash[:])
	def := &ui_contribution.UIContributionDefinition{
		ContributionID:  ui_contribution.ContributionID(contributionID),
		ExtensionID:     ui_contribution.ExtensionID(extensionID),
		ModuleID:        ui_contribution.ModuleID(moduleID),
		Kind:            ui_contribution.UIContributionSchemaPage,
		Slot:            ui_contribution.UISlotReference{SlotID: "extension.settings.page", ContractVersion: 1},
		ContractVersion: 1,
		Display: ui_contribution.UIDisplayMetadata{
			Title:       ui_contribution.LocalizedText{Default: title},
			Description: ui_contribution.LocalizedText{Default: "Generated by Amitia UI Agent for workspace " + workspaceID},
		},
		Entry: ui_contribution.UIEntryDefinition{
			Type:        ui_contribution.SandboxSchemaRenderer,
			Path:        schemaRel,
			SchemaPath:  schemaRel,
			ContentHash: hashText,
		},
		Sandbox:   ui_contribution.UISandboxPolicy{Type: ui_contribution.SandboxSchemaRenderer},
		Lifecycle: ui_contribution.UILifecyclePolicy{Initial: string(ui_contribution.UIStateRegistered)},
		Integrity: ui_contribution.ContributionIntegrity{
			DefinitionHash: hashText,
			EntryHash:      hashText,
			SchemaHash:     hashText,
			Generation:     time.Now().UTC().UnixNano(),
		},
	}
	if old, getErr := p.host.GetContribution(def.ContributionID); getErr == nil && old != nil {
		_ = p.host.UnregisterContribution(def.ContributionID)
	}
	if err := p.host.RegisterContribution(def); err != nil {
		p.registry.UnregisterSchema(extensionID, pageID)
		_ = os.Remove(schemaPath)
		return builtin.UIAgentPublishResult{}, fmt.Errorf("uiagent publisher: register UI contribution: %w", err)
	}
	if err := p.repo.PutContribution(ctx, def); err != nil {
		_ = p.host.UnregisterContribution(def.ContributionID)
		p.registry.UnregisterSchema(extensionID, pageID)
		_ = os.Remove(schemaPath)
		return builtin.UIAgentPublishResult{}, fmt.Errorf("uiagent publisher: persist UI contribution: %w", err)
	}
	return builtin.UIAgentPublishResult{SchemaID: pageID, ContributionID: contributionID}, nil
}
