package ffmpeg

const (
	FFMPEG_UNAVAILABLE             = "FFMPEG_UNAVAILABLE"
	FFMPEG_BINARY_NOT_FOUND        = "FFMPEG_BINARY_NOT_FOUND"
	FFMPEG_BINARY_INVALID          = "FFMPEG_BINARY_INVALID"
	FFMPEG_BINARY_INTEGRITY_FAILED = "FFMPEG_BINARY_INTEGRITY_FAILED"
	FFMPEG_ARCH_MISMATCH           = "FFMPEG_ARCH_MISMATCH"

	FFPROBE_NOT_FOUND = "FFPROBE_NOT_FOUND"
	FFPROBE_INVALID   = "FFPROBE_INVALID"

	FFMPEG_RUNTIME_UNAVAILABLE       = "FFMPEG_RUNTIME_UNAVAILABLE"
	FFMPEG_PROCESS_SPAWN_UNSUPPORTED = "FFMPEG_PROCESS_SPAWN_UNSUPPORTED"

	FFMPEG_PROCESS_FAILED   = "FFMPEG_PROCESS_FAILED"
	FFMPEG_PROCESS_TIMEOUT  = "FFMPEG_PROCESS_TIMEOUT"
	FFMPEG_PROCESS_CANCELLED = "FFMPEG_PROCESS_CANCELLED"

	FFMPEG_PROTOCOL_FORBIDDEN = "FFMPEG_PROTOCOL_FORBIDDEN"
	FFMPEG_OUTPUT_TOO_LARGE   = "FFMPEG_OUTPUT_TOO_LARGE"
	FFMPEG_STDOUT_TOO_LARGE   = "FFMPEG_STDOUT_TOO_LARGE"
	FFMPEG_STDERR_TOO_LARGE   = "FFMPEG_STDERR_TOO_LARGE"

	FFMPEG_INVALID_PROBE_OUTPUT = "FFMPEG_INVALID_PROBE_OUTPUT"

	MEDIA_UNAVAILABLE = "MEDIA_UNAVAILABLE"

	MEDIA_METADATA_FAILED           = "MEDIA_METADATA_FAILED"
	MEDIA_METADATA_TIMEOUT          = "MEDIA_METADATA_TIMEOUT"
	MEDIA_METADATA_OUTPUT_TOO_LARGE = "MEDIA_METADATA_OUTPUT_TOO_LARGE"
	MEDIA_METADATA_INVALID          = "MEDIA_METADATA_INVALID"

	MEDIA_FORMAT_UNSUPPORTED    = "MEDIA_FORMAT_UNSUPPORTED"
	MEDIA_CONTAINER_UNSUPPORTED = "MEDIA_CONTAINER_UNSUPPORTED"

	MEDIA_VIDEO_CODEC_UNSUPPORTED   = "MEDIA_VIDEO_CODEC_UNSUPPORTED"
	MEDIA_AUDIO_CODEC_UNSUPPORTED   = "MEDIA_AUDIO_CODEC_UNSUPPORTED"
	MEDIA_SUBTITLE_CODEC_UNSUPPORTED = "MEDIA_SUBTITLE_CODEC_UNSUPPORTED"

	MEDIA_CODEC_CONTAINER_INCOMPATIBLE = "MEDIA_CODEC_CONTAINER_INCOMPATIBLE"

	MEDIA_TRANSCODE_REQUIRED       = "MEDIA_TRANSCODE_REQUIRED"
	MEDIA_VIDEO_TRANSCODE_REQUIRED = "MEDIA_VIDEO_TRANSCODE_REQUIRED"
	MEDIA_AUDIO_TRANSCODE_REQUIRED = "MEDIA_AUDIO_TRANSCODE_REQUIRED"

	MEDIA_CONVERSION_INVALID   = "MEDIA_CONVERSION_INVALID"
	MEDIA_CONVERSION_FAILED    = "MEDIA_CONVERSION_FAILED"
	MEDIA_CONVERSION_TIMEOUT   = "MEDIA_CONVERSION_TIMEOUT"
	MEDIA_CONVERSION_CANCELLED = "MEDIA_CONVERSION_CANCELLED"

	MEDIA_RESOLUTION_INVALID      = "MEDIA_RESOLUTION_INVALID"
	MEDIA_RESOLUTION_TOO_LARGE    = "MEDIA_RESOLUTION_TOO_LARGE"
	MEDIA_FRAME_RATE_INVALID      = "MEDIA_FRAME_RATE_INVALID"
	MEDIA_PIXEL_FORMAT_UNSUPPORTED = "MEDIA_PIXEL_FORMAT_UNSUPPORTED"

	MEDIA_BITRATE_INVALID        = "MEDIA_BITRATE_INVALID"
	MEDIA_SAMPLE_RATE_INVALID    = "MEDIA_SAMPLE_RATE_INVALID"
	MEDIA_CHANNEL_LAYOUT_INVALID = "MEDIA_CHANNEL_LAYOUT_INVALID"

	MEDIA_HDR_PRESERVATION_UNSUPPORTED = "MEDIA_HDR_PRESERVATION_UNSUPPORTED"
	MEDIA_ORIENTATION_INVALID          = "MEDIA_ORIENTATION_INVALID"

	MEDIA_TRIM_INVALID                    = "MEDIA_TRIM_INVALID"
	MEDIA_PRECISE_TRIM_REQUIRES_TRANSCODE = "MEDIA_PRECISE_TRIM_REQUIRES_TRANSCODE"

	MEDIA_METADATA_POLICY_INVALID  = "MEDIA_METADATA_POLICY_INVALID"
	MEDIA_METADATA_KEY_UNSUPPORTED = "MEDIA_METADATA_KEY_UNSUPPORTED"
	MEDIA_METADATA_VALUE_TOO_LARGE = "MEDIA_METADATA_VALUE_TOO_LARGE"

	MEDIA_STREAM_NOT_FOUND     = "MEDIA_STREAM_NOT_FOUND"
	MEDIA_STREAM_TYPE_MISMATCH = "MEDIA_STREAM_TYPE_MISMATCH"

	MEDIA_OUTPUT_TOO_LARGE      = "MEDIA_OUTPUT_TOO_LARGE"
	MEDIA_INPUT_TOO_LARGE       = "MEDIA_INPUT_TOO_LARGE"
	MEDIA_DISK_SPACE_INSUFFICIENT = "MEDIA_DISK_SPACE_INSUFFICIENT"

	MEDIA_BACKEND_UNAVAILABLE        = "MEDIA_BACKEND_UNAVAILABLE"
	MEDIA_BACKEND_CAPABILITY_MISSING = "MEDIA_BACKEND_CAPABILITY_MISSING"

	MEDIA_OUTPUT_VERIFY_FAILED      = "MEDIA_OUTPUT_VERIFY_FAILED"
	MEDIA_OUTPUT_CONTAINER_MISMATCH = "MEDIA_OUTPUT_CONTAINER_MISMATCH"
	MEDIA_OUTPUT_STREAM_MISSING     = "MEDIA_OUTPUT_STREAM_MISSING"

	MEDIA_RESOURCE_UNAVAILABLE        = "MEDIA_RESOURCE_UNAVAILABLE"
	MEDIA_RESOURCE_MATERIALIZE_FAILED = "MEDIA_RESOURCE_MATERIALIZE_FAILED"
	MEDIA_RESOURCE_COMMIT_FAILED      = "MEDIA_RESOURCE_COMMIT_FAILED"

	MEDIA_OVERWRITE_REQUIRED = "MEDIA_OVERWRITE_REQUIRED"
	MEDIA_OUTCOME_UNKNOWN    = "MEDIA_OUTCOME_UNKNOWN"

	MinimumSupportedFFmpegVersion = "4.0"
)

type Error struct {
	Code    string
	Message string
}

func (e *Error) Error() string {
	if e == nil {
		return ""
	}
	return e.Code + ": " + e.Message
}

func NewError(code, message string) *Error {
	return &Error{Code: code, Message: message}
}
