package ffmpeg

const (
	FFMPEG_UNAVAILABLE             = "FFMPEG_UNAVAILABLE"
	FFMPEG_BINARY_NOT_FOUND        = "FFMPEG_BINARY_NOT_FOUND"
	FFMPEG_BINARY_INVALID          = "FFMPEG_BINARY_INVALID"
	FFMPEG_BINARY_INTEGRITY_FAILED = "FFMPEG_BINARY_INTEGRITY_FAILED"
	FFMPEG_ARCH_MISMATCH           = "FFMPEG_ARCH_MISMATCH"

	FFPROBE_NOT_FOUND = "FFPROBE_NOT_FOUND"
	FFPROBE_INVALID   = "FFPROBE_INVALID"

	FFMPEG_RUNTIME_UNAVAILABLE    = "FFMPEG_RUNTIME_UNAVAILABLE"
	FFMPEG_PROCESS_SPAWN_UNSUPPORTED = "FFMPEG_PROCESS_SPAWN_UNSUPPORTED"

	FFMPEG_PROCESS_FAILED   = "FFMPEG_PROCESS_FAILED"
	FFMPEG_PROCESS_TIMEOUT  = "FFMPEG_PROCESS_TIMEOUT"
	FFMPEG_PROCESS_CANCELLED = "FFMPEG_PROCESS_CANCELLED"

	FFMPEG_PROTOCOL_FORBIDDEN  = "FFMPEG_PROTOCOL_FORBIDDEN"
	FFMPEG_OUTPUT_TOO_LARGE    = "FFMPEG_OUTPUT_TOO_LARGE"
	FFMPEG_STDOUT_TOO_LARGE    = "FFMPEG_STDOUT_TOO_LARGE"
	FFMPEG_STDERR_TOO_LARGE    = "FFMPEG_STDERR_TOO_LARGE"

	FFMPEG_INVALID_PROBE_OUTPUT = "FFMPEG_INVALID_PROBE_OUTPUT"

	MinimumSupportedFFmpegVersion = "4.0"
)

type Error struct {
	Code    string
	Message string
}

func (e *Error) Error() string {
	if e == nil {
		return ""
	}
	return e.Code + ": " + e.Message
}

func NewError(code, message string) *Error {
	return &Error{Code: code, Message: message}
}
