package clipboard

const (
	ErrClipboardUnsupported             = "CLIPBOARD_UNSUPPORTED"
	ErrClipboardUnavailable             = "CLIPBOARD_UNAVAILABLE"
	ErrClipboardEmpty                   = "CLIPBOARD_EMPTY"
	ErrDetectionUnsupported             = "CLIPBOARD_DETECTION_UNSUPPORTED"
	ErrDetectionFailed                  = "CLIPBOARD_DETECTION_FAILED"
	ErrReadNotAllowed                   = "CLIPBOARD_READ_NOT_ALLOWED"
	ErrReadUserIntentRequired           = "CLIPBOARD_READ_USER_INTENT_REQUIRED"
	ErrReadPermissionDenied             = "CLIPBOARD_READ_PERMISSION_DENIED"
	ErrReadFailed                       = "CLIPBOARD_READ_FAILED"
	ErrItemNotFound                     = "CLIPBOARD_ITEM_NOT_FOUND"
	ErrItemStale                        = "CLIPBOARD_ITEM_STALE"
	ErrTypeUnsupported                  = "CLIPBOARD_TYPE_UNSUPPORTED"
	ErrRepresentationUnavailable        = "CLIPBOARD_REPRESENTATION_UNAVAILABLE"
	ErrValueDecodingFailed              = "CLIPBOARD_VALUE_DECODING_FAILED"
	ErrImportFailed                     = "CLIPBOARD_IMPORT_FAILED"
	ErrMaterializationCancelled         = "CLIPBOARD_MATERIALIZATION_CANCELLED"
	ErrMaterializationFailed            = "CLIPBOARD_MATERIALIZATION_FAILED"
	ErrContentTooLarge                  = "CLIPBOARD_CONTENT_TOO_LARGE"
	ErrWriteFailed                      = "CLIPBOARD_WRITE_FAILED"
	ErrWritePermissionDenied            = "CLIPBOARD_WRITE_PERMISSION_DENIED"
	ErrWriteTypeNotAllowed              = "CLIPBOARD_WRITE_TYPE_NOT_ALLOWED"
	ErrWriteValueRequired               = "CLIPBOARD_WRITE_VALUE_REQUIRED"
	ErrWriteValueInvalid                = "CLIPBOARD_WRITE_VALUE_INVALID"
	ErrWriteItemLimitExceeded           = "CLIPBOARD_WRITE_ITEM_LIMIT_EXCEEDED"
	ErrURLTooLong                       = "CLIPBOARD_URL_TOO_LONG"
	ErrClearFailed                      = "CLIPBOARD_CLEAR_FAILED"
	ErrClearNotAllowed                  = "CLIPBOARD_CLEAR_NOT_ALLOWED"
	ErrRestoreUnsupported               = "CLIPBOARD_RESTORE_UNSUPPORTED"
	ErrRestoreInvalidState              = "CLIPBOARD_RESTORE_INVALID_STATE"
	ErrSensitiveBlocked                 = "CLIPBOARD_SENSITIVE_BLOCKED"
	ErrSensitiveAuditPersisted          = "CLIPBOARD_SENSITIVE_AUDIT_PERSISTED"
	ErrSensitiveMissingAudit            = "CLIPBOARD_SENSITIVE_MISSING_AUDIT"
	ErrSensitiveMissingManualApproval   = "CLIPBOARD_SENSITIVE_MISSING_MANUAL_APPROVAL"
	ErrSecretWriteNotConfirmed          = "CLIPBOARD_SECRET_WRITE_NOT_CONFIRMED"
	ErrPeripheralRoleUnsupported        = "CLIPBOARD_PERIPHERAL_ROLE_UNSUPPORTED"
	ErrPeripheralRoleDisabled           = "CLIPBOARD_PERIPHERAL_ROLE_DISABLED"
	ErrAdvertisingFailed                = "CLIPBOARD_ADVERTISING_FAILED"
	ErrServicePublishFailed             = "CLIPBOARD_SERVICE_PUBLISH_FAILED"
	ErrUpdateValueFailed                = "CLIPBOARD_UPDATE_VALUE_FAILED"
	ErrOutcomeUnknown                   = "CLIPBOARD_OUTCOME_UNKNOWN"
	ErrNativeBridgeUnavailable          = "CLIPBOARD_NATIVE_BRIDGE_UNAVAILABLE"
	ErrInvalidResponse                  = "CLIPBOARD_INVALID_RESPONSE"
	ErrTimeout                          = "CLIPBOARD_TIMEOUT"
	ErrCancelled                        = "CLIPBOARD_CANCELLED"
)
