package nativebridge

const (
	ErrProviderUnavailable    = "PROVIDER_UNAVAILABLE"
	ErrAuthorizationDenied    = "AUTHORIZATION_DENIED"
	ErrUserActionRequired     = "USER_ACTION_REQUIRED"
	ErrPlatformNotSupported   = "PLATFORM_NOT_SUPPORTED"
	ErrBridgeDisconnected     = "BRIDGE_DISCONNECTED"
	ErrBridgeTimeout          = "BRIDGE_TIMEOUT"
	ErrBridgeInvalidResponse  = "BRIDGE_INVALID_RESPONSE"
	ErrOperationNotSupported  = "OPERATION_NOT_SUPPORTED"
	ErrInvalidArgument        = "INVALID_ARGUMENT"
	ErrInternalError          = "INTERNAL_ERROR"
	ErrTimeout                = "TIMEOUT"
	ErrInvalidResponse        = "INVALID_RESPONSE"
	ErrStaleNativeReference   = "STALE_NATIVE_REFERENCE"
	ErrHostUnavailable        = "HOST_UNAVAILABLE"
	ErrExecNotSupported       = "EXEC_NOT_SUPPORTED"
	ErrExecFailed             = "EXEC_FAILED"
	ErrExecTimeout            = "EXEC_TIMEOUT"
	ErrPermissionRequired     = "PERMISSION_REQUIRED"
	ErrForegroundRequired     = "FOREGROUND_REQUIRED"
	ErrCapabilityUnavailable  = "CAPABILITY_UNAVAILABLE"
	ErrResourceExportFailed   = "RESOURCE_EXPORT_FAILED"
	ErrShareFailed            = "SHARE_FAILED"
	ErrShortcutNotSupported   = "SHORTCUT_NOT_SUPPORTED"
	ErrAlarmUnsupported       = "ALARM_UNSUPPORTED"
	ErrFileAccessDenied       = "FILE_ACCESS_DENIED"
	ErrFileNotFound           = "FILE_NOT_FOUND"
	ErrMediaCaptureFailed     = "MEDIA_CAPTURE_FAILED"
	ErrBackgroundTaskFailed   = "BACKGROUND_TASK_FAILED"
)
