export type PackageErrorCode =
  | "PET_IDENTITY_CONFLICT"
  | "RELEASE_VERSION_CONFLICT"
  | "RELEASE_CONTENT_CONFLICT"
  | "PACKAGE_SCHEMA_UNSUPPORTED"
  | "PACKAGE_SCHEMA_MISSING"
  | "PACKAGE_MANIFEST_INVALID"
  | "PACKAGE_PATH_INVALID"
  | "PACKAGE_ARCHIVE_BOMB"
  | "PACKAGE_DUPLICATE_ENTRY"
  | "PACKAGE_EXECUTABLE_FORBIDDEN"
  | "PACKAGE_SYMLINK_FORBIDDEN"
  | "PACKAGE_HASH_MISMATCH"
  | "PACKAGE_FILE_UNDECLARED"
  | "PACKAGE_FILE_MISSING"
  | "PACKAGE_RUNTIME_INCOMPATIBLE"
  | "PACKAGE_QUALITY_GATE_BLOCKED"
  | "PACKAGE_BINDING_NOT_ALLOWED"
  | "ACTION_CONFIG_MISSING"
  | "ACTION_CONFIG_INVALID"
  | "ACTION_REFERENCE_INVALID"
  | "FRAME_MISSING"
  | "FRAME_HASH_MISMATCH"
  | "PATH_ESCAPE_REJECTED"
  | "DEFAULT_ACTION_INVALID"
  | "RUNTIME_VERSION_UNSUPPORTED"
  | "PACKAGE_JSON_DUPLICATE_KEY"
  | "PACKAGE_JSON_UNKNOWN_FIELD"
  | "PACKAGE_MANIFEST_HASH_MISSING"
  | "PACKAGE_MANIFEST_HASH_MISMATCH"
  | "PACKAGE_INTEGRITY_MISSING"
  | "PACKAGE_INTEGRITY_ALGORITHM_UNSUPPORTED"
  | "PACKAGE_MEDIA_TYPE_MISMATCH"
  | "PACKAGE_ACTION_SUMMARY_MISMATCH"
  | "PACKAGE_ACTION_CONFIG_SCHEMA_UNSUPPORTED"
  | "PACKAGE_ACTION_KEY_MISMATCH"
  | "PACKAGE_FRAME_INDEX_INVALID"
  | "PACKAGE_FRAME_ID_DUPLICATE"
  | "PACKAGE_FRAME_ASSET_ID_MISSING"
  | "PACKAGE_RUNTIME_VERSION_INVALID"
  | "PACKAGE_RUNTIME_VERSION_RANGE_INVALID"
  | "PACKAGE_PREVIEW_UNDECLARED"
  | "PACKAGE_RESOURCE_NOT_DECLARED"
  | "PACKAGE_RESOURCE_HASH_MISMATCH";

export const PackageErrorCodes = {
  PET_IDENTITY_CONFLICT: "PET_IDENTITY_CONFLICT",
  RELEASE_VERSION_CONFLICT: "RELEASE_VERSION_CONFLICT",
  RELEASE_CONTENT_CONFLICT: "RELEASE_CONTENT_CONFLICT",
  PACKAGE_SCHEMA_UNSUPPORTED: "PACKAGE_SCHEMA_UNSUPPORTED",
  PACKAGE_SCHEMA_MISSING: "PACKAGE_SCHEMA_MISSING",
  PACKAGE_MANIFEST_INVALID: "PACKAGE_MANIFEST_INVALID",
  PACKAGE_PATH_INVALID: "PACKAGE_PATH_INVALID",
  PACKAGE_ARCHIVE_BOMB: "PACKAGE_ARCHIVE_BOMB",
  PACKAGE_DUPLICATE_ENTRY: "PACKAGE_DUPLICATE_ENTRY",
  PACKAGE_EXECUTABLE_FORBIDDEN: "PACKAGE_EXECUTABLE_FORBIDDEN",
  PACKAGE_SYMLINK_FORBIDDEN: "PACKAGE_SYMLINK_FORBIDDEN",
  PACKAGE_HASH_MISMATCH: "PACKAGE_HASH_MISMATCH",
  PACKAGE_FILE_UNDECLARED: "PACKAGE_FILE_UNDECLARED",
  PACKAGE_FILE_MISSING: "PACKAGE_FILE_MISSING",
  PACKAGE_RUNTIME_INCOMPATIBLE: "PACKAGE_RUNTIME_INCOMPATIBLE",
  PACKAGE_QUALITY_GATE_BLOCKED: "PACKAGE_QUALITY_GATE_BLOCKED",
  PACKAGE_BINDING_NOT_ALLOWED: "PACKAGE_BINDING_NOT_ALLOWED",
  ACTION_CONFIG_MISSING: "ACTION_CONFIG_MISSING",
  ACTION_CONFIG_INVALID: "ACTION_CONFIG_INVALID",
  ACTION_REFERENCE_INVALID: "ACTION_REFERENCE_INVALID",
  FRAME_MISSING: "FRAME_MISSING",
  FRAME_HASH_MISMATCH: "FRAME_HASH_MISMATCH",
  PATH_ESCAPE_REJECTED: "PATH_ESCAPE_REJECTED",
  DEFAULT_ACTION_INVALID: "DEFAULT_ACTION_INVALID",
  RUNTIME_VERSION_UNSUPPORTED: "RUNTIME_VERSION_UNSUPPORTED",
  PACKAGE_JSON_DUPLICATE_KEY: "PACKAGE_JSON_DUPLICATE_KEY",
  PACKAGE_JSON_UNKNOWN_FIELD: "PACKAGE_JSON_UNKNOWN_FIELD",
  PACKAGE_MANIFEST_HASH_MISSING: "PACKAGE_MANIFEST_HASH_MISSING",
  PACKAGE_MANIFEST_HASH_MISMATCH: "PACKAGE_MANIFEST_HASH_MISMATCH",
  PACKAGE_INTEGRITY_MISSING: "PACKAGE_INTEGRITY_MISSING",
  PACKAGE_INTEGRITY_ALGORITHM_UNSUPPORTED: "PACKAGE_INTEGRITY_ALGORITHM_UNSUPPORTED",
  PACKAGE_MEDIA_TYPE_MISMATCH: "PACKAGE_MEDIA_TYPE_MISMATCH",
  PACKAGE_ACTION_SUMMARY_MISMATCH: "PACKAGE_ACTION_SUMMARY_MISMATCH",
  PACKAGE_ACTION_CONFIG_SCHEMA_UNSUPPORTED: "PACKAGE_ACTION_CONFIG_SCHEMA_UNSUPPORTED",
  PACKAGE_ACTION_KEY_MISMATCH: "PACKAGE_ACTION_KEY_MISMATCH",
  PACKAGE_FRAME_INDEX_INVALID: "PACKAGE_FRAME_INDEX_INVALID",
  PACKAGE_FRAME_ID_DUPLICATE: "PACKAGE_FRAME_ID_DUPLICATE",
  PACKAGE_FRAME_ASSET_ID_MISSING: "PACKAGE_FRAME_ASSET_ID_MISSING",
  PACKAGE_RUNTIME_VERSION_INVALID: "PACKAGE_RUNTIME_VERSION_INVALID",
  PACKAGE_RUNTIME_VERSION_RANGE_INVALID: "PACKAGE_RUNTIME_VERSION_RANGE_INVALID",
  PACKAGE_PREVIEW_UNDECLARED: "PACKAGE_PREVIEW_UNDECLARED",
  PACKAGE_RESOURCE_NOT_DECLARED: "PACKAGE_RESOURCE_NOT_DECLARED",
  PACKAGE_RESOURCE_HASH_MISMATCH: "PACKAGE_RESOURCE_HASH_MISMATCH",
} as const;

export const SEVERITY_ERROR = "error";
export const SEVERITY_WARNING = "warning";
export const SEVERITY_INFO = "info";

export interface PackageValidationError {
  code: PackageErrorCode;
  severity: string;
  path?: string;
  actionKey?: string;
  message: string;
  expected?: string;
  actual?: string;
  remediation?: string;
}

export class PackageContractError extends Error {
  readonly code: PackageErrorCode;
  readonly path?: string;
  readonly actionKey?: string;
  readonly expected?: string;
  readonly actual?: string;

  constructor(
    code: PackageErrorCode,
    message: string,
    options?: {
      path?: string;
      actionKey?: string;
      expected?: string;
      actual?: string;
      cause?: unknown;
    },
  ) {
    super(message, options?.cause !== undefined ? { cause: options.cause } : undefined);
    this.name = "PackageContractError";
    this.code = code;
    this.path = options?.path;
    this.actionKey = options?.actionKey;
    this.expected = options?.expected;
    this.actual = options?.actual;
  }
}

export function createPackageError(
  code: PackageErrorCode,
  message: string,
  options?: {
    path?: string;
    actionKey?: string;
    expected?: string;
    actual?: string;
    cause?: unknown;
  },
): PackageContractError {
  return new PackageContractError(code, message, options);
}
