package share

const (
	ErrShareUnsupported             = "SHARE_UNSUPPORTED"
	ErrShareUnavailable             = "SHARE_UNAVAILABLE"
	ErrShareExtensionMissing        = "SHARE_EXTENSION_MISSING"
	ErrShareURLSchemeNotAllowed     = "SHARE_URL_SCHEME_NOT_ALLOWED"
	ErrShareURLInvalid              = "SHARE_URL_INVALID"
	ErrShareTooManyResources        = "SHARE_TOO_MANY_RESOURCES"
	ErrShareResourceTooLarge        = "SHARE_RESOURCE_TOO_LARGE"
	ErrShareTotalTooLarge           = "SHARE_TOTAL_TOO_LARGE"
	ErrShareTextTooLong             = "SHARE_TEXT_TOO_LONG"
	ErrShareSubjectTooLong          = "SHARE_SUBJECT_TOO_LONG"
	ErrShareShareTitleTooLong       = "SHARE_SHARE_TITLE_TOO_LONG"
	ErrSharePreviewTitleTooLong     = "SHARE_PREVIEW_TITLE_TOO_LONG"
	ErrSharePreviewSubtitleTooLong  = "SHARE_PREVIEW_SUBTITLE_TOO_LONG"
	ErrSharePreviewImageRequired    = "SHARE_PREVIEW_IMAGE_REQUIRED"
	ErrShareResourceInvalid        = "SHARE_RESOURCE_INVALID"
	ErrShareMaterializationFailed   = "SHARE_MATERIALIZATION_FAILED"
	ErrShareSendFailed              = "SHARE_SEND_FAILED"
	ErrShareUserCancelled           = "SHARE_USER_CANCELLED"
	ErrShareUIContextRequired       = "SHARE_UI_CONTEXT_REQUIRED"
	ErrShareUserIntentRequired      = "SHARE_USER_INTENT_REQUIRED"
	ErrShareCannotPresentOnPhone    = "SHARE_CANNOT_PRESENT_ON_PHONE"
	ErrShareCannotPresentOn iPad    = "SHARE_CANNOT_PRESENT_ON_IPAD"
	ErrShareReceivedNotFound        = "SHARE_RECEIVED_NOT_FOUND"
	ErrShareReceivedStale           = "SHARE_RECEIVED_STALE"
	ErrShareReceivedEmpty           = "SHARE_RECEIVED_EMPTY"
	ErrShareStagingInvalid          = "SHARE_STAGING_INVALID"
	ErrShareStagingNotCommitted     = "SHARE_STAGING_NOT_COMMITTED"
	ErrShareStagingMissingFiles     = "SHARE_STAGING_MISSING_FILES"
	ErrShareStagingHashMismatch     = "SHARE_STAGING_HASH_MISMATCH"
	ErrShareStagingPathEscape       = "SHARE_STAGING_PATH_ESCAPE"
	ErrShareStagingTooManyResources = "SHARE_STAGING_TOO_MANY_RESOURCES"
	ErrShareStagingTooLarge         = "SHARE_STAGING_TOO_LARGE"
	ErrShareStagingTextTooLong      = "SHARE_STAGING_TEXT_TOO_LONG"
	ErrShareIntakeFailed            = "SHARE_INTAKE_FAILED"
	ErrShareCleanupFailed           = "SHARE_CLEANUP_FAILED"
	ErrReceivedContainsUnsupportedAttachments = "SHARE_RECEIVED_CONTAINS_UNSUPPORTED_ATTACHMENTS"
	ErrShareRestoreUnsupported      = "SHARE_RESTORE_UNSUPPORTED"
	ErrShareRestoreInvalidState     = "SHARE_RESTORE_INVALID_STATE"
	ErrOutcomeUnknown               = "SHARE_OUTCOME_UNKNOWN"
	ErrNativeBridgeUnavailable      = "SHARE_NATIVE_BRIDGE_UNAVAILABLE"
	ErrInvalidResponse              = "SHARE_INVALID_RESPONSE"
	ErrTimeout                      = "SHARE_TIMEOUT"
	ErrCancelled                    = "SHARE_CANCELLED"
)
