package interaction

const (
	INTERACTION_UNSUPPORTED           = "INTERACTION_UNSUPPORTED"
	INTERACTION_UNAVAILABLE           = "INTERACTION_UNAVAILABLE"
	INTERACTION_INVALID_REQUEST       = "INTERACTION_INVALID_REQUEST"

	INTERACTION_NODE_NOT_FOUND        = "INTERACTION_NODE_NOT_FOUND"
	INTERACTION_NODE_STALE            = "INTERACTION_NODE_STALE"
	INTERACTION_CONTEXT_CHANGED       = "INTERACTION_CONTEXT_CHANGED"

	INTERACTION_ACTION_UNSUPPORTED    = "INTERACTION_ACTION_UNSUPPORTED"
	INTERACTION_ACTION_FAILED         = "INTERACTION_ACTION_FAILED"
	INTERACTION_OUTCOME_UNKNOWN       = "INTERACTION_OUTCOME_UNKNOWN"

	INTERACTION_COORDINATE_INVALID    = "INTERACTION_COORDINATE_INVALID"
	INTERACTION_DISPLAY_UNAVAILABLE   = "INTERACTION_DISPLAY_UNAVAILABLE"

	INTERACTION_TEXT_INPUT_UNSUPPORTED   = "INTERACTION_TEXT_INPUT_UNSUPPORTED"
	INTERACTION_SENSITIVE_INPUT_DENIED   = "INTERACTION_SENSITIVE_INPUT_DENIED"

	INTERACTION_VISUAL_UNAVAILABLE        = "INTERACTION_VISUAL_UNAVAILABLE"
	INTERACTION_SCREENSHOT_FAILED         = "INTERACTION_SCREENSHOT_FAILED"
	INTERACTION_VISUAL_TARGET_NOT_FOUND   = "INTERACTION_VISUAL_TARGET_NOT_FOUND"
	INTERACTION_VISUAL_TARGET_AMBIGUOUS   = "INTERACTION_VISUAL_TARGET_AMBIGUOUS"
	INTERACTION_VISUAL_STATE_STALE        = "INTERACTION_VISUAL_STATE_STALE"

	INTERACTION_ROOT_UNAVAILABLE       = "INTERACTION_ROOT_UNAVAILABLE"
	INTERACTION_ADB_UNAVAILABLE        = "INTERACTION_ADB_UNAVAILABLE"

	INTERACTION_VERIFICATION_FAILED    = "INTERACTION_VERIFICATION_FAILED"

	INTERACTION_TIMEOUT               = "INTERACTION_TIMEOUT"
	INTERACTION_CANCELLED             = "INTERACTION_CANCELLED"
	INTERACTION_NATIVE_HOST_UNAVAILABLE = "INTERACTION_NATIVE_HOST_UNAVAILABLE"
)

func MapInteractionErrorToCanonical(code string) string {
	switch code {
	case INTERACTION_UNSUPPORTED:
		return "PLATFORM_NOT_SUPPORTED"
	case INTERACTION_UNAVAILABLE:
		return "PROVIDER_UNAVAILABLE"
	case INTERACTION_INVALID_REQUEST:
		return "AUTHORIZATION_DENIED"
	case INTERACTION_NODE_NOT_FOUND:
		return "PROVIDER_UNAVAILABLE"
	case INTERACTION_NODE_STALE:
		return "BRIDGE_INVALID_RESPONSE"
	case INTERACTION_CONTEXT_CHANGED:
		return "BRIDGE_INVALID_RESPONSE"
	case INTERACTION_ACTION_UNSUPPORTED:
		return "PLATFORM_NOT_SUPPORTED"
	case INTERACTION_ACTION_FAILED:
		return "PROVIDER_UNAVAILABLE"
	case INTERACTION_OUTCOME_UNKNOWN:
		return "PROVIDER_UNAVAILABLE"
	case INTERACTION_COORDINATE_INVALID:
		return "AUTHORIZATION_DENIED"
	case INTERACTION_DISPLAY_UNAVAILABLE:
		return "PROVIDER_UNAVAILABLE"
	case INTERACTION_TEXT_INPUT_UNSUPPORTED:
		return "PLATFORM_NOT_SUPPORTED"
	case INTERACTION_SENSITIVE_INPUT_DENIED:
		return "AUTHORIZATION_DENIED"
	case INTERACTION_VISUAL_UNAVAILABLE:
		return "PROVIDER_UNAVAILABLE"
	case INTERACTION_SCREENSHOT_FAILED:
		return "PROVIDER_UNAVAILABLE"
	case INTERACTION_VISUAL_TARGET_NOT_FOUND:
		return "PROVIDER_UNAVAILABLE"
	case INTERACTION_VISUAL_TARGET_AMBIGUOUS:
		return "BRIDGE_INVALID_RESPONSE"
	case INTERACTION_VISUAL_STATE_STALE:
		return "BRIDGE_INVALID_RESPONSE"
	case INTERACTION_ROOT_UNAVAILABLE:
		return "PROVIDER_UNAVAILABLE"
	case INTERACTION_ADB_UNAVAILABLE:
		return "PROVIDER_UNAVAILABLE"
	case INTERACTION_VERIFICATION_FAILED:
		return "PROVIDER_UNAVAILABLE"
	case INTERACTION_TIMEOUT:
		return "BRIDGE_TIMEOUT"
	case INTERACTION_CANCELLED:
		return "CANCELLED"
	case INTERACTION_NATIVE_HOST_UNAVAILABLE:
		return "PROVIDER_UNAVAILABLE"
	default:
		return "PROVIDER_UNAVAILABLE"
	}
}

const (
	PermissionInteractionReadVisual = "android.interaction.read_visual"
	PermissionInteractionClick      = "android.interaction.click"
	PermissionInteractionInput      = "android.interaction.input"
	PermissionInteractionGesture    = "android.interaction.gesture"
	PermissionInteractionCoordinate = "android.interaction.coordinate"
	PermissionInteractionRoot       = "android.interaction.root"
	PermissionInteractionADB        = "android.interaction.adb"
)
