package interaction

import "testing"

func TestMapInteractionErrorToCanonical(t *testing.T) {
	tests := []struct {
		domainCode string
		expected   string
	}{
		{INTERACTION_UNSUPPORTED, "PLATFORM_NOT_SUPPORTED"},
		{INTERACTION_UNAVAILABLE, "PROVIDER_UNAVAILABLE"},
		{INTERACTION_INVALID_REQUEST, "AUTHORIZATION_DENIED"},
		{INTERACTION_NODE_NOT_FOUND, "PROVIDER_UNAVAILABLE"},
		{INTERACTION_NODE_STALE, "BRIDGE_INVALID_RESPONSE"},
		{INTERACTION_CONTEXT_CHANGED, "BRIDGE_INVALID_RESPONSE"},
		{INTERACTION_ACTION_UNSUPPORTED, "PLATFORM_NOT_SUPPORTED"},
		{INTERACTION_ACTION_FAILED, "PROVIDER_UNAVAILABLE"},
		{INTERACTION_OUTCOME_UNKNOWN, "PROVIDER_UNAVAILABLE"},
		{INTERACTION_COORDINATE_INVALID, "AUTHORIZATION_DENIED"},
		{INTERACTION_DISPLAY_UNAVAILABLE, "PROVIDER_UNAVAILABLE"},
		{INTERACTION_TEXT_INPUT_UNSUPPORTED, "PLATFORM_NOT_SUPPORTED"},
		{INTERACTION_SENSITIVE_INPUT_DENIED, "AUTHORIZATION_DENIED"},
		{INTERACTION_VISUAL_UNAVAILABLE, "PROVIDER_UNAVAILABLE"},
		{INTERACTION_SCREENSHOT_FAILED, "PROVIDER_UNAVAILABLE"},
		{INTERACTION_VISUAL_TARGET_NOT_FOUND, "PROVIDER_UNAVAILABLE"},
		{INTERACTION_VISUAL_TARGET_AMBIGUOUS, "BRIDGE_INVALID_RESPONSE"},
		{INTERACTION_VISUAL_STATE_STALE, "BRIDGE_INVALID_RESPONSE"},
		{INTERACTION_ROOT_UNAVAILABLE, "PROVIDER_UNAVAILABLE"},
		{INTERACTION_ADB_UNAVAILABLE, "PROVIDER_UNAVAILABLE"},
		{INTERACTION_VERIFICATION_FAILED, "PROVIDER_UNAVAILABLE"},
		{INTERACTION_TIMEOUT, "BRIDGE_TIMEOUT"},
		{INTERACTION_CANCELLED, "CANCELLED"},
		{INTERACTION_NATIVE_HOST_UNAVAILABLE, "PROVIDER_UNAVAILABLE"},
		{"UNKNOWN_CODE", "PROVIDER_UNAVAILABLE"},
	}

	for _, tt := range tests {
		t.Run(tt.domainCode, func(t *testing.T) {
			got := MapInteractionErrorToCanonical(tt.domainCode)
			if got != tt.expected {
				t.Fatalf("expected %s, got %s", tt.expected, got)
			}
		})
	}
}

func TestError_Error(t *testing.T) {
	err := &Error{Code: INTERACTION_ACTION_FAILED, Message: "action failed"}
	expected := "INTERACTION_ACTION_FAILED: action failed"
	if err.Error() != expected {
		t.Fatalf("expected %q, got %q", expected, err.Error())
	}
}

func TestNewError(t *testing.T) {
	err := NewError(INTERACTION_NODE_STALE, "node expired")
	if err.Code != INTERACTION_NODE_STALE {
		t.Fatalf("expected INTERACTION_NODE_STALE, got %s", err.Code)
	}
	if err.Message != "node expired" {
		t.Fatalf("expected 'node expired', got %s", err.Message)
	}
}
